local function node(def)
  def.quality = def.quality or 'rare'
  def.editor_skill_id = def.editor_skill_id or nil
  def.icon = def.icon or nil
  def.attr = def.attr or {}
  def.runtime = def.runtime or {}
  def.desc = def.desc or {}
  def.route_tags = def.route_tags or {}
  def.next_ids = def.next_ids or {}
  def.unlock_rewards = def.unlock_rewards or {}
  return def
end

local list = {
  node({
    id = 'bond_body_core',
    display_name = '体术',
    group_id = 'body',
    line_id = 'line_body_core',
    tier = 1,
    parent_id = nil,
    next_ids = { 'bond_body_core_momentum' },
    route_tags = { 'auto_fighting_spirit' },
    template = 'static_attr',
    icon = 107362,
    editor_skill_id = 201385560,
    desc = {
      single = '利刃：攻击力+50，力量+50。',
      advanced = '斗气场域：每秒对周围1200范围内的敌人造成60%力量的自适应伤害。',
    },
  }),
  node({
    id = 'bond_body_core_momentum',
    display_name = '气势',
    group_id = 'body',
    line_id = 'line_body_core',
    tier = 1,
    parent_id = 'bond_body_core',
    next_ids = { 'bond_body_core_vitality' },
    route_tags = {},
    template = 'static_attr',
    icon = 107362,
    editor_skill_id = 201385560,
    runtime = { all_damage_bonus = 0.04 },
    desc = {
      single = '气势：所有伤害+4%。',
      advanced = '斗气场域：每秒对周围1200范围内的敌人造成60%力量的自适应伤害。',
    },
  }),
  node({
    id = 'bond_body_core_vitality',
    display_name = '生命值+100',
    group_id = 'body',
    line_id = 'line_body_core',
    tier = 1,
    parent_id = 'bond_body_core_momentum',
    next_ids = {
      'bond_body_tactics',
      'bond_body_fortress',
      'bond_body_life',
      'bond_body_charge_breaker',
      'bond_body_blood_oath',
      'bond_body_blood_demon',
    },
    route_tags = {},
    template = 'static_attr',
    icon = 107362,
    editor_skill_id = 201385560,
    attr = {
      ['生命'] = 100,
      ['力量'] = 50,
    },
    desc = {
      single = '生命值+100：生命值+100，力量+50。',
      advanced = '基础体术已凑齐，开启后续分支。',
    },
  }),
  node({
    id = 'bond_economy_core',
    display_name = '经济',
    group_id = 'economy',
    line_id = 'line_economy_core',
    tier = 1,
    parent_id = nil,
    next_ids = { 'bond_economy_core_exp' },
    route_tags = { 'economy' },
    template = 'kill_stack',
    icon = 106694,
    editor_skill_id = 201385558,
    runtime = {
      wood_per_sec_bonus = 0.5,
      gold_per_sec_bonus = 15,
    },
    desc = {
      single = '杀敌金币+10%。杀敌经验+10%。杀敌加成+10%。',
      advanced = '每秒木材+0.5，每秒金币+15。',
    },
  }),
  node({
    id = 'bond_economy_core_exp',
    display_name = '杀敌经验+10%',
    group_id = 'economy',
    line_id = 'line_economy_core',
    tier = 1,
    parent_id = 'bond_economy_core',
    next_ids = { 'bond_economy_core_reward' },
    route_tags = {},
    template = 'kill_stack',
    icon = 106694,
    editor_skill_id = 201385558,
    runtime = { kill_reward_ratio = 0.10 },
    desc = {
      single = '杀敌经验+10%。',
      advanced = '每秒木材+0.5，每秒金币+15。',
    },
  }),
  node({
    id = 'bond_economy_core_reward',
    display_name = '杀敌加成+10%',
    group_id = 'economy',
    line_id = 'line_economy_core',
    tier = 1,
    parent_id = 'bond_economy_core_exp',
    next_ids = { 'bond_economy_greed', 'bond_economy_challenge' },
    route_tags = {},
    template = 'kill_stack',
    icon = 106694,
    editor_skill_id = 201385558,
    runtime = { kill_reward_ratio = 0.10 },
    desc = {
      single = '杀敌加成+10%。',
      advanced = '基础经济已凑齐，开启后续分支。',
    },
  }),
  node({
    id = 'bond_magic_core',
    display_name = '法术',
    group_id = 'magic',
    line_id = 'line_magic_core',
    tier = 1,
    parent_id = nil,
    next_ids = { 'bond_magic_core_amp' },
    route_tags = { 'skill', 'spell_cycle', 'auto_spell_burst' },
    template = 'per_second_growth',
    icon = 107016,
    editor_skill_id = 201385553,
    desc = {
      single = '法术威力：技能伤害+5%。',
      advanced = '魔爆术：每隔18秒，触发1次魔爆术，对300范围内的敌人造成200%智力的自适应伤害。',
    },
  }),
  node({
    id = 'bond_magic_core_amp',
    display_name = '法术增幅',
    group_id = 'magic',
    line_id = 'line_magic_core',
    tier = 1,
    parent_id = 'bond_magic_core',
    next_ids = { 'bond_magic_core_essence' },
    route_tags = {},
    template = 'per_second_growth',
    icon = 107016,
    editor_skill_id = 201385553,
    runtime = { spell_damage_bonus = 0.075 },
    desc = {
      single = '法术增幅：魔法伤害+7.5%。',
      advanced = '魔爆术：每隔18秒，触发1次魔爆术，对300范围内的敌人造成200%智力的自适应伤害。',
    },
  }),
  node({
    id = 'bond_magic_core_essence',
    display_name = '法师奥义',
    group_id = 'magic',
    line_id = 'line_magic_core',
    tier = 1,
    parent_id = 'bond_magic_core_amp',
    next_ids = {
      'bond_magic_arcane_power',
      'bond_magic_trick',
      'bond_magic_haste',
    },
    route_tags = {},
    template = 'per_second_growth',
    icon = 107016,
    editor_skill_id = 201385553,
    attr = {
      ['攻击'] = 50,
      ['智力'] = 50,
    },
    desc = {
      single = '法师奥义：攻击力+50，智力+50。',
      advanced = '基础法术已凑齐，开启后续分支。',
    },
  }),
  node({
    id = 'bond_archery_core',
    display_name = '箭术',
    group_id = 'archery',
    line_id = 'line_archery_core',
    tier = 1,
    parent_id = nil,
    next_ids = { 'bond_archery_core_burst' },
    route_tags = { 'clear', 'tempo' },
    template = 'basic_attack_modifier',
    icon = 107004,
    editor_skill_id = 201385551,
    desc = {
      single = '箭矢弹射：攻击力+50，弹射伤害+5%。',
      advanced = '穿云箭：每攻击15次，射出1支穿云箭，对直线敌人造成300%敏捷的自适应伤害。',
    },
  }),
  node({
    id = 'bond_archery_core_burst',
    display_name = '箭矢扩散',
    group_id = 'archery',
    line_id = 'line_archery_core',
    tier = 1,
    parent_id = 'bond_archery_core',
    next_ids = { 'bond_archery_core_stance' },
    route_tags = {},
    template = 'basic_attack_modifier',
    icon = 107004,
    editor_skill_id = 201385551,
    attr = {
      ['攻击'] = 50,
      ['多重伤害'] = 5,
    },
    desc = {
      single = '箭矢扩散：攻击力+50，多重伤害+5%。',
      advanced = '穿云箭：每攻击15次，射出1支穿云箭，对直线敌人造成300%敏捷的自适应伤害。',
    },
  }),
  node({
    id = 'bond_archery_core_stance',
    display_name = '射手姿态',
    group_id = 'archery',
    line_id = 'line_archery_core',
    tier = 1,
    parent_id = 'bond_archery_core_burst',
    next_ids = { 'bond_archery_barrage', 'bond_archery_rapid', 'bond_archery_shooting' },
    route_tags = {},
    template = 'basic_attack_modifier',
    icon = 107004,
    editor_skill_id = 201385551,
    attr = {
      ['攻击'] = 50,
      ['敏捷'] = 50,
    },
    desc = {
      single = '射手姿态：攻击力+50，敏捷+50。',
      advanced = '基础箭术已凑齐，开启后续分支。',
    },
  }),
  node({
    id = 'bond_critical_core',
    display_name = '暴击',
    group_id = 'critical',
    line_id = 'line_critical_core',
    tier = 1,
    parent_id = nil,
    next_ids = { 'bond_critical_core_damage' },
    route_tags = { 'burst' },
    template = 'basic_attack_modifier',
    icon = 106810,
    editor_skill_id = 201385546,
    attr = {
      ['物理暴击'] = 3,
      ['魔法暴击'] = 3,
    },
    desc = {
      single = '暴击强化：物理暴击+3%，魔法暴击+3%。',
      advanced = '物理暴击+4%，魔法暴击+4%。',
    },
  }),
  node({
    id = 'bond_critical_core_damage',
    display_name = '暴伤强化',
    group_id = 'critical',
    line_id = 'line_critical_core',
    tier = 1,
    parent_id = 'bond_critical_core',
    next_ids = { 'bond_critical_deadly' },
    route_tags = {},
    template = 'basic_attack_modifier',
    icon = 106810,
    editor_skill_id = 201385546,
    attr = {
      ['物理暴伤'] = 10,
      ['魔法暴伤'] = 10,
    },
    desc = {
      single = '暴伤强化：物理暴伤+10%，魔法暴伤+10%。',
      advanced = '基础暴击已凑齐，开启后续分支。',
    },
  }),
  node({
    id = 'bond_growth_core',
    display_name = '成长',
    group_id = 'growth',
    line_id = 'line_growth_core',
    tier = 1,
    parent_id = nil,
    next_ids = { 'bond_growth_core_agility_up' },
    route_tags = { 'growth' },
    template = 'per_second_growth',
    icon = 106724,
    editor_skill_id = 201385537,
    runtime = {
      wood_per_sec_bonus = 0.3,
      agility_on_kill = 0.1,
      strength_on_kill = 0.1,
      intelligence_on_kill = 0.1,
    },
    desc = {
      single = '智力提升：每秒智力+0.5。',
      advanced = '每秒木材+0.3，杀敌力量+0.1，杀敌敏捷+0.1，杀敌智力+0.1。',
    },
  }),
  node({
    id = 'bond_growth_core_agility_up',
    display_name = '敏捷提升',
    group_id = 'growth',
    line_id = 'line_growth_core',
    tier = 1,
    parent_id = 'bond_growth_core',
    next_ids = { 'bond_growth_core_strength_up' },
    route_tags = {},
    template = 'per_second_growth',
    icon = 106724,
    editor_skill_id = 201385537,
    runtime = { agility_per_second = 0.5 },
    desc = {
      single = '敏捷提升：每秒敏捷+0.5。',
      advanced = '每秒木材+0.3，杀敌力量+0.1，杀敌敏捷+0.1，杀敌智力+0.1。',
    },
  }),
  node({
    id = 'bond_growth_core_strength_up',
    display_name = '力量提升',
    group_id = 'growth',
    line_id = 'line_growth_core',
    tier = 1,
    parent_id = 'bond_growth_core_agility_up',
    next_ids = { 'bond_growth_core_attack_up' },
    route_tags = {},
    template = 'per_second_growth',
    icon = 106724,
    editor_skill_id = 201385537,
    runtime = { strength_per_second = 0.5 },
    desc = {
      single = '力量提升：每秒力量+0.5。',
      advanced = '每秒木材+0.3，杀敌力量+0.1，杀敌敏捷+0.1，杀敌智力+0.1。',
    },
  }),
  node({
    id = 'bond_growth_core_attack_up',
    display_name = '攻击提升',
    group_id = 'growth',
    line_id = 'line_growth_core',
    tier = 1,
    parent_id = 'bond_growth_core_strength_up',
    next_ids = { 'bond_growth_agility', 'bond_growth_strength', 'bond_growth_intelligence' },
    route_tags = {},
    template = 'per_second_growth',
    icon = 106724,
    editor_skill_id = 201385537,
    runtime = { attack_per_second = 0.5 },
    desc = {
      single = '攻击提升：每秒攻击+0.5。',
      advanced = '基础成长已凑齐，开启后续分支。',
    },
  }),
  node({
    id = 'bond_growth_agility',
    display_name = '敏捷',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 2,
    parent_id = 'bond_growth_core_attack_up',
    next_ids = { 'bond_growth_agility_grant' },
    route_tags = {},
    template = 'static_attr',
    icon = 106724,
    editor_skill_id = 201385537,
    attr = { ['敏捷'] = 100 },
    unlock_rewards = { wood = 50 },
    desc = {
      single = '敏捷之源：敏捷+100，木材+50。',
      advanced = '杀敌敏捷+0.1，每秒敏捷+0.2，物理伤害+8%。',
    },
  }),
  node({
    id = 'bond_growth_agility_grant',
    display_name = '赋予敏捷',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 2,
    parent_id = 'bond_growth_agility',
    next_ids = { 'bond_growth_agility_growth' },
    route_tags = {},
    template = 'static_attr',
    icon = 106724,
    editor_skill_id = 201385537,
    attr = { ['敏捷'] = 100 },
    desc = {
      single = '赋予敏捷：敏捷+100。',
      advanced = '杀敌敏捷+0.1，每秒敏捷+0.2，物理伤害+8%。',
    },
  }),
  node({
    id = 'bond_growth_agility_growth',
    display_name = '敏捷成长',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 2,
    parent_id = 'bond_growth_agility_grant',
    next_ids = { 'bond_growth_agility_amp' },
    route_tags = {},
    template = 'static_attr',
    icon = 106724,
    editor_skill_id = 201385537,
    runtime = { agility_per_second = 0.3 },
    desc = {
      single = '敏捷成长：每秒敏捷+0.3。',
      advanced = '杀敌敏捷+0.1，每秒敏捷+0.2，物理伤害+8%。',
    },
  }),
  node({
    id = 'bond_growth_agility_amp',
    display_name = '敏捷增幅',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 2,
    parent_id = 'bond_growth_agility_growth',
    next_ids = { 'bond_growth_demon_hunter' },
    route_tags = {},
    template = 'static_attr',
    icon = 106724,
    editor_skill_id = 201385537,
    attr = { ['敏捷增幅'] = 5 },
    desc = {
      single = '敏捷增幅：敏捷增幅+5%。',
      advanced = '我要玩敏捷！卡池中加入敏捷相关的基础卡牌。',
    },
  }),
  node({
    id = 'bond_growth_demon_hunter',
    display_name = '猎魔人',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 2,
    parent_id = 'bond_growth_agility_amp',
    next_ids = { 'bond_growth_demon_hunter_heartseeker' },
    route_tags = {},
    template = 'basic_attack_modifier',
    icon = 108140,
    editor_skill_id = 201385538,
    attr = {
      ['攻击范围'] = 100,
      ['敏捷'] = 120,
    },
    desc = {
      single = '蓄力射击：攻击范围+100，敏捷+120。',
      advanced = '当局每进化1次，就会使敏捷增幅+2%，每秒敏捷+0.2，物理伤害+3%。',
    },
  }),
  node({
    id = 'bond_growth_demon_hunter_heartseeker',
    display_name = '觅心箭',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 2,
    parent_id = 'bond_growth_demon_hunter',
    next_ids = { 'bond_growth_demon_hunter_rapid' },
    route_tags = {},
    template = 'basic_attack_modifier',
    icon = 108140,
    editor_skill_id = 201385538,
    attr = {
      ['物理暴击'] = 6,
    },
    desc = {
      single = '觅心箭：物理暴击+6%。',
      advanced = '当局每进化1次，就会使敏捷增幅+2%，每秒敏捷+0.2，物理伤害+3%。',
    },
  }),
  node({
    id = 'bond_growth_demon_hunter_rapid',
    display_name = '急速射击',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 2,
    parent_id = 'bond_growth_demon_hunter_heartseeker',
    next_ids = { 'bond_growth_demon_hunter_hunt' },
    route_tags = {},
    template = 'basic_attack_modifier',
    icon = 108140,
    editor_skill_id = 201385538,
    attr = {
      ['攻击速度'] = 25,
    },
    desc = {
      single = '急速射击：攻速+25%，攻击间隔-0.1。',
      advanced = '当局每进化1次，就会使敏捷增幅+2%，每秒敏捷+0.2，物理伤害+3%。',
    },
  }),
  node({
    id = 'bond_growth_demon_hunter_hunt',
    display_name = '射猎技巧',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 2,
    parent_id = 'bond_growth_demon_hunter_rapid',
    next_ids = { 'bond_growth_bow_god' },
    route_tags = { 'growth', 'boss', 'tempo' },
    template = 'basic_attack_modifier',
    icon = 108140,
    editor_skill_id = 201385538,
    runtime = {
      agility_per_second = 0.2,
      all_damage_bonus = 0.03,
    },
    desc = {
      single = '射猎技巧：多重伤害+10%，弹射伤害+10%。',
      advanced = '当局每进化1次，就会使敏捷增幅+2%，每秒敏捷+0.2，物理伤害+3%。',
    },
  }),
  node({
    id = 'bond_growth_bow_god',
    display_name = '弓神',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 3,
    parent_id = 'bond_growth_demon_hunter_hunt',
    next_ids = { 'bond_growth_bow_god_piercing' },
    route_tags = {},
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 108148,
    editor_skill_id = 201385539,
    attr = {
      ['命中'] = 20,
      ['最终伤害'] = 4,
    },
    desc = {
      single = '瞄准射击：命中+20%，最终伤害+4%。',
      advanced = '最终敏捷+5%，每点敏捷额外提供0.1攻击力。',
    },
  }),
  node({
    id = 'bond_growth_bow_god_piercing',
    display_name = '百步穿杨',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 3,
    parent_id = 'bond_growth_bow_god',
    next_ids = { 'bond_growth_bow_god_master' },
    route_tags = {},
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 108148,
    editor_skill_id = 201385539,
    attr = {
      ['攻击范围'] = 150,
    },
    runtime = {
      normal_attack_damage_bonus = 0.12,
    },
    desc = {
      single = '百步穿杨：攻击范围+150，普攻伤害+12%。',
      advanced = '最终敏捷+5%，每点敏捷额外提供0.1攻击力。',
    },
  }),
  node({
    id = 'bond_growth_bow_god_master',
    display_name = '弓箭大师',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 3,
    parent_id = 'bond_growth_bow_god_piercing',
    next_ids = {},
    route_tags = { 'growth', 'boss', 'clear' },
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 108148,
    editor_skill_id = 201385539,
    runtime = {
      multishot_bonus = 1,
      bounce_count_bonus = 1,
    },
    desc = {
      single = '弓箭大师：多重数量+1，弹射次数+1。',
      advanced = '最终敏捷+5%，每点敏捷额外提供0.1攻击力。',
    },
  }),
  node({
    id = 'bond_growth_strength',
    display_name = '力量',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 2,
    parent_id = 'bond_growth_core_attack_up',
    next_ids = { 'bond_growth_strength_amp' },
    route_tags = {},
    template = 'static_attr',
    icon = 106775,
    editor_skill_id = 201385540,
    attr = { ['力量'] = 100 },
    unlock_rewards = { wood = 50 },
    desc = {
      single = '力量之源：力量+100，木材+50。',
      advanced = '杀敌力量+0.1，每秒力量+0.2，生命值+200。',
    },
  }),
  node({
    id = 'bond_growth_strength_amp',
    display_name = '力量增幅',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 2,
    parent_id = 'bond_growth_strength',
    next_ids = { 'bond_growth_strength_growth' },
    route_tags = {},
    template = 'static_attr',
    icon = 106775,
    editor_skill_id = 201385540,
    attr = { ['力量增幅'] = 5 },
    desc = {
      single = '力量增幅：力量增幅+5%。',
      advanced = '杀敌力量+0.1，每秒力量+0.2，生命值+200。',
    },
  }),
  node({
    id = 'bond_growth_strength_growth',
    display_name = '力量成长',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 2,
    parent_id = 'bond_growth_strength_amp',
    next_ids = { 'bond_growth_strength_grant' },
    route_tags = {},
    template = 'static_attr',
    icon = 106775,
    editor_skill_id = 201385540,
    runtime = { strength_per_second = 0.3 },
    desc = {
      single = '力量成长：每秒力量+0.3。',
      advanced = '杀敌力量+0.1，每秒力量+0.2，生命值+200。',
    },
  }),
  node({
    id = 'bond_growth_strength_grant',
    display_name = '赋予力量',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 2,
    parent_id = 'bond_growth_strength_growth',
    next_ids = { 'bond_growth_barbarian' },
    route_tags = {},
    template = 'static_attr',
    icon = 106775,
    editor_skill_id = 201385540,
    attr = { ['力量'] = 100 },
    desc = {
      single = '赋予力量：力量+100。',
      advanced = '我要玩力量！卡池中加入力量相关的基础卡牌。',
    },
  }),
  node({
    id = 'bond_growth_barbarian',
    display_name = '野蛮人',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 2,
    parent_id = 'bond_growth_strength_grant',
    next_ids = { 'bond_growth_barbarian_steel' },
    route_tags = {},
    template = 'kill_stack',
    icon = 106751,
    editor_skill_id = 201385541,
    desc = {
      single = '狂乱：攻速+20%，所有伤害+5%。',
      advanced = '当局每进化1次，就会使力量增幅+2%，每秒力量+0.2，生命值+100。',
    },
  }),
  node({
    id = 'bond_growth_barbarian_steel',
    display_name = '钢铁之肤',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 2,
    parent_id = 'bond_growth_barbarian',
    next_ids = { 'bond_growth_barbarian_hammer' },
    route_tags = {},
    template = 'kill_stack',
    icon = 106751,
    editor_skill_id = 201385541,
    attr = {
      ['护甲'] = 10,
      ['护甲增幅'] = 5,
    },
    desc = {
      single = '钢铁之肤：护甲+10，护甲增幅+5%。',
      advanced = '当局每进化1次，就会使力量增幅+2%，每秒力量+0.2，生命值+100。',
    },
  }),
  node({
    id = 'bond_growth_barbarian_hammer',
    display_name = '先祖之锤',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 2,
    parent_id = 'bond_growth_barbarian_steel',
    next_ids = { 'bond_growth_barbarian_warcry' },
    route_tags = {},
    template = 'kill_stack',
    icon = 106751,
    editor_skill_id = 201385541,
    attr = {
      ['力量'] = 120,
      ['攻击'] = 80,
    },
    desc = {
      single = '先祖之锤：力量+120，攻击力+80。',
      advanced = '当局每进化1次，就会使力量增幅+2%，每秒力量+0.2，生命值+100。',
    },
  }),
  node({
    id = 'bond_growth_barbarian_warcry',
    display_name = '集结呐喊',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 2,
    parent_id = 'bond_growth_barbarian_hammer',
    next_ids = { 'bond_growth_war_god' },
    route_tags = { 'growth', 'burst' },
    template = 'kill_stack',
    icon = 106751,
    editor_skill_id = 201385541,
    attr = {
      ['技能急速'] = 10,
      ['生命恢复'] = 4,
    },
    runtime = { attack_on_kill = 2 },
    desc = {
      single = '集结呐喊：技能急速+10，生命恢复+4。',
      advanced = '当局每进化1次，就会使力量增幅+2%，每秒力量+0.2，生命值+100。',
    },
  }),
  node({
    id = 'bond_growth_war_god',
    display_name = '战神',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 3,
    parent_id = 'bond_growth_barbarian_warcry',
    next_ids = { 'bond_growth_war_god_guard' },
    route_tags = {},
    template = 'kill_stack',
    quality = 'epic',
    icon = 107026,
    editor_skill_id = 201385542,
    attr = {
      ['物理暴击'] = 10,
    },
    desc = {
      single = '战神之怒：物理暴击+10%。',
      advanced = '最终力量+5%，每点力量额外提供0.1攻击力。',
    },
  }),
  node({
    id = 'bond_growth_war_god_guard',
    display_name = '战神之御',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 3,
    parent_id = 'bond_growth_war_god',
    next_ids = { 'bond_growth_war_god_power' },
    route_tags = {},
    template = 'kill_stack',
    quality = 'epic',
    icon = 107026,
    editor_skill_id = 201385542,
    attr = {
      ['生命'] = 800,
      ['护甲'] = 10,
      ['格挡'] = 5,
    },
    desc = {
      single = '战神之御：生命值+800，护甲+10，格挡+5。',
      advanced = '最终力量+5%，每点力量额外提供0.1攻击力。',
    },
  }),
  node({
    id = 'bond_growth_war_god_power',
    display_name = '战神之力',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 3,
    parent_id = 'bond_growth_war_god_guard',
    next_ids = {},
    route_tags = { 'growth', 'burst' },
    template = 'kill_stack',
    quality = 'epic',
    icon = 107026,
    editor_skill_id = 201385542,
    attr = {
      ['力量'] = 200,
      ['力量增幅'] = 10,
    },
    runtime = { attack_on_kill = 4 },
    desc = {
      single = '战神之力：力量+200，力量增幅+10%。',
      advanced = '最终力量+5%，每点力量额外提供0.1攻击力。',
    },
  }),
  node({
    id = 'bond_growth_intelligence',
    display_name = '智力',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 2,
    parent_id = 'bond_growth_core_attack_up',
    next_ids = { 'bond_growth_intelligence_grant' },
    route_tags = {},
    template = 'static_attr',
    icon = 106912,
    editor_skill_id = 201385543,
    attr = { ['智力'] = 100 },
    unlock_rewards = { wood = 50 },
    desc = {
      single = '智力之源：智力+100，木材+50。',
      advanced = '杀敌智力+0.1，每秒智力+0.2，魔法伤害+8%。',
    },
  }),
  node({
    id = 'bond_growth_intelligence_grant',
    display_name = '赋予智力',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 2,
    parent_id = 'bond_growth_intelligence',
    next_ids = { 'bond_growth_intelligence_growth' },
    route_tags = {},
    template = 'static_attr',
    icon = 106912,
    editor_skill_id = 201385543,
    attr = { ['智力'] = 100 },
    desc = {
      single = '赋予智力：智力+100。',
      advanced = '杀敌智力+0.1，每秒智力+0.2，魔法伤害+8%。',
    },
  }),
  node({
    id = 'bond_growth_intelligence_growth',
    display_name = '智力成长',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 2,
    parent_id = 'bond_growth_intelligence_grant',
    next_ids = { 'bond_growth_intelligence_amp' },
    route_tags = {},
    template = 'static_attr',
    icon = 106912,
    editor_skill_id = 201385543,
    runtime = { intelligence_per_second = 0.3 },
    desc = {
      single = '智力成长：每秒智力+0.3。',
      advanced = '杀敌智力+0.1，每秒智力+0.2，魔法伤害+8%。',
    },
  }),
  node({
    id = 'bond_growth_intelligence_amp',
    display_name = '智力增幅',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 2,
    parent_id = 'bond_growth_intelligence_growth',
    next_ids = { 'bond_growth_archmage' },
    route_tags = {},
    template = 'static_attr',
    icon = 106912,
    editor_skill_id = 201385543,
    attr = { ['智力增幅'] = 5 },
    desc = {
      single = '智力增幅：智力增幅+5%。',
      advanced = '我要玩智力！卡池中加入智力相关的基础卡牌。',
    },
  }),
  node({
    id = 'bond_growth_archmage',
    display_name = '秘法师',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 2,
    parent_id = 'bond_growth_intelligence_amp',
    next_ids = { 'bond_growth_archmage_sage' },
    route_tags = {},
    template = 'per_second_growth',
    icon = 106905,
    editor_skill_id = 201385544,
    attr = {
      ['智力'] = 50,
    },
    runtime = { spell_damage_bonus = 0.08 },
    desc = {
      single = '天智：技能伤害+8%，智力+50。',
      advanced = '当局每进化1次，就会使智力增幅+2%，每秒智力+0.2，魔法伤害+3%。',
    },
  }),
  node({
    id = 'bond_growth_archmage_sage',
    display_name = '贤者',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 2,
    parent_id = 'bond_growth_archmage',
    next_ids = { 'bond_growth_archmage_quick_cast' },
    route_tags = {},
    template = 'per_second_growth',
    icon = 106905,
    editor_skill_id = 201385544,
    attr = {
      ['智力'] = 150,
    },
    runtime = {
      intelligence_per_second = 0.3,
    },
    desc = {
      single = '贤者：智力+150，每秒智力+0.3。',
      advanced = '当局每进化1次，就会使智力增幅+2%，每秒智力+0.2，魔法伤害+3%。',
    },
  }),
  node({
    id = 'bond_growth_archmage_quick_cast',
    display_name = '快速施法',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 2,
    parent_id = 'bond_growth_archmage_sage',
    next_ids = { 'bond_growth_archmage_burst' },
    route_tags = {},
    template = 'per_second_growth',
    icon = 106905,
    editor_skill_id = 201385544,
    attr = {
      ['技能急速'] = 15,
    },
    desc = {
      single = '快速施法：技能急速+15。',
      advanced = '当局每进化1次，就会使智力增幅+2%，每秒智力+0.2，魔法伤害+3%。',
    },
  }),
  node({
    id = 'bond_growth_archmage_burst',
    display_name = '魔能爆发',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 2,
    parent_id = 'bond_growth_archmage_quick_cast',
    next_ids = { 'bond_growth_spell_god' },
    route_tags = { 'growth', 'skill' },
    template = 'per_second_growth',
    icon = 106905,
    editor_skill_id = 201385544,
    attr = {
      ['魔法暴击'] = 3,
    },
    runtime = {
      intelligence_per_second = 0.2,
      spell_damage_bonus = 0.03,
    },
    desc = {
      single = '魔能爆发：魔法暴击+3%，魔法暴伤+9%。',
      advanced = '当局每进化1次，就会使智力增幅+2%，每秒智力+0.2，魔法伤害+3%。',
    },
  }),
  node({
    id = 'bond_growth_spell_god',
    display_name = '法神',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 3,
    parent_id = 'bond_growth_archmage_burst',
    next_ids = { 'bond_growth_spell_god_mana' },
    route_tags = {},
    template = 'per_second_growth',
    quality = 'epic',
    icon = 106916,
    editor_skill_id = 201385545,
    attr = {
      ['智力'] = 100,
    },
    desc = {
      single = '掌控之力：智力+100，每拥有一个初始技能，智力增幅+4%。',
      advanced = '最终智力+5%，每点智力额外提供0.1攻击力。',
    },
  }),
  node({
    id = 'bond_growth_spell_god_mana',
    display_name = '旷世法力',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 3,
    parent_id = 'bond_growth_spell_god',
    next_ids = { 'bond_growth_spell_god_element' },
    route_tags = {},
    template = 'per_second_growth',
    quality = 'epic',
    icon = 106916,
    editor_skill_id = 201385545,
    attr = {
      ['智力'] = 200,
    },
    desc = {
      single = '旷世法力：智力+200。',
      advanced = '最终智力+5%，每点智力额外提供0.1攻击力。',
    },
  }),
  node({
    id = 'bond_growth_spell_god_element',
    display_name = '元素之力',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 3,
    parent_id = 'bond_growth_spell_god_mana',
    next_ids = {},
    route_tags = { 'growth', 'skill' },
    template = 'per_second_growth',
    quality = 'epic',
    icon = 106916,
    editor_skill_id = 201385545,
    runtime = {
      intelligence_per_second = 0.4,
      spell_damage_bonus = 0.15,
    },
    desc = {
      single = '元素之力：全系伤害+15%。',
      advanced = '最终智力+5%，每点智力额外提供0.1攻击力。',
    },
  }),
  node({
    id = 'bond_critical_deadly',
    display_name = '致命',
    group_id = 'critical',
    line_id = 'line_critical_core',
    tier = 2,
    parent_id = 'bond_critical_core_damage',
    next_ids = { 'bond_critical_deadly_magic' },
    route_tags = {},
    template = 'basic_attack_modifier',
    icon = 106810,
    editor_skill_id = 201385546,
    attr = {
      ['物理暴击'] = 3,
    },
    desc = {
      single = '暴击转化-物：物理暴击+3%，每溢出1%物理暴击，转化为2%物理暴伤。',
      advanced = '造成的所有非暴击伤害降低20%，所有暴击伤害提高20%。',
    },
  }),
  node({
    id = 'bond_critical_deadly_magic',
    display_name = '暴击转化-魔',
    group_id = 'critical',
    line_id = 'line_critical_core',
    tier = 2,
    parent_id = 'bond_critical_deadly',
    next_ids = { 'bond_critical_cannon' },
    route_tags = { 'burst' },
    template = 'basic_attack_modifier',
    icon = 106810,
    editor_skill_id = 201385546,
    attr = {
      ['魔法暴击'] = 3,
    },
    runtime = { critical_damage_bonus = 0.20 },
    desc = {
      single = '暴击转化-魔：魔法暴击+3%，每溢出1%魔法暴击，转化为2%魔法暴伤。',
      advanced = '造成的所有非暴击伤害降低20%，所有暴击伤害提高20%。',
    },
  }),
  node({
    id = 'bond_critical_cannon',
    display_name = '大炮',
    group_id = 'critical',
    line_id = 'line_critical_core',
    tier = 3,
    parent_id = 'bond_critical_deadly_magic',
    next_ids = { 'bond_critical_cannon_attack' },
    route_tags = {},
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 106686,
    editor_skill_id = 201385547,
    attr = {
      ['魔法暴击'] = 5,
    },
    desc = {
      single = '致命魔法：魔法暴击+5%，造成的魔法暴击伤害有20%的概率在原有的基础上翻倍。',
      advanced = '每溢出2%的物理暴击，致命攻击的触发概率提升1%；每溢出2%的魔法暴击，致命魔法的触发概率提升1%。',
    },
  }),
  node({
    id = 'bond_critical_cannon_attack',
    display_name = '致命攻击',
    group_id = 'critical',
    line_id = 'line_critical_core',
    tier = 3,
    parent_id = 'bond_critical_cannon',
    next_ids = {},
    route_tags = { 'burst', 'boss' },
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 106686,
    editor_skill_id = 201385547,
    attr = {
      ['物理暴击'] = 5,
    },
    runtime = { critical_damage_bonus = 0.40 },
    desc = {
      single = '致命攻击：物理暴击+5%，造成的物理暴击伤害有20%的概率在原有的基础上翻倍。',
      advanced = '每溢出2%的物理暴击，致命攻击的触发概率提升1%；每溢出2%的魔法暴击，致命魔法的触发概率提升1%。',
    },
  }),
  node({
    id = 'bond_archery_barrage',
    display_name = '广射',
    group_id = 'archery',
    line_id = 'line_archery_barrage',
    tier = 2,
    parent_id = 'bond_archery_core_stance',
    next_ids = { 'bond_archery_barrage_moon_blade' },
    route_tags = { 'clear' },
    template = 'basic_attack_modifier',
    icon = 106785,
    editor_skill_id = 201385548,
    attr = { ['攻击范围'] = 150 },
    runtime = { normal_attack_damage_bonus = 0.08 },
    desc = {
      single = '射击威力：物理伤害+8%。',
      advanced = '每有100攻击范围就会提高1%的普攻伤害。',
    },
  }),
  node({
    id = 'bond_archery_barrage_moon_blade',
    display_name = '超远射击',
    group_id = 'archery',
    line_id = 'line_archery_barrage',
    tier = 2,
    parent_id = 'bond_archery_barrage',
    next_ids = { 'bond_archery_moon_blade' },
    route_tags = {},
    template = 'basic_attack_modifier',
    icon = 106785,
    editor_skill_id = 201385548,
    desc = {
      single = '超远射击：攻击范围+150。',
      advanced = '每有100攻击范围就会提高1%的普攻伤害。',
    },
  }),
  node({
    id = 'bond_archery_moon_blade',
    display_name = '月刃',
    group_id = 'archery',
    line_id = 'line_archery_barrage',
    tier = 2,
    parent_id = 'bond_archery_barrage_moon_blade',
    next_ids = { 'bond_archery_moon_blessing' },
    route_tags = {},
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 108246,
    editor_skill_id = 201385549,
    desc = {
      single = '弹射之刃：弹射次数+1。',
      advanced = '立即获得当前弹射次数*50的敏捷，弹射伤害超过100%时，每溢出1%转化为1%的普攻伤害。',
    },
  }),
  node({
    id = 'bond_archery_moon_blessing',
    display_name = '月之祝福',
    group_id = 'archery',
    line_id = 'line_archery_barrage',
    tier = 2,
    parent_id = 'bond_archery_moon_blade',
    next_ids = {},
    route_tags = { 'clear' },
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 108246,
    editor_skill_id = 201385549,
    runtime = { bounce_count_bonus = 1 },
    desc = {
      single = '月之祝福：弹射伤害+15%。',
      advanced = '立即获得当前弹射次数*50的敏捷，弹射伤害超过100%时，每溢出1%转化为1%的普攻伤害。',
    },
  }),
  node({
    id = 'bond_archery_rapid',
    display_name = '速攻',
    group_id = 'archery',
    line_id = 'line_archery_rapid',
    tier = 2,
    parent_id = 'bond_archery_core_stance',
    next_ids = { 'bond_archery_rapid_swiftness' },
    route_tags = {},
    template = 'static_attr',
    icon = 106700,
    editor_skill_id = 201385550,
    attr = { ['攻击速度'] = 30 },
    desc = {
      single = '疾风：攻击间隔-0.1。',
      advanced = '攻击有20%的概率提升100%攻速，持续5秒。',
    },
  }),
  node({
    id = 'bond_archery_rapid_swiftness',
    display_name = '迅捷',
    group_id = 'archery',
    line_id = 'line_archery_rapid',
    tier = 2,
    parent_id = 'bond_archery_rapid',
    next_ids = { 'bond_archery_rapid_agile' },
    route_tags = {},
    template = 'static_attr',
    icon = 106700,
    editor_skill_id = 201385550,
    desc = {
      single = '迅捷：攻速+30%。',
      advanced = '攻击有20%的概率提升100%攻速，持续5秒。',
    },
  }),
  node({
    id = 'bond_archery_rapid_agile',
    display_name = '灵敏',
    group_id = 'archery',
    line_id = 'line_archery_rapid',
    tier = 2,
    parent_id = 'bond_archery_rapid_swiftness',
    next_ids = {},
    route_tags = { 'tempo', 'auto_rapid_overdrive' },
    template = 'static_attr',
    icon = 106700,
    editor_skill_id = 201385550,
    desc = {
      single = '灵敏：敏捷+111。',
      advanced = '攻击有20%的概率提升100%攻速，持续5秒。',
    },
  }),
  node({
    id = 'bond_archery_shooting',
    display_name = '射术',
    group_id = 'archery',
    line_id = 'line_archery_shooting',
    tier = 2,
    parent_id = 'bond_archery_core_stance',
    next_ids = { 'bond_archery_shooting_edge' },
    route_tags = {},
    template = 'basic_attack_modifier',
    icon = 107004,
    editor_skill_id = 201385551,
    attr = {
      ['攻击'] = 50,
      ['敏捷'] = 50,
    },
    desc = {
      single = '穿云重弩：每2多重数量，穿云箭数量+1。',
      advanced = '穿云箭所需的攻击次数降低5次。',
    },
  }),
  node({
    id = 'bond_archery_shooting_edge',
    display_name = '穿云箭锋',
    group_id = 'archery',
    line_id = 'line_archery_shooting',
    tier = 2,
    parent_id = 'bond_archery_shooting',
    next_ids = { 'bond_archery_multishot' },
    route_tags = { 'clear', 'tempo' },
    template = 'basic_attack_modifier',
    icon = 107004,
    editor_skill_id = 201385551,
    runtime = { normal_attack_damage_bonus = 0.05 },
    desc = {
      single = '穿云箭锋：每1弹射次数，穿云箭伤害+50%。',
      advanced = '穿云箭所需的攻击次数降低5次。',
    },
  }),
  node({
    id = 'bond_archery_multishot',
    display_name = '多重箭',
    group_id = 'archery',
    line_id = 'line_archery_shooting',
    tier = 2,
    parent_id = 'bond_archery_shooting',
    next_ids = { 'bond_archery_multishot_volley' },
    route_tags = {},
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 106787,
    editor_skill_id = 201385552,
    desc = {
      single = '多重威力：多重伤害+15%。',
      advanced = '立即获得当前多重数量*50的敏捷，多重伤害超过100%时，每溢出1%转化为1%的普攻伤害。',
    },
  }),
  node({
    id = 'bond_archery_multishot_volley',
    display_name = '多重齐发',
    group_id = 'archery',
    line_id = 'line_archery_shooting',
    tier = 2,
    parent_id = 'bond_archery_multishot',
    next_ids = {},
    route_tags = { 'clear' },
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 106787,
    editor_skill_id = 201385552,
    runtime = { multishot_bonus = 1 },
    desc = {
      single = '多重齐发：多重数量+1。',
      advanced = '立即获得当前多重数量*50的敏捷，多重伤害超过100%时，每溢出1%转化为1%的普攻伤害。',
    },
  }),
  node({
    id = 'bond_magic_mage',
    display_name = '魔法师',
    group_id = 'magic',
    line_id = 'line_magic_mage',
    tier = 2,
    parent_id = 'bond_magic_haste_charge',
    next_ids = { 'bond_magic_mage_flame' },
    route_tags = {},
    template = 'per_second_growth',
    icon = 107016,
    editor_skill_id = 201385553,
    attr = {
      ['攻击'] = 50,
      ['智力'] = 50,
    },
    desc = {
      single = '奥术魔法：智力+75，能量伤害+10%。',
      advanced = '魔法互通：造成能量、火系、冰系伤害时，当前伤害类型会受到另外2种15%的伤害增幅的加成。',
    },
  }),
  node({
    id = 'bond_magic_mage_flame',
    display_name = '火焰魔法',
    group_id = 'magic',
    line_id = 'line_magic_mage',
    tier = 2,
    parent_id = 'bond_magic_mage',
    next_ids = { 'bond_magic_mage_frost' },
    route_tags = {},
    template = 'per_second_growth',
    icon = 107016,
    editor_skill_id = 201385553,
    desc = {
      single = '火焰魔法：智力+75，火系伤害+10%。',
      advanced = '魔法互通：造成能量、火系、冰系伤害时，当前伤害类型会受到另外2种15%的伤害增幅的加成。',
    },
  }),
  node({
    id = 'bond_magic_mage_frost',
    display_name = '寒冰魔法',
    group_id = 'magic',
    line_id = 'line_magic_mage',
    tier = 2,
    parent_id = 'bond_magic_mage_flame',
    next_ids = {},
    route_tags = { 'skill', 'resonance' },
    template = 'per_second_growth',
    icon = 107016,
    editor_skill_id = 201385553,
    runtime = { spell_damage_bonus = 0.075 },
    desc = {
      single = '寒冰魔法：智力+75，冰系伤害+10%。',
      advanced = '魔法互通：造成能量、火系、冰系伤害时，当前伤害类型会受到另外2种15%的伤害增幅的加成。',
    },
  }),
  node({
    id = 'bond_magic_arcane_power',
    display_name = '魔能',
    group_id = 'magic',
    line_id = 'line_magic_arcane_power',
    tier = 2,
    parent_id = 'bond_magic_core_essence',
    next_ids = { 'bond_magic_arcane_power_staff' },
    route_tags = {},
    template = 'static_attr',
    icon = 107049,
    editor_skill_id = 201385554,
    attr = { ['技能急速'] = 10 },
    desc = {
      single = '魔法外衣：全属性+30，技能急速+5。',
      advanced = '技能急速+10，当冷却缩减超过上限时，每溢出2点技能急速就会提升1%的技能伤害。',
    },
  }),
  node({
    id = 'bond_magic_arcane_power_staff',
    display_name = '魔法权杖',
    group_id = 'magic',
    line_id = 'line_magic_arcane_power',
    tier = 2,
    parent_id = 'bond_magic_arcane_power',
    next_ids = {},
    route_tags = { 'skill', 'spell_cycle' },
    template = 'static_attr',
    icon = 107049,
    editor_skill_id = 201385554,
    desc = {
      single = '魔法权杖：攻击力+50，技能伤害+4%。',
      advanced = '技能急速+10，当冷却缩减超过上限时，每溢出2点技能急速就会提升1%的技能伤害。',
    },
  }),
  node({
    id = 'bond_magic_trick',
    display_name = '魔术',
    group_id = 'magic',
    line_id = 'line_magic_trick',
    tier = 2,
    parent_id = 'bond_magic_core_essence',
    next_ids = { 'bond_magic_trick_mastery' },
    route_tags = {},
    template = 'basic_attack_modifier',
    icon = 107051,
    editor_skill_id = 201385555,
    desc = {
      single = '魔爆能量：魔爆术冷却时间-5秒。',
      advanced = '技能栏每拥有一个初始技能，魔爆术触发次数+1。',
    },
  }),
  node({
    id = 'bond_magic_trick_mastery',
    display_name = '魔爆掌握',
    group_id = 'magic',
    line_id = 'line_magic_trick',
    tier = 2,
    parent_id = 'bond_magic_trick',
    next_ids = {},
    route_tags = { 'skill', 'tempo', 'auto_spell_burst_amp' },
    template = 'basic_attack_modifier',
    icon = 107051,
    editor_skill_id = 201385555,
    runtime = { skill_echo_chance = 0.10 },
    desc = {
      single = '魔爆掌握：魔爆术范围+150。',
      advanced = '技能栏每拥有一个初始技能，魔爆术触发次数+1。',
    },
  }),
  node({
    id = 'bond_magic_haste',
    display_name = '急速',
    group_id = 'magic',
    line_id = 'line_magic_haste',
    tier = 2,
    parent_id = 'bond_magic_core_essence',
    next_ids = { 'bond_magic_haste_cooldown' },
    route_tags = {},
    template = 'static_attr',
    icon = 106857,
    editor_skill_id = 201385556,
    attr = {
      ['技能急速'] = 10,
      ['智力'] = 111,
    },
    desc = {
      single = '灵智：智力+111。',
      advanced = '任意技能进入冷却时，有7%的概率立即重置该技能冷却。',
    },
  }),
  node({
    id = 'bond_magic_haste_cooldown',
    display_name = '冷缩',
    group_id = 'magic',
    line_id = 'line_magic_haste',
    tier = 2,
    parent_id = 'bond_magic_haste',
    next_ids = { 'bond_magic_haste_charge' },
    route_tags = {},
    template = 'static_attr',
    icon = 106857,
    editor_skill_id = 201385556,
    desc = {
      single = '冷缩：技能急速+10。',
      advanced = '任意技能进入冷却时，有7%的概率立即重置该技能冷却。',
    },
  }),
  node({
    id = 'bond_magic_haste_charge',
    display_name = '充能',
    group_id = 'magic',
    line_id = 'line_magic_haste',
    tier = 2,
    parent_id = 'bond_magic_haste_cooldown',
    next_ids = { 'bond_magic_elementalist', 'bond_magic_mage' },
    route_tags = { 'skill', 'tempo', 'auto_haste_reset' },
    template = 'static_attr',
    icon = 106857,
    editor_skill_id = 201385556,
    desc = {
      single = '充能：魔法伤害+5%，技能急速+5。',
      advanced = '任意技能进入冷却时，有7%的概率立即重置该技能冷却。',
    },
  }),
  node({
    id = 'bond_magic_elementalist',
    display_name = '元素师',
    group_id = 'magic',
    line_id = 'line_magic_elementalist',
    tier = 2,
    parent_id = 'bond_magic_haste_charge',
    next_ids = { 'bond_magic_elementalist_storm' },
    route_tags = {},
    template = 'per_second_growth',
    icon = 106858,
    editor_skill_id = 201385557,
    desc = {
      single = '大地元素：魔法伤害+5%，物系伤害+10%。',
      advanced = '元素相融：造成物系、电系、风系伤害时，当前伤害类型会受到另外2种15%的伤害增幅的加成。',
    },
  }),
  node({
    id = 'bond_magic_elementalist_storm',
    display_name = '风暴元素',
    group_id = 'magic',
    line_id = 'line_magic_elementalist',
    tier = 2,
    parent_id = 'bond_magic_elementalist',
    next_ids = { 'bond_magic_elementalist_lightning' },
    route_tags = {},
    template = 'per_second_growth',
    icon = 106858,
    editor_skill_id = 201385557,
    desc = {
      single = '风暴元素：魔法伤害+5%，风系伤害+10%。',
      advanced = '元素相融：造成物系、电系、风系伤害时，当前伤害类型会受到另外2种15%的伤害增幅的加成。',
    },
  }),
  node({
    id = 'bond_magic_elementalist_lightning',
    display_name = '闪电元素',
    group_id = 'magic',
    line_id = 'line_magic_elementalist',
    tier = 2,
    parent_id = 'bond_magic_elementalist_storm',
    next_ids = {},
    route_tags = { 'skill', 'element', 'burn', 'cold_tide', 'shock' },
    template = 'per_second_growth',
    icon = 106858,
    editor_skill_id = 201385557,
    runtime = { elemental_damage_bonus = 0.15 },
    desc = {
      single = '闪电元素：魔法伤害+5%，电系伤害+10%。',
      advanced = '元素相融：造成物系、电系、风系伤害时，当前伤害类型会受到另外2种15%的伤害增幅的加成。',
    },
  }),
  node({
    id = 'bond_economy_greed',
    display_name = '贪婪',
    group_id = 'economy',
    line_id = 'line_economy_greed',
    tier = 2,
    parent_id = 'bond_economy_core_reward',
    next_ids = { 'bond_economy_greed_coin' },
    route_tags = {},
    template = 'kill_stack',
    icon = 106694,
    editor_skill_id = 201385558,
    desc = {
      single = '贪婪之刃：杀敌数+888。',
      advanced = '贪婪吞噬：随机吞噬4张可吞噬卡牌。卡牌除外：该卡牌放弃后直接除外，不会返回卡池。',
    },
  }),
  node({
    id = 'bond_economy_greed_coin',
    display_name = '贪欲金币',
    group_id = 'economy',
    line_id = 'line_economy_greed',
    tier = 2,
    parent_id = 'bond_economy_greed',
    next_ids = { 'bond_economy_greed_key' },
    route_tags = {},
    template = 'kill_stack',
    icon = 106694,
    editor_skill_id = 201385558,
    unlock_rewards = { gold = 6000 },
    desc = {
      single = '贪欲金币：金币+6000。',
      advanced = '贪婪吞噬：随机吞噬4张可吞噬卡牌。卡牌除外：该卡牌放弃后直接除外，不会返回卡池。',
    },
  }),
  node({
    id = 'bond_economy_greed_key',
    display_name = '贪欲钥匙',
    group_id = 'economy',
    line_id = 'line_economy_greed',
    tier = 2,
    parent_id = 'bond_economy_greed_coin',
    next_ids = {},
    route_tags = { 'economy', 'growth' },
    template = 'kill_stack',
    icon = 106694,
    editor_skill_id = 201385558,
    unlock_rewards = { wood = 150 },
    runtime = { kill_gold_ratio = 0.20 },
    desc = {
      single = '贪欲钥匙：木材+150。',
      advanced = '贪婪吞噬：随机吞噬4张可吞噬卡牌。卡牌除外：该卡牌放弃后直接除外，不会返回卡池。',
    },
  }),
  node({
    id = 'bond_economy_challenge',
    display_name = '挑战',
    group_id = 'economy',
    line_id = 'line_economy_challenge',
    tier = 2,
    parent_id = 'bond_economy_core_reward',
    next_ids = { 'bond_economy_challenge_exp_hunter' },
    route_tags = {},
    template = 'kill_stack',
    icon = 107382,
    editor_skill_id = 201385559,
    desc = {
      single = '木材猎人：木材挑战怪物数量+1。',
      advanced = '挑战伤害+15%，所有挑战冷却时间减少。',
    },
  }),
  node({
    id = 'bond_economy_challenge_exp_hunter',
    display_name = '经验猎人',
    group_id = 'economy',
    line_id = 'line_economy_challenge',
    tier = 2,
    parent_id = 'bond_economy_challenge',
    next_ids = { 'bond_economy_challenge_gold_hunter' },
    route_tags = {},
    template = 'kill_stack',
    icon = 107382,
    editor_skill_id = 201385559,
    desc = {
      single = '经验猎人：经验挑战怪物数量+1。',
      advanced = '挑战伤害+15%，所有挑战冷却时间减少。',
    },
  }),
  node({
    id = 'bond_economy_challenge_gold_hunter',
    display_name = '金币猎人',
    group_id = 'economy',
    line_id = 'line_economy_challenge',
    tier = 2,
    parent_id = 'bond_economy_challenge_exp_hunter',
    next_ids = {},
    route_tags = { 'economy', 'boss' },
    template = 'kill_stack',
    icon = 107382,
    editor_skill_id = 201385559,
    runtime = { kill_reward_ratio = 0.10 },
    desc = {
      single = '金币猎人：金币挑战怪物数量+1。',
      advanced = '挑战伤害+15%，所有挑战冷却时间减少。',
    },
  }),
  node({
    id = 'bond_body_life',
    display_name = '生命',
    group_id = 'body',
    line_id = 'line_body_life',
    tier = 2,
    parent_id = 'bond_body_core_vitality',
    next_ids = { 'bond_body_life_blessing' },
    route_tags = {},
    template = 'static_attr',
    icon = 107362,
    editor_skill_id = 201385560,
    attr = {
      ['生命恢复'] = 2,
    },
    desc = {
      single = '回春：生命恢复+2。',
      advanced = '生命增幅+5%，护甲+5。',
    },
  }),
  node({
    id = 'bond_body_life_blessing',
    display_name = '生命祝福',
    group_id = 'body',
    line_id = 'line_body_life',
    tier = 2,
    parent_id = 'bond_body_life',
    next_ids = { 'bond_body_life_power' },
    route_tags = {},
    template = 'static_attr',
    icon = 107362,
    editor_skill_id = 201385560,
    attr = {
      ['生命'] = 200,
    },
    desc = {
      single = '生命祝福：生命值+200。',
      advanced = '生命增幅+5%，护甲+5。',
    },
  }),
  node({
    id = 'bond_body_life_power',
    display_name = '生命之力',
    group_id = 'body',
    line_id = 'line_body_life',
    tier = 2,
    parent_id = 'bond_body_life_blessing',
    next_ids = {},
    route_tags = { 'survival', 'blessing' },
    template = 'static_attr',
    icon = 107362,
    editor_skill_id = 201385560,
    attr = {
      ['生命增幅'] = 5,
      ['护甲'] = 5,
    },
    desc = {
      single = '生命之力：生命增幅+5%。',
      advanced = '生命增幅+5%，护甲+5。',
    },
  }),
  node({
    id = 'bond_body_blood_oath',
    display_name = '血誓',
    group_id = 'body',
    line_id = 'line_body_blood_oath',
    tier = 2,
    parent_id = 'bond_body_core_vitality',
    next_ids = { 'bond_body_blood_oath_blade' },
    route_tags = {},
    template = 'kill_stack',
    quality = 'epic',
    icon = 106542,
    editor_skill_id = 201385561,
    desc = {
      single = '血契：每有100点生命上限智力+3。',
      advanced = '生命值+500，血刃、血契、血矛效果翻倍。',
    },
  }),
  node({
    id = 'bond_body_blood_oath_blade',
    display_name = '血刃',
    group_id = 'body',
    line_id = 'line_body_blood_oath',
    tier = 2,
    parent_id = 'bond_body_blood_oath',
    next_ids = { 'bond_body_blood_oath_spear' },
    route_tags = {},
    template = 'kill_stack',
    quality = 'epic',
    icon = 106542,
    editor_skill_id = 201385561,
    desc = {
      single = '血刃：每有100点生命上限攻击力+3。',
      advanced = '生命值+500，血刃、血契、血矛效果翻倍。',
    },
  }),
  node({
    id = 'bond_body_blood_oath_spear',
    display_name = '血矛',
    group_id = 'body',
    line_id = 'line_body_blood_oath',
    tier = 2,
    parent_id = 'bond_body_blood_oath_blade',
    next_ids = {},
    route_tags = { 'blood_pact', 'survival' },
    template = 'kill_stack',
    quality = 'epic',
    icon = 106542,
    editor_skill_id = 201385561,
    attr = { ['生命'] = 500 },
    desc = {
      single = '血矛：每有100点生命上限敏捷+3。',
      advanced = '生命值+500，血刃、血契、血矛效果翻倍。',
    },
  }),
  node({
    id = 'bond_body_blood_demon',
    display_name = '血魔',
    group_id = 'body',
    line_id = 'line_body_blood_demon',
    tier = 3,
    parent_id = 'bond_body_core_vitality',
    next_ids = { 'bond_body_blood_demon_satan' },
    route_tags = {},
    template = 'kill_stack',
    quality = 'epic',
    icon = 106720,
    editor_skill_id = 201385562,
    desc = {
      single = '魔手：杀敌生命+0.4，杀敌恢复+5，攻击附加30%生命值的自适应。',
      advanced = '每损失35%最大生命值，就会触发一次回荡，对周围750范围内敌人造成500%生命值无视闪避的自适应伤害，击退敌人500距离，并附加3秒眩晕。',
    },
  }),
  node({
    id = 'bond_body_blood_demon_satan',
    display_name = '撒旦',
    group_id = 'body',
    line_id = 'line_body_blood_demon',
    tier = 3,
    parent_id = 'bond_body_blood_demon',
    next_ids = { 'bond_body_blood_demon_armlet' },
    route_tags = {},
    template = 'kill_stack',
    quality = 'epic',
    icon = 106720,
    editor_skill_id = 201385562,
    attr = {
      ['攻击'] = 100,
      ['力量'] = 100,
    },
    desc = {
      single = '撒旦：攻击力+100，力量+100，每损失1%的最大生命值，就会使所有伤害+0.5%。',
      advanced = '每损失35%最大生命值，就会触发一次回荡，对周围750范围内敌人造成500%生命值无视闪避的自适应伤害，击退敌人500距离，并附加3秒眩晕。',
    },
  }),
  node({
    id = 'bond_body_blood_demon_armlet',
    display_name = '臂章',
    group_id = 'body',
    line_id = 'line_body_blood_demon',
    tier = 3,
    parent_id = 'bond_body_blood_demon_satan',
    next_ids = {},
    route_tags = { 'berserk', 'burst', 'survival', 'auto_blood_demon_burst' },
    template = 'kill_stack',
    quality = 'epic',
    icon = 106720,
    editor_skill_id = 201385562,
    runtime = { low_hp_damage_bonus = 0.20 },
    desc = {
      single = '臂章：攻击力+100，护甲+10，生命值高于50%时自动开启，每秒损失2%最大生命值；生命值低于30%时自动关闭。',
      advanced = '每损失35%最大生命值，就会触发一次回荡，对周围750范围内敌人造成500%生命值无视闪避的自适应伤害，击退敌人500距离，并附加3秒眩晕。',
    },
  }),
  node({
    id = 'bond_body_tactics',
    display_name = '战术',
    group_id = 'body',
    line_id = 'line_body_tactics',
    tier = 2,
    parent_id = 'bond_body_core_vitality',
    next_ids = { 'bond_body_tactics_blunt_edge' },
    route_tags = {},
    template = 'static_attr',
    icon = 106761,
    editor_skill_id = 201385563,
    desc = {
      single = '破甲：斗气场域影响范围内敌人护甲-10%。',
      advanced = '斗气场域额外附加 30% 生命伤害，每击杀 1 敌力量 +0.5。',
    },
  }),
  node({
    id = 'bond_body_tactics_blunt_edge',
    display_name = '挫锋',
    group_id = 'body',
    line_id = 'line_body_tactics',
    tier = 2,
    parent_id = 'bond_body_tactics',
    next_ids = {},
    route_tags = { 'armor_break' },
    template = 'static_attr',
    icon = 106761,
    editor_skill_id = 201385563,
    runtime = { all_damage_bonus = 0.04 },
    desc = {
      single = '挫锋：斗气场域影响范围内敌人攻击力-30%。',
      advanced = '斗气场域额外附加 30% 生命伤害，每击杀 1 敌力量 +0.5。',
    },
  }),
  node({
    id = 'bond_body_fortress',
    display_name = '固守',
    group_id = 'body',
    line_id = 'line_body_fortress',
    tier = 2,
    parent_id = 'bond_body_core_vitality',
    next_ids = { 'bond_body_fortress_hard_armor' },
    route_tags = { 'survival' },
    template = 'static_attr',
    icon = 106869,
    editor_skill_id = 201385564,
    attr = {
      ['生命'] = 100,
      ['护甲'] = 5,
      ['格挡'] = 5,
    },
    desc = {
      single = '坚盾：生命值+100，格挡+5。',
      advanced = '护甲增幅+10%，受到的单次伤害不会超过最大生命值的35%。',
    },
  }),
  node({
    id = 'bond_body_fortress_hard_armor',
    display_name = '硬甲',
    group_id = 'body',
    line_id = 'line_body_fortress',
    tier = 2,
    parent_id = 'bond_body_fortress',
    next_ids = {},
    route_tags = { 'survival' },
    template = 'static_attr',
    icon = 106869,
    editor_skill_id = 201385564,
    desc = {
      single = '硬甲：生命值+100，护甲+5。',
      advanced = '护甲增幅+10%，受到的单次伤害不会超过最大生命值的35%。',
    },
  }),
  node({
    id = 'bond_body_charge_breaker',
    display_name = '陷阵',
    group_id = 'body',
    line_id = 'line_body_charge_breaker',
    tier = 2,
    parent_id = 'bond_body_core_vitality',
    next_ids = { 'bond_body_charge_breaker_bloody_battle' },
    route_tags = {},
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 106989,
    editor_skill_id = 201385565,
    desc = {
      single = '奋力抵抗：护甲+5，格挡+5，每击杀100名敌人提高1%的所有伤害，最高25%。',
      advanced = '每击杀200名敌人触发，全属性增幅+20%，攻速+50%，技能急速+30，持续10秒。',
    },
  }),
  node({
    id = 'bond_body_charge_breaker_bloody_battle',
    display_name = '浴血拼杀',
    group_id = 'body',
    line_id = 'line_body_charge_breaker',
    tier = 2,
    parent_id = 'bond_body_charge_breaker',
    next_ids = {},
    route_tags = { 'boss', 'armor_break', 'auto_charge_breaker_rally' },
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 106989,
    editor_skill_id = 201385565,
    runtime = {
      elite_damage_bonus = 0.20,
      boss_damage_bonus = 0.20,
    },
    desc = {
      single = '浴血拼杀：杀敌恢复+5。',
      advanced = '每击杀200名敌人触发，全属性增幅+20%，攻速+50%，技能急速+30，持续10秒。',
    },
  }),
}

local by_id = {}
local root_ids = {}
local by_line = {}
local by_group = {}

for _, def in ipairs(list) do
  assert(not by_id[def.id], string.format('duplicate bond node id: %s', def.id))
  by_id[def.id] = def
  by_line[def.line_id] = by_line[def.line_id] or {}
  by_line[def.line_id][#by_line[def.line_id] + 1] = def
  by_group[def.group_id] = by_group[def.group_id] or {}
  by_group[def.group_id][#by_group[def.group_id] + 1] = def
  if not def.parent_id then
    root_ids[#root_ids + 1] = def.id
  end
end

for _, def in ipairs(list) do
  if def.parent_id then
    assert(by_id[def.parent_id], string.format('missing parent_id for bond node: %s -> %s', def.id, def.parent_id))
  end
  for _, next_id in ipairs(def.next_ids) do
    assert(by_id[next_id], string.format('missing next_id for bond node: %s -> %s', def.id, next_id))
  end
end

return {
  list = list,
  by_id = by_id,
  root_ids = root_ids,
  by_line = by_line,
  by_group = by_group,
}
