local function node(def)
  def.quality = def.quality or 'rare'
  def.editor_skill_id = def.editor_skill_id or nil
  def.icon = def.icon or nil
  def.attr = def.attr or {}
  def.runtime = def.runtime or {}
  def.desc = def.desc or {}
  def.route_tags = def.route_tags or {}
  def.next_ids = def.next_ids or {}
  def.unlock_rewards = def.unlock_rewards or {}
  return def
end

local list = {
  node({
    id = 'bond_body_core',
    display_name = '体术',
    group_id = 'body',
    line_id = 'line_body_core',
    tier = 1,
    parent_id = nil,
    next_ids = { 'bond_body_life', 'bond_body_tactics', 'bond_body_fortress' },
    route_tags = { 'auto_fighting_spirit' },
    template = 'static_attr',
    icon = 107362,
    editor_skill_id = 201385560,
    desc = {
      single = '斗气场域：每秒对 1200 范围敌人造成 60% 力量自适应伤害。',
      advanced = '后继：生命 / 战术 / 固守。',
    },
  }),
  node({
    id = 'bond_economy_core',
    display_name = '经济',
    group_id = 'economy',
    line_id = 'line_economy_core',
    tier = 1,
    parent_id = nil,
    next_ids = { 'bond_economy_greed', 'bond_economy_challenge' },
    route_tags = { 'economy' },
    template = 'kill_stack',
    icon = 106694,
    editor_skill_id = 201385558,
    runtime = {
      wood_per_sec_bonus = 0.4,
      gold_per_sec_bonus = 10,
    },
    desc = {
      single = '每秒木材 +0.4，每秒金币 +10。',
      advanced = '后继：贪婪 / 挑战。',
    },
  }),
  node({
    id = 'bond_magic_core',
    display_name = '法术',
    group_id = 'magic',
    line_id = 'line_magic_core',
    tier = 1,
    parent_id = nil,
    next_ids = {
      'bond_magic_mage',
      'bond_magic_arcane_power',
      'bond_magic_trick',
      'bond_magic_haste',
      'bond_magic_elementalist',
    },
    route_tags = { 'skill', 'spell_cycle', 'auto_spell_burst' },
    template = 'per_second_growth',
    icon = 107016,
    editor_skill_id = 201385553,
    desc = {
      single = '魔爆术：每18秒触发，对300范围造成200%智力伤害。',
      advanced = '后继：魔法师 / 魔能 / 魔术 / 急速 / 元素师。',
    },
  }),
  node({
    id = 'bond_archery_core',
    display_name = '箭术',
    group_id = 'archery',
    line_id = 'line_archery_core',
    tier = 1,
    parent_id = nil,
    next_ids = { 'bond_archery_barrage', 'bond_archery_rapid', 'bond_archery_shooting' },
    route_tags = { 'clear', 'tempo' },
    template = 'basic_attack_modifier',
    icon = 107004,
    editor_skill_id = 201385551,
    desc = {
      single = '穿云箭：每攻击 15 次射出 1 支，造成 300% 敏捷伤害。',
      advanced = '后继：广射 / 速攻 / 射术。',
    },
  }),
  node({
    id = 'bond_critical_core',
    display_name = '暴击',
    group_id = 'critical',
    line_id = 'line_critical_core',
    tier = 1,
    parent_id = nil,
    next_ids = { 'bond_critical_deadly' },
    route_tags = { 'burst' },
    template = 'basic_attack_modifier',
    icon = 106810,
    editor_skill_id = 201385546,
    attr = {
      ['物理暴击'] = 4,
      ['魔法暴击'] = 4,
    },
    desc = {
      single = '物理暴击 +4%，魔法暴击 +4%。',
      advanced = '后继：致命。',
    },
  }),
  node({
    id = 'bond_growth_core',
    display_name = '成长',
    group_id = 'growth',
    line_id = 'line_growth_core',
    tier = 1,
    parent_id = nil,
    next_ids = { 'bond_growth_agility', 'bond_growth_strength', 'bond_growth_intelligence' },
    route_tags = { 'growth' },
    template = 'per_second_growth',
    icon = 106724,
    editor_skill_id = 201385537,
    runtime = {
      wood_per_sec_bonus = 0.2,
      agility_on_kill = 0.1,
      strength_on_kill = 0.1,
      intelligence_on_kill = 0.1,
    },
    desc = {
      single = '每秒木材 +0.2，杀敌力量 +0.1，杀敌敏捷 +0.1，杀敌智力 +0.1。',
      advanced = '后继：敏捷 / 力量 / 智力。',
    },
  }),
  node({
    id = 'bond_growth_agility',
    display_name = '敏捷',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 2,
    parent_id = 'bond_growth_core',
    next_ids = { 'bond_growth_demon_hunter' },
    route_tags = { 'growth', 'tempo' },
    template = 'static_attr',
    icon = 106724,
    editor_skill_id = 201385537,
    attr = { ['敏捷'] = 100 },
    unlock_rewards = { wood = 50 },
    desc = {
      single = '敏捷 +100，木材 +50。',
      advanced = '后继：猎魔人。',
    },
  }),
  node({
    id = 'bond_growth_demon_hunter',
    display_name = '猎魔人',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 2,
    parent_id = 'bond_growth_agility',
    next_ids = { 'bond_growth_bow_god' },
    route_tags = { 'growth', 'boss', 'tempo' },
    template = 'basic_attack_modifier',
    icon = 108140,
    editor_skill_id = 201385538,
    attr = {
      ['攻击范围'] = 100,
      ['敏捷'] = 120,
      ['攻击速度'] = 25,
      ['物理暴击'] = 6,
    },
    runtime = {
      agility_per_second = 0.2,
      all_damage_bonus = 0.03,
    },
    desc = {
      single = '攻击范围 +100，敏捷 +120。每进化 1 次，敏捷增幅 +2%，每秒敏捷 +0.2，物理伤害 +3%。',
      advanced = '后继：弓神。',
    },
  }),
  node({
    id = 'bond_growth_bow_god',
    display_name = '弓神',
    group_id = 'growth',
    line_id = 'line_growth_agility',
    tier = 3,
    parent_id = 'bond_growth_demon_hunter',
    next_ids = {},
    route_tags = { 'growth', 'boss', 'clear' },
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 108148,
    editor_skill_id = 201385539,
    attr = {
      ['命中'] = 20,
      ['攻击范围'] = 150,
    },
    runtime = {
      normal_attack_damage_bonus = 0.15,
      multishot_bonus = 1,
      bounce_count_bonus = 1,
    },
    desc = {
      single = '命中 +20%，攻击范围 +150，普攻伤害 +15%，多重数量 +1，弹射次数 +1。',
      advanced = '最终敏捷 +5%，每点敏捷额外提供 0.1 攻击力。',
    },
  }),
  node({
    id = 'bond_growth_strength',
    display_name = '力量',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 2,
    parent_id = 'bond_growth_core',
    next_ids = { 'bond_growth_barbarian' },
    route_tags = { 'growth', 'burst' },
    template = 'static_attr',
    icon = 106775,
    editor_skill_id = 201385540,
    attr = { ['力量'] = 100 },
    unlock_rewards = { wood = 50 },
    desc = {
      single = '力量 +100，木材 +50。',
      advanced = '后继：野蛮人。',
    },
  }),
  node({
    id = 'bond_growth_barbarian',
    display_name = '野蛮人',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 2,
    parent_id = 'bond_growth_strength',
    next_ids = { 'bond_growth_war_god' },
    route_tags = { 'growth', 'burst' },
    template = 'kill_stack',
    icon = 106751,
    editor_skill_id = 201385541,
    runtime = { attack_on_kill = 2 },
    desc = {
      single = '每次击杀永久攻击 +2。',
      advanced = '后继：战神。',
    },
  }),
  node({
    id = 'bond_growth_war_god',
    display_name = '战神',
    group_id = 'growth',
    line_id = 'line_growth_strength',
    tier = 3,
    parent_id = 'bond_growth_barbarian',
    next_ids = {},
    route_tags = { 'growth', 'burst' },
    template = 'kill_stack',
    quality = 'epic',
    icon = 107026,
    editor_skill_id = 201385542,
    attr = {
      ['力量'] = 200,
      ['物理暴击'] = 10,
      ['生命'] = 800,
      ['护甲'] = 10,
      ['格挡'] = 5,
    },
    runtime = { attack_on_kill = 4 },
    desc = {
      single = '力量 +200，力量增幅 +10%，物理暴击 +10%，生命值 +800，护甲 +10，格挡 +5。',
      advanced = '最终力量 +5%，每点力量额外提供 0.1 攻击力。',
    },
  }),
  node({
    id = 'bond_growth_intelligence',
    display_name = '智力',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 2,
    parent_id = 'bond_growth_core',
    next_ids = { 'bond_growth_archmage' },
    route_tags = { 'growth', 'skill' },
    template = 'static_attr',
    icon = 106912,
    editor_skill_id = 201385543,
    attr = { ['智力'] = 100 },
    unlock_rewards = { wood = 50 },
    desc = {
      single = '智力 +100，木材 +50。',
      advanced = '后继：秘法师。',
    },
  }),
  node({
    id = 'bond_growth_archmage',
    display_name = '秘法师',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 2,
    parent_id = 'bond_growth_intelligence',
    next_ids = { 'bond_growth_spell_god' },
    route_tags = { 'growth', 'skill' },
    template = 'per_second_growth',
    icon = 106905,
    editor_skill_id = 201385544,
    attr = {
      ['魔法暴击'] = 3,
      ['智力'] = 150,
    },
    runtime = {
      intelligence_per_second = 0.2,
      spell_damage_bonus = 0.03,
    },
    desc = {
      single = '魔法暴击 +3%，魔法暴伤 +9%，技能急速 +15。每进化 1 次，智力增幅 +2%，每秒智力 +0.2，魔法伤害 +3%。',
      advanced = '后继：法神。',
    },
  }),
  node({
    id = 'bond_growth_spell_god',
    display_name = '法神',
    group_id = 'growth',
    line_id = 'line_growth_intelligence',
    tier = 3,
    parent_id = 'bond_growth_archmage',
    next_ids = {},
    route_tags = { 'growth', 'skill' },
    template = 'per_second_growth',
    quality = 'epic',
    icon = 106916,
    editor_skill_id = 201385545,
    attr = {
      ['智力'] = 100,
    },
    runtime = {
      intelligence_per_second = 0.4,
      spell_damage_bonus = 0.15,
    },
    desc = {
      single = '智力 +100，全系伤害 +15%，每拥有 1 个初始技能，智力增幅 +4%。',
      advanced = '最终智力 +5%，每点智力额外提供 0.1 攻击力。',
    },
  }),
  node({
    id = 'bond_critical_deadly',
    display_name = '致命',
    group_id = 'critical',
    line_id = 'line_critical_core',
    tier = 2,
    parent_id = 'bond_critical_core',
    next_ids = { 'bond_critical_cannon' },
    route_tags = { 'burst' },
    template = 'basic_attack_modifier',
    icon = 106810,
    editor_skill_id = 201385546,
    attr = {
      ['物理暴击'] = 3,
      ['魔法暴击'] = 3,
    },
    runtime = { critical_damage_bonus = 0.20 },
    desc = {
      single = '物理暴击 +3%，魔法暴击 +3%。非暴击伤害 -20%，物理暴伤 +20%。',
      advanced = '后继：大炮。',
    },
  }),
  node({
    id = 'bond_critical_cannon',
    display_name = '大炮',
    group_id = 'critical',
    line_id = 'line_critical_core',
    tier = 3,
    parent_id = 'bond_critical_deadly',
    next_ids = {},
    route_tags = { 'burst', 'boss' },
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 106686,
    editor_skill_id = 201385547,
    attr = {
      ['物理暴击'] = 5,
      ['魔法暴击'] = 5,
    },
    runtime = { critical_damage_bonus = 0.40 },
    desc = {
      single = '致命攻击 / 致命魔法：物理或魔法暴击 +5%，暴伤 20% 概率翻倍。',
      advanced = '致命攻击：每溢出 2% 物理暴击，致命攻击触发概率 +1%。致命魔法：溢出 1% 魔法暴击，转化为 2% 魔法暴伤。',
    },
  }),
  node({
    id = 'bond_archery_barrage',
    display_name = '广射',
    group_id = 'archery',
    line_id = 'line_archery_barrage',
    tier = 2,
    parent_id = 'bond_archery_core',
    next_ids = { 'bond_archery_moon_blade' },
    route_tags = { 'clear' },
    template = 'basic_attack_modifier',
    icon = 106785,
    editor_skill_id = 201385548,
    attr = { ['攻击范围'] = 150 },
    runtime = { normal_attack_damage_bonus = 0.08 },
    desc = {
      single = '攻击范围 +150。每100攻击范围提高 1% 普攻伤害。',
      advanced = '后继：月刃。',
    },
  }),
  node({
    id = 'bond_archery_moon_blade',
    display_name = '月刃',
    group_id = 'archery',
    line_id = 'line_archery_barrage',
    tier = 2,
    parent_id = 'bond_archery_barrage',
    next_ids = {},
    route_tags = { 'clear' },
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 108246,
    editor_skill_id = 201385549,
    runtime = { bounce_count_bonus = 1 },
    desc = {
      single = '弹射次数 +1，弹射伤害 +15%。',
      advanced = '立即获得当前弹射次数 * 50 敏捷，弹射伤害 > 100% 时每溢出 1% 转化为 1% 普攻伤害。',
    },
  }),
  node({
    id = 'bond_archery_rapid',
    display_name = '速攻',
    group_id = 'archery',
    line_id = 'line_archery_rapid',
    tier = 2,
    parent_id = 'bond_archery_core',
    next_ids = {},
    route_tags = { 'tempo', 'auto_rapid_overdrive' },
    template = 'static_attr',
    icon = 106700,
    editor_skill_id = 201385550,
    attr = { ['攻击速度'] = 30 },
    desc = {
      single = '攻速 +30%，攻击间隔 -0.1。',
      advanced = '攻击 20% 概率提升 100% 攻速，持续 5 秒。',
    },
  }),
  node({
    id = 'bond_archery_shooting',
    display_name = '射术',
    group_id = 'archery',
    line_id = 'line_archery_shooting',
    tier = 2,
    parent_id = 'bond_archery_core',
    next_ids = { 'bond_archery_multishot' },
    route_tags = { 'clear', 'tempo' },
    template = 'basic_attack_modifier',
    icon = 107004,
    editor_skill_id = 201385551,
    attr = {
      ['攻击'] = 50,
      ['敏捷'] = 50,
    },
    runtime = { normal_attack_damage_bonus = 0.05 },
    desc = {
      single = '攻击力 +50，敏捷 +50。穿云箭：每攻击 15 次射出 1 支，造成 300% 敏捷伤害。',
      advanced = '后继：多重箭。',
    },
  }),
  node({
    id = 'bond_archery_multishot',
    display_name = '多重箭',
    group_id = 'archery',
    line_id = 'line_archery_shooting',
    tier = 2,
    parent_id = 'bond_archery_shooting',
    next_ids = {},
    route_tags = { 'clear' },
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 106787,
    editor_skill_id = 201385552,
    runtime = { multishot_bonus = 1 },
    desc = {
      single = '多重数量 +1，多重伤害 +15%。',
      advanced = '立即获得当前多重数量 * 50 敏捷，多重伤害 > 100% 时每溢出 1% 转化为 1% 普攻伤害。',
    },
  }),
  node({
    id = 'bond_magic_mage',
    display_name = '魔法师',
    group_id = 'magic',
    line_id = 'line_magic_mage',
    tier = 2,
    parent_id = 'bond_magic_core',
    next_ids = {},
    route_tags = { 'skill', 'resonance' },
    template = 'per_second_growth',
    icon = 107016,
    editor_skill_id = 201385553,
    attr = {
      ['攻击'] = 50,
      ['智力'] = 50,
    },
    runtime = { spell_damage_bonus = 0.075 },
    desc = {
      single = '技能伤害 +5%，魔法伤害 +7.5%。魔爆术：每18秒触发，对300范围造成200%智力伤害。',
      advanced = '',
    },
  }),
  node({
    id = 'bond_magic_arcane_power',
    display_name = '魔能',
    group_id = 'magic',
    line_id = 'line_magic_arcane_power',
    tier = 2,
    parent_id = 'bond_magic_core',
    next_ids = {},
    route_tags = { 'skill', 'spell_cycle' },
    template = 'static_attr',
    icon = 107049,
    editor_skill_id = 201385554,
    attr = { ['技能急速'] = 10 },
    desc = {
      single = '技能急速 +10。溢出 2 点急速提升 1% 技能伤害。',
      advanced = '',
    },
  }),
  node({
    id = 'bond_magic_trick',
    display_name = '魔术',
    group_id = 'magic',
    line_id = 'line_magic_trick',
    tier = 2,
    parent_id = 'bond_magic_core',
    next_ids = {},
    route_tags = { 'skill', 'tempo', 'auto_spell_burst_amp' },
    template = 'basic_attack_modifier',
    icon = 107051,
    editor_skill_id = 201385555,
    runtime = { skill_echo_chance = 0.10 },
    desc = {
      single = '魔爆术范围 +150，魔爆术冷却 -5 秒。',
      advanced = '每拥有 1 个初始技能，魔爆触发次数 +1。',
    },
  }),
  node({
    id = 'bond_magic_haste',
    display_name = '急速',
    group_id = 'magic',
    line_id = 'line_magic_haste',
    tier = 2,
    parent_id = 'bond_magic_core',
    next_ids = {},
    route_tags = { 'skill', 'tempo', 'auto_haste_reset' },
    template = 'static_attr',
    icon = 106857,
    editor_skill_id = 201385556,
    attr = {
      ['技能急速'] = 10,
      ['智力'] = 111,
    },
    desc = {
      single = '技能急速 +10，魔法伤害 +5%，智力 +111。',
      advanced = '技能冷却时 7% 概率立即重置冷却。',
    },
  }),
  node({
    id = 'bond_magic_elementalist',
    display_name = '元素师',
    group_id = 'magic',
    line_id = 'line_magic_elementalist',
    tier = 2,
    parent_id = 'bond_magic_core',
    next_ids = {},
    route_tags = { 'skill', 'element', 'burn', 'cold_tide', 'shock' },
    template = 'per_second_growth',
    icon = 106858,
    editor_skill_id = 201385557,
    runtime = { elemental_damage_bonus = 0.15 },
    desc = {
      single = '魔法伤害 +5%，元素伤害 +10%。',
      advanced = '造成物系 / 电系 / 风系伤害时，受另外 2 种 15% 增幅。',
    },
  }),
  node({
    id = 'bond_economy_greed',
    display_name = '贪婪',
    group_id = 'economy',
    line_id = 'line_economy_core',
    tier = 2,
    parent_id = 'bond_economy_core',
    next_ids = {},
    route_tags = { 'economy', 'growth' },
    template = 'kill_stack',
    icon = 106694,
    editor_skill_id = 201385558,
    runtime = { kill_gold_ratio = 0.20 },
    desc = {
      single = '以击杀金币收益为主，承接贪欲金币 / 贪欲之刃 / 贪欲钥匙。',
      advanced = '随机吞噬 4 张可吞噬卡牌。',
    },
  }),
  node({
    id = 'bond_economy_challenge',
    display_name = '挑战',
    group_id = 'economy',
    line_id = 'line_economy_core',
    tier = 2,
    parent_id = 'bond_economy_core',
    next_ids = {},
    route_tags = { 'economy', 'boss' },
    template = 'kill_stack',
    icon = 107382,
    editor_skill_id = 201385559,
    runtime = { kill_reward_ratio = 0.10 },
    desc = {
      single = '杀敌经验 +10%，杀敌加成 +10%。',
      advanced = '每秒木材 +0.4，每秒金币 +10。',
    },
  }),
  node({
    id = 'bond_body_life',
    display_name = '生命',
    group_id = 'body',
    line_id = 'line_body_life',
    tier = 2,
    parent_id = 'bond_body_core',
    next_ids = { 'bond_body_blood_oath' },
    route_tags = { 'survival', 'blessing' },
    template = 'static_attr',
    icon = 107362,
    editor_skill_id = 201385560,
    attr = {
      ['生命'] = 200,
      ['护甲'] = 5,
    },
    desc = {
      single = '生命值 +200，生命增幅 +5%，护甲 +5。',
      advanced = '后继：血誓。',
    },
  }),
  node({
    id = 'bond_body_blood_oath',
    display_name = '血誓',
    group_id = 'body',
    line_id = 'line_body_life',
    tier = 2,
    parent_id = 'bond_body_life',
    next_ids = { 'bond_body_blood_demon' },
    route_tags = { 'blood_pact', 'survival' },
    template = 'kill_stack',
    quality = 'epic',
    icon = 106542,
    editor_skill_id = 201385561,
    attr = { ['生命'] = 500 },
    desc = {
      single = '生命值 +500。每100点生命上限转为额外属性：血刃 / 血契 / 血矛效果翻倍。',
      advanced = '后继：血魔。',
    },
  }),
  node({
    id = 'bond_body_blood_demon',
    display_name = '血魔',
    group_id = 'body',
    line_id = 'line_body_life',
    tier = 3,
    parent_id = 'bond_body_blood_oath',
    next_ids = {},
    route_tags = { 'berserk', 'burst', 'survival', 'auto_blood_demon_burst' },
    template = 'kill_stack',
    quality = 'epic',
    icon = 106720,
    editor_skill_id = 201385562,
    attr = {
      ['攻击'] = 100,
      ['力量'] = 100,
    },
    runtime = { low_hp_damage_bonus = 0.20 },
    desc = {
      single = '攻击 +100，力量 +100。每损失 1% 生命，所有伤害 +0.5%。',
      advanced = '每损失 35% 生命值触发回血，造成 50% 生命伤害并晕眩。',
    },
  }),
  node({
    id = 'bond_body_tactics',
    display_name = '战术',
    group_id = 'body',
    line_id = 'line_body_tactics',
    tier = 2,
    parent_id = 'bond_body_core',
    next_ids = {},
    route_tags = { 'armor_break' },
    template = 'static_attr',
    icon = 106761,
    editor_skill_id = 201385563,
    runtime = { all_damage_bonus = 0.04 },
    desc = {
      single = '斗气场域内敌人护甲 -10%，攻击力 -30%。',
      advanced = '斗气场域额外附加 30% 生命伤害，每击杀 1 敌力量 +0.5。',
    },
  }),
  node({
    id = 'bond_body_fortress',
    display_name = '固守',
    group_id = 'body',
    line_id = 'line_body_fortress',
    tier = 2,
    parent_id = 'bond_body_core',
    next_ids = { 'bond_body_charge_breaker' },
    route_tags = { 'survival' },
    template = 'static_attr',
    icon = 106869,
    editor_skill_id = 201385564,
    attr = {
      ['生命'] = 100,
      ['护甲'] = 5,
      ['格挡'] = 5,
    },
    desc = {
      single = '生命值 +100，护甲 +5，格挡 +5。',
      advanced = '护甲增幅 +10%，单次伤害不超过生命值 35%。后继：陷阵。',
    },
  }),
  node({
    id = 'bond_body_charge_breaker',
    display_name = '陷阵',
    group_id = 'body',
    line_id = 'line_body_fortress',
    tier = 2,
    parent_id = 'bond_body_fortress',
    next_ids = {},
    route_tags = { 'boss', 'armor_break', 'auto_charge_breaker_rally' },
    template = 'basic_attack_modifier',
    quality = 'epic',
    icon = 106989,
    editor_skill_id = 201385565,
    runtime = {
      elite_damage_bonus = 0.20,
      boss_damage_bonus = 0.20,
    },
    desc = {
      single = '护甲 +5，格挡 +5；每击杀100敌伤害减免 +1%，最高25%。',
      advanced = '每击杀200敌触发全属性 +20%、攻速 +50%、技能急速 +30，持续10秒。',
    },
  }),
}

local by_id = {}
local root_ids = {}
local by_line = {}
local by_group = {}

for _, def in ipairs(list) do
  assert(not by_id[def.id], string.format('duplicate bond node id: %s', def.id))
  by_id[def.id] = def
  by_line[def.line_id] = by_line[def.line_id] or {}
  by_line[def.line_id][#by_line[def.line_id] + 1] = def
  by_group[def.group_id] = by_group[def.group_id] or {}
  by_group[def.group_id][#by_group[def.group_id] + 1] = def
  if not def.parent_id then
    root_ids[#root_ids + 1] = def.id
  end
end

for _, def in ipairs(list) do
  if def.parent_id then
    assert(by_id[def.parent_id], string.format('missing parent_id for bond node: %s -> %s', def.id, def.parent_id))
  end
  for _, next_id in ipairs(def.next_ids) do
    assert(by_id[next_id], string.format('missing next_id for bond node: %s -> %s', def.id, next_id))
  end
end

return {
  list = list,
  by_id = by_id,
  root_ids = root_ids,
  by_line = by_line,
  by_group = by_group,
}
