local M = {}

function M.create(args)
  local AttackSkillObjects = assert(args and args.AttackSkillObjects, 'AttackSkillObjects is required')
  local ATTACK_SKILL_DEFS = AttackSkillObjects.defs_by_id
  local ATTACK_SKILL_BLUEPRINTS = AttackSkillObjects.blueprints
  local ATTACK_SKILL_SLOT_COUNT = 5

  local function create_skill_runtime()
    return {
      normal_attack_bonus_ratio = 0,
      splash_ratio = 0,
      splash_radius = 220,
      chain_chance = 0,
      chain_bounces = 0,
      chain_ratio = 0,
      chain_radius = 420,
      execute_threshold = 0,
      medbot_every = 0,
      medbot_heal = 0,
      medbot_kills = 0,
      artillery_interval = 0,
      artillery_ratio = 0,
      artillery_base = 0,
      artillery_radius = 0,
      artillery_cd = 0,
      bonus_gold_on_kill = 0,
      split_count = 0,
      split_ratio = 0,
      boss_bonus_ratio = 0,
      armor_break_ratio = 0,
      armor_break_duration = 0,
      armor_break_max_stacks = 0,
      secondary_targets = 0,
      burst_radius = 0,
      burst_ratio = 0,
      extra_targets = 0,
      ignite_duration = 0,
      ignite_tick_ratio = 0,
      ignite_spread_radius = 0,
      frost_control_bonus = 0,
      shatter_bonus = 0,
      shard_count = 0,
      shard_ratio = 0,
      shock_duration = 0,
      shock_bonus = 0,
      field_radius = 0,
      field_ratio = 0,
      apply_generic_armor_break = false,
      apply_generic_ignite = false,
      apply_generic_shock = false,
      apply_generic_control = false,
      generic_status_duration = 0,
      terminal_burst_radius = 0,
      terminal_burst_ratio = 0,
      followup_count = 0,
      followup_ratio = 0,
      split_seek_count = 0,
      split_seek_ratio = 0,
      split_seek_radius = 0,
      split_seek_depth = 0,
      kill_seek_count = 0,
      kill_seek_ratio = 0,
      kill_seek_radius = 0,
      echo_count = 0,
      echo_ratio = 0,
      return_pass_enabled = false,
      return_pass_ratio = 0.75,
      sweep_enabled = false,
      field_track_target = false,
      persistent_field_duration = 0,
      persistent_field_ratio = 0,
      persistent_field_control = false,
      persistent_field_ignite = false,
      pull_strength = 0,
    }
  end

  local function create_attack_skill_instance(skill_id, slot)
    local def = ATTACK_SKILL_DEFS[skill_id]
    local blueprint = ATTACK_SKILL_BLUEPRINTS.by_id and ATTACK_SKILL_BLUEPRINTS.by_id[skill_id] or nil
    local blueprint_base = blueprint and blueprint.base or {}
    return {
      id = def.id,
      name = def.name,
      slot = slot or def.default_slot or 0,
      summary = def.summary,
      archetype = def.archetype or (blueprint and blueprint.archetype) or nil,
      category = def.category or nil,
      cast_family = def.cast_family or nil,
      presentation_family = def.presentation_family or nil,
      eca_reference = def.eca_reference or nil,
      ui_icon = def.ui_icon or (blueprint and (blueprint.ui_icon or blueprint.icon)) or nil,
      icon = def.icon or def.ui_icon or (blueprint and (blueprint.icon or blueprint.ui_icon)) or nil,
      evolution_name = def.evolution_name or (blueprint and blueprint.evolution and blueprint.evolution.name) or nil,
      evolution_summary = def.evolution_summary or (blueprint and blueprint.evolution and blueprint.evolution.summary) or nil,
      damage_type = def.damage_type,
      damage_form = def.damage_form,
      element = def.element,
      damage_label = def.damage_label,
      level = 1,
      unlocked = true,
      damage_ratio = def.base_damage_ratio or 0,
      base_cooldown = def.base_cooldown or 0,
      cooldown_reduction = 0,
      cooldown_remaining = 0,
      cast_range = def.base_range or 0,
      range_bonus = 0,
      attack_speed_bonus = 0,
      pierce = def.base_pierce or 0,
      pierce_width = def.base_pierce_width or 90,
      base_duration = def.base_duration or blueprint_base.duration or 0,
      base_radius = def.base_radius or blueprint_base.radius or 0,
      base_bounce = def.base_bounce or blueprint_base.bounce or 0,
      repeat_count = def.base_repeat_count or 1,
      explosion_ratio = def.base_explosion_ratio or 0,
      explosion_radius = def.base_explosion_radius or 0,
      extra_targets = def.base_extra_targets or 0,
      control_lock_time = def.base_control_lock_time or 0,
      knockback_distance = def.base_knockback_distance or 0,
      knockback_speed = def.base_knockback_speed or 900,
      split_count = 0,
      split_ratio = 0,
      boss_bonus_ratio = 0,
      armor_break_ratio = 0,
      armor_break_duration = 0,
      armor_break_max_stacks = 0,
      secondary_targets = 0,
      burst_radius = 0,
      burst_ratio = 0,
      ignite_duration = 0,
      ignite_tick_ratio = 0,
      ignite_spread_radius = 0,
      frost_control_bonus = 0,
      shatter_bonus = 0,
      shard_count = 0,
      shard_ratio = 0,
      shock_duration = 0,
      shock_bonus = 0,
      field_radius = 0,
      field_ratio = 0,
      apply_generic_armor_break = false,
      apply_generic_ignite = false,
      apply_generic_shock = false,
      apply_generic_control = false,
      generic_status_duration = 0,
      terminal_burst_radius = 0,
      terminal_burst_ratio = 0,
      followup_count = 0,
      followup_ratio = 0,
      split_seek_count = 0,
      split_seek_ratio = 0,
      split_seek_radius = 0,
      split_seek_depth = 0,
      kill_seek_count = 0,
      kill_seek_ratio = 0,
      kill_seek_radius = 0,
      echo_count = 0,
      echo_ratio = 0,
      return_pass_enabled = false,
      return_pass_ratio = 0.75,
      sweep_enabled = false,
      field_track_target = false,
      persistent_field_duration = 0,
      persistent_field_ratio = 0,
      persistent_field_control = false,
      persistent_field_ignite = false,
      pull_strength = 0,
    }
  end

  local function create_attack_skill_state()
    local basic_attack = create_attack_skill_instance('basic_attack', 1)
    return {
      slots = {
        [1] = basic_attack,
      },
      by_id = {
        basic_attack = basic_attack,
      },
      upgrade_counts = {},
      last_picked_skill_id = nil,
      new_skill_feed = {},
      unlock_offer_fail_streak = 0,
    }
  end

  local function create_initial_state()
    return {
      hero = nil,
      hero_common_attack = nil,
      hero_spawn_point = nil,
      defense_point = nil,
      all_enemies = nil,
      total_enemy_alive = 0,
      total_kills = 0,
      current_wave_index = 0,
      started_wave_count = 0,
      active_wave = nil,
      active_challenges = nil,
      resources = nil,
      resource_income_elapsed = 0,
      bond_runtime = nil,
      battle_event_feed = nil,
      effect_debug_runtime = nil,
      mark_runtime = nil,
      treasure_runtime = nil,
      auto_active_effects = nil,
      enemy_info_map = nil,
      skill_points = 0,
      hero_progress = nil,
      awaiting_upgrade = false,
      current_upgrade_choices = nil,
      current_upgrade_round = nil,
      skill_runtime = nil,
      attack_skill_state = nil,
      reward_queue = nil,
      challenge_charges = 0,
      challenge_recover_elapsed = 0,
      bond_draw_count = 0,
      defeated_boss_waves = nil,
      basic_attack_ability_bound = false,
      basic_attack_ability_warned = false,
      debug_ctrl_down_count = 0,
      runtime_elapsed = 0,
      runtime_hud = nil,
      choice_panel = nil,
      choice_panel_hidden = false,
      runtime_overview = nil,
      runtime_overview_mode = 'build',
      runtime_attr_tab_panel = nil,
      runtime_attr_tab_selected = 'summary',
      hero_attr_runtime = nil,
      attr_choice_runtime = nil,
      hero_form_skill_runtime = nil,
      gm_ui = nil,
      session_phase = 'outgame',
      outgame_profile = nil,
      selected_stage_id = nil,
      selected_mode_id = nil,
      current_stage_def = nil,
      current_mode_def = nil,
      last_battle_result = nil,
      outgame_ui = nil,
      outgame_profile_save_enabled = false,
      outgame_profile_save_warned = false,
      game_finished = false,
    }
  end

  return {
    ATTACK_SKILL_DEFS = ATTACK_SKILL_DEFS,
    ATTACK_SKILL_BLUEPRINTS = ATTACK_SKILL_BLUEPRINTS,
    ATTACK_SKILL_SLOT_COUNT = ATTACK_SKILL_SLOT_COUNT,
    create_skill_runtime = create_skill_runtime,
    create_attack_skill_instance = create_attack_skill_instance,
    create_attack_skill_state = create_attack_skill_state,
    create_initial_state = create_initial_state,
  }
end

return M
