local a=(require'data.game_tables').hero_roster
local b=require'data.tables.hero.hero_form_skills'
local c={}function c.create(d)local e=d.STATE;
local f=d.y3;
local g=d.message or function()end;
local h=d.round_number or function(i)return math.floor((i or 0)+0.5)end;
local j=d.hero_attr_system;
local k=d.is_active_enemy;
local l=d.get_enemies_in_range;
local m=d.get_enemy_runtime_info;
local n=d.is_boss_runtime_enemy;
local o=d.is_elite_runtime_enemy;
local p=d.deal_skill_damage;
local q=d.heal_hero;
local r=d.play_skill_sound or function()end;
local s={}local function t()if not e.hero_form_skill_runtime then e.hero_form_skill_runtime={cooldowns={},counters={},active_hero_id=nil,active_skill_id=nil,announced_hero_id=nil}end;
return e.hero_form_skill_runtime end;
local function u(v)v.cooldowns={}v.counters={}end;
local function w(x)if not x or not x.move then return nil end;
return x:move()end;
local function y(z)if not z or not z.is_exist or not z:is_exist()then return nil end;
return w(z:get_point())end;
local function A(B)local z=B and B.unit or nil;
if z and z.is_exist and z:is_exist()then return w(z:get_point())end;
return nil end;
local function C()local D=e.evolution_runtime;
if D and D.active_form_unit_id then return tonumber(D.active_form_unit_id)end;
if e.hero and e.hero.is_exist and e.hero:is_exist()and e.hero.get_key then return tonumber(e.hero:get_key())end;
return nil end;
local function E()local F=C()if not F or not a or type(a)~='table' or type(a.by_unit_id)~='table' then return nil end;
return a.by_unit_id[F]end;
local function G()local H=E()if not H or not b or type(b)~='table' then return nil,nil end;
return (b.by_roster_id and b.by_roster_id[H.id])or b.by_hero_id and b.by_hero_id[H.id],H end;
local function I(H,J)if not H or not J then return end;g(string.format('????????[%s] %s???????%s??????��??',tostring(H.rarity or'?'),tostring(H.name or H.id),tostring(J.name or J.id)))end;
local function K(J)return t().cooldowns[J.id]or 0 end;
local function L(J,M)t().cooldowns[J.id]=math.max(0,M or 0)end;
local function N(J,O)local v=t()v.counters[J.id]=(v.counters[J.id]or 0)+(O or 0)return v.counters[J.id]end;
local function P(J)t().counters[J.id]=0 end;
local function Q(R)local v=t()for S,T in pairs(v.cooldowns)do v.cooldowns[S]=math.max(0,(T or 0)-R)end end;
local function U(V,W)if not e.hero or not e.hero.is_exist or not e.hero:is_exist()then return 0 end;
local i=j and j.get_attr(e.hero,V)or e.hero:get_attr(V)i=f.helper.tonumber(i)or 0;
if i>0 or not W then return i end;
local X=j and j.get_attr(e.hero,W)or e.hero:get_attr(W)return f.helper.tonumber(X)or 0 end;
local function Y()return math.max(1,U('?????????','????'))end;
local function Z()local i=U('?????????','????')if i>0 then return i end;
return math.max(1,U('???????'))end;
local function _(a0)if not a0 or not a0.is_exist or not a0:is_exist()then return 1 end;
local a1=f.helper.tonumber(a0:get_attr('????'))or f.helper.tonumber(a0:get_attr('???????'))or 0;
if a1<=0 then return 1 end;
return math.max(0,(a0:get_hp()or 0)/a1)end;
local function a2(a0)if not a0 or not m then return false end;
local B=m(a0)return n and n(B)or o and o(B)or false end;
local function a3(J)return{damage_type=J.damage_type or'????',damage_form=J.damage_form or'spell',element=J.element or'none',damage_label=J.damage_label or'??????'}end;
local function a4(J,a5,a0)local a6=Y()*math.max(0,a5 or 0)if(J.boss_bonus_ratio or 0)>0 and a2(a0)then a6=a6*(1+(J.boss_bonus_ratio or 0))end;
return math.max(0,a6)end;
local function a7(J,a0,a5)if not a0 or not k(a0)then return false end;
local a6=a4(J,a5 or J.damage_ratio,a0)if a6<=0 then return false end;p(a0,a6,a3(J))return true end;
local function a8(a9,aa,ab,ac)if not a9 or not aa or aa<=0 then return{}end;
return l(a9,aa,ab,ac)end;
local function ad(J,ae)if ae and ae.target and k(ae.target)then return ae.target end;
local aa=math.max(320,J.radius or 0,960)return a8(e.hero,aa,nil,1)[1]end;
local function af(J,x,a5)if not x then return false end;
local ag=false;
for ah,z in ipairs(a8(x,J.radius or 220,nil,nil))do ag=a7(J,z,a5)or ag end;
return ag end;
local function ai(J)local ag=false;
for ah,z in ipairs(a8(e.hero,J.radius or 240,nil,nil))do ag=a7(J,z,J.damage_ratio)or ag end;
return ag end;
local function aj(J)local ak=false;if(J.heal_ratio or 0)>0 then q(h(Z()*(J.heal_ratio or 0)))ak=true end;
return ai(J)or ak end;
local function al(J,ae)local a0=ad(J,ae)if not a0 then return false end;
local ag=a7(J,a0,J.damage_ratio)local am=J.splash_ratio and J.splash_ratio>0 and J.splash_ratio or(J.damage_ratio or 0)for ah,z in ipairs(a8(a0,J.radius or 220,a0,nil))do ag=a7(J,z,am)or ag end;
return ag end;
local function an(J,ae)local a0=ad(J,ae)if not a0 then return false end;
local ag=a7(J,a0,J.damage_ratio)local am=J.splash_ratio and J.splash_ratio>0 and J.splash_ratio or 0;
if am>0 then for ah,z in ipairs(a8(a0,J.radius or 180,a0,nil))do ag=a7(J,z,am)or ag end end;
return ag end;
local function ao(J,ae)local a0=ad(J,ae)if not a0 then return false end;
local ag=a7(J,a0,J.damage_ratio)local ap=math.max(0,h(J.target_count or 0))local am=J.splash_ratio and J.splash_ratio>0 and J.splash_ratio or J.damage_ratio;
for ah,z in ipairs(a8(a0,J.radius or 420,a0,ap))do ag=a7(J,z,am)or ag end;
return ag end;
local function aq(J,ae)local ar=ad(J,ae)if not ar then return false end;
local ag=a7(J,ar,J.damage_ratio)local as=J.splash_ratio and J.splash_ratio>0 and J.splash_ratio or J.damage_ratio;
local at=math.max(0,h(J.bounce_count or 0))local au={[ar]=true}for ah=1,at,1 do local av=nil;
for ah,z in ipairs(a8(ar,J.radius or 420,nil,8))do if not au[z]then av=z;break end end;
if not av then break end;au[av]=true;ar=av;ag=a7(J,ar,as)or ag end;
return ag end;
local function aw(J,ae)local ax=ad(J,ae)local ay=ae and ae.point or nil;
local az=math.max(1,h(J.repeat_count or 1))local aA=math.max(1,h(J.target_count or 1))local aB=math.max(0.05,J.repeat_interval or 0.18)
for aC=1,az,1 do f.ltimer.wait((aC-1)*aB,function()if not e.hero or not e.hero.is_exist or not e.hero:is_exist()or e.game_finished then return end;
local a9=ay;
if not a9 and ax and ax.is_exist and ax:is_exist()then a9=ax end;a9=a9 or e.hero;
for ah,z in ipairs(a8(a9,J.radius or 320,nil,aA))do a7(J,z,J.damage_ratio)end end)end;
return true end;
local function aD(J,ae)local x=ae and ae.point or nil;
if not x then local a0=ad(J,ae)x=y(a0)end;x=x or y(e.hero)if not x then return false end;
local aE=w(x)local aF=w(x)local aG=math.max(0,J.delay or 0)
f.ltimer.wait(aG,function()if e.game_finished then return end;af(J,aE,J.damage_ratio)if(J.splash_ratio or 0)>0 then f.ltimer.wait(0.15,function()if e.game_finished then return end;af(J,aF,J.splash_ratio)end)end end)
return true end;
local function aH(J,ae)if(J.gold_gain or 0)>0 and e.resources then e.resources.gold=(e.resources.gold or 0)+h(J.gold_gain or 0)end;
local x=ae and ae.point or nil;
if not x then x=A(ae and ae.info or nil)end;
if not x then return false end;
local ag=af(J,w(x),J.damage_ratio)if(J.splash_ratio or 0)>0 then f.ltimer.wait(0.12,function()if e.game_finished then return end;af(J,w(x),J.splash_ratio)end)end;
return ag or true end;
local function aI(J,ae)local a0=ad(J,ae)if not a0 then return false end;
local ag=a7(J,a0,J.damage_ratio)if(J.hp_threshold or 0)>0 and _(a0)<=(J.hp_threshold or 0)then local aJ=f.helper.tonumber(a0:get_hp())or 0;
if aJ>0 then p(a0,aJ+a4(J,0.15,a0),a3(J))ag=true end end;if(J.splash_ratio or 0)>0 then for ah,z in ipairs(a8(a0,J.radius or 180,a0,nil))do ag=a7(J,z,J.splash_ratio)or ag end end;
return ag end;
local aK={hero_pulse=ai,healing_wave=aj,cleave_target=al,target_burst=an,fan_volley=ao,chain_bolt=aq,repeat_strikes=aw,meteor_zone=aD,corpse_burst=aH,execute_burst=aI}
local function aL(J,ae)if not J or not aK[J.pattern]then return false end;
if not e.hero or not e.hero.is_exist or not e.hero:is_exist()or e.game_finished then return false end;
if K(J)>0 then return false end;
local aM,aN=pcall(aK[J.pattern],J,ae or{})if not aM or not aN then return false end;L(J,J.cooldown or 0)r(J)return true end;
local function aO()local v=t()local J,H=G()local aP=H and H.id or nil;
local S=J and J.id or nil;
if v.active_hero_id~=aP or v.active_skill_id~=S then v.active_hero_id=aP;v.active_skill_id=S;u(v)end;
if v.announced_hero_id~=aP then v.announced_hero_id=aP;
if H and J then I(H,J)end end;
return J,H end;
function s.update(R)if not e.hero or not e.hero.is_exist or not e.hero:is_exist()or e.game_finished then return end;Q(R)local J=aO()if not J then return end;
if J.trigger_type=='interval'then aL(J,{})return end;
if J.trigger_type=='low_hp_interval'then local aQ=_(e.hero)if aQ<=(J.hp_threshold or 0)then aL(J,{})end end end;
function s.handle_basic_attack_cast(a0)local J=aO()if not J or J.trigger_type~='basic_attack'then return end;
local aR=math.max(1,h(J.trigger_value or 1))if N(J,1)>=aR and aL(J,{target=a0})then P(J)end end;
function s.handle_attack_skill_cast(aS,a0)if not aS or aS.id=='basic_attack'then return end;
local J=aO()if not J or J.trigger_type~='attack_skill'then return end;
local aR=math.max(1,h(J.trigger_value or 1))if N(J,1)>=aR and aL(J,{target=a0})then P(J)end end;
function s.handle_enemy_kill(B)local J=aO()if not J or J.trigger_type~='enemy_kill'then return end;
local aR=math.max(1,h(J.trigger_value or 1))if N(J,1)>=aR and aL(J,{info=B,point=A(B)})then P(J)end end;
function s.get_active_entry()local ah,H=G()return H end;
function s.get_active_skill()local J=G()return J end;
function s.force_cast_skill(skill_id,target,point)local J=b.by_id[tostring(skill_id or '')]if not J then return false,'��???????????'..tostring(skill_id)end;
local ok=aL(J,{target=target,point=point})if not ok then return false,'??????????????'..tostring(J.name or J.id)end;
return true,'??????????????'..tostring(J.name or J.id)end;
function s.get_roster()return a end;
function s.get_skill_defs()return b end;
return s end;
return c





