#!/usr/bin/env python
# -*- coding: utf-8 -*-

import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPO_ROOT = ROOT.parents[1]
BONDS = ROOT / 'script' / 'runtime' / 'bonds.lua'
NODE_DEFS = ROOT / 'script' / 'runtime' / 'bond_nodes.lua'
REWARDS = ROOT / 'script' / 'runtime' / 'rewards.lua'
CHOICE_PANEL_MODEL = ROOT / 'script' / 'runtime' / 'choice_panel_model.lua'
OVERVIEW_MODEL = ROOT / 'script' / 'runtime' / 'overview_model.lua'
BOOT = ROOT / 'script' / 'runtime' / 'boot.lua'
BONDS_CHAIN = ROOT / 'script' / 'runtime' / 'bonds_chain.lua'
TEXT_COLORIZER = ROOT / 'script' / 'ui' / 'choice_panel_text_colorizer.lua'
INPUT_EVENTS = ROOT / 'script' / 'runtime' / 'input_events.lua'
DEBUG_TOOLS = ROOT / 'script' / 'runtime' / 'debug_tools.lua'
ATTACK_SKILLS = ROOT / 'script' / 'runtime' / 'attack_skills.lua'
ATTACK_UPGRADES = ROOT / 'script' / 'runtime' / 'attack_upgrades.lua'
AUTO_ACTIVE_EFFECTS = ROOT / 'script' / 'runtime' / 'auto_active_effects.lua'
HERO_ATTR_DEFS = ROOT / 'script' / 'runtime' / 'hero_attr_defs.lua'
AUTO_ACTIVE_EFFECT_DEFS = ROOT / 'script' / 'entry_objects' / 'auto_active_effects.lua'
BOND_ABILITY_CONFIG = ROOT / 'script' / 'tools' / 'bond_node_ability_config.json'
CSV_BOND_ROOT_SETS = ROOT / 'script' / 'data_csv' / 'bond_root_sets.csv'
CSV_BOND_NODES = ROOT / 'script' / 'data_csv' / 'bond_nodes.csv'
FIGHTING_SPIRIT_MODIFIER = ROOT / 'editor_table' / 'modifierall' / '201365014.json'
LEGACY_BONDS_DIR = ROOT / 'script' / 'entry_objects' / 'bonds'
LEGACY_BOND_CARDS_DIR = ROOT / 'script' / 'entry_objects' / 'bond_cards'
LEGACY_BOND_RECIPES_DIR = ROOT / 'script' / 'entry_objects' / 'bond_recipes'
LUA = Path(r'C:\Users\裴浩然\AppData\Local\Programs\Lua\5.4.8\lua.exe')
LUAC = Path(r'C:\Users\裴浩然\AppData\Local\Programs\Lua\5.4.8\luac.exe')


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=REPO_ROOT,
        text=True,
        encoding='utf-8',
        errors='replace',
        capture_output=True,
        check=False,
    )


def assert_ok(result: subprocess.CompletedProcess[str], message: str) -> None:
    if result.returncode != 0:
        raise AssertionError(f'{message}\nSTDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}')


def assert_contains(content: str, needle: str, message: str) -> None:
    if needle not in content:
        raise AssertionError(message)


def assert_not_contains(content: str, needle: str, message: str) -> None:
    if needle in content:
        raise AssertionError(message)


def main() -> None:
    if not HERO_ATTR_DEFS.exists():
        raise AssertionError('hero_attr_defs.lua should exist')

    if LEGACY_BONDS_DIR.exists():
        raise AssertionError('legacy entry_objects/bonds directory should be removed')
    if LEGACY_BOND_CARDS_DIR.exists():
        raise AssertionError('legacy entry_objects/bond_cards directory should be removed')
    if LEGACY_BOND_RECIPES_DIR.exists():
        raise AssertionError('legacy entry_objects/bond_recipes directory should be removed')

    syntax = run([str(LUAC), '-p', str(BONDS)])
    assert_ok(syntax, 'runtime/bonds.lua syntax check failed')

    syntax = run([str(LUAC), '-p', str(TEXT_COLORIZER)])
    assert_ok(syntax, 'ui/choice_panel_text_colorizer.lua syntax check failed')

    syntax = run([str(LUAC), '-p', str(DEBUG_TOOLS)])
    assert_ok(syntax, 'runtime/debug_tools.lua syntax check failed')

    smoke_source = (
            "package.path = 'maps/EntryMap/script/?.lua;maps/EntryMap/script/?/init.lua;maps/EntryMap/script/?/?.lua;' .. package.path "
            "local bonds = require('runtime.bonds') "
            "local state = { bond_runtime = bonds.create_runtime(), resources = { wood = 0 } } "
            "assert(type(bonds.create_runtime) == 'function') "
            "assert(type(bonds.try_draw) == 'function') "
            "assert(type(bonds.apply_choice) == 'function') "
            "assert(type(bonds.notify_attack_skill_cast) == 'function') "
            "assert(type(bonds.collect_route_tags) == 'function') "
            "assert(type(bonds.has_route_tag) == 'function') "
            "assert(bonds.can_unlock_node(state, 'bond_growth_core') == true) "
            "assert(bonds.can_unlock_node(state, 'bond_growth_demon_hunter') == false) "
            "local bond_nodes = require('runtime.bond_nodes') "
            "local defs = bond_nodes.by_id "
            "assert(defs.bond_growth_agility.display_name == '敏捷') "
            "assert(defs.bond_growth_core.next_ids[1] == 'bond_growth_core_agility_up', 'xmind: 成长应先接基础成长链') "
            "assert(defs.bond_growth_core_agility_up.parent_id == 'bond_growth_core', 'xmind: 敏捷提升应接在成长后面') "
            "assert(defs.bond_growth_core_strength_up.parent_id == 'bond_growth_core_agility_up', 'xmind: 力量提升应接在敏捷提升后面') "
            "assert(defs.bond_growth_core_attack_up.parent_id == 'bond_growth_core_strength_up', 'xmind: 攻击提升应接在力量提升后面') "
            "assert(defs.bond_growth_agility.parent_id == 'bond_growth_core_attack_up', 'xmind: 敏捷分支应接在基础成长链完成后') "
            "assert(defs.bond_growth_agility.next_ids[1] == 'bond_growth_agility_grant', 'doc: 敏捷分支应先接赋予敏捷') "
            "assert(defs.bond_growth_agility_grant.parent_id == 'bond_growth_agility', 'doc: 赋予敏捷应接在敏捷之源后') "
            "assert(defs.bond_growth_agility_growth.parent_id == 'bond_growth_agility_grant', 'doc: 敏捷成长应接在赋予敏捷后') "
            "assert(defs.bond_growth_agility_amp.parent_id == 'bond_growth_agility_growth', 'doc: 敏捷增幅应接在敏捷成长后') "
            "assert(defs.bond_growth_demon_hunter.parent_id == 'bond_growth_agility_amp', 'doc: 猎魔人应在基础敏捷四张卡后开启') "
            "assert(defs.bond_growth_demon_hunter.next_ids[1] == 'bond_growth_demon_hunter_heartseeker', 'doc: 猎魔人应继续按文档拆卡') "
            "assert(defs.bond_growth_bow_god.parent_id == 'bond_growth_demon_hunter_hunt', 'doc: 弓神应在猎魔人四张卡后开启') "
            "assert(defs.bond_growth_bow_god.next_ids[1] == 'bond_growth_bow_god_piercing', 'doc: 弓神应继续按文档拆卡') "
            "assert(string.find(defs.bond_growth_agility.desc.single, '木材', 1, true) ~= nil, '敏捷应带木材收益文案') "
            "assert(defs.bond_growth_demon_hunter.display_name == '猎魔人') "
            "assert(defs.bond_growth_bow_god.display_name == '弓神') "
            "assert(defs.bond_growth_agility_grant.display_name == '赋予敏捷', 'doc: 敏捷第二张卡名称应与总表一致') "
            "assert(defs.bond_growth_agility_growth.display_name == '敏捷成长', 'doc: 敏捷第三张卡名称应与总表一致') "
            "assert(defs.bond_growth_agility_amp.display_name == '敏捷增幅', 'doc: 敏捷第四张卡名称应与总表一致') "
            "assert(defs.bond_growth_demon_hunter_heartseeker.display_name == '觅心箭', 'doc: 猎魔人第二张卡名称应与总表一致') "
            "assert(defs.bond_growth_demon_hunter_rapid.display_name == '急速射击', 'doc: 猎魔人第三张卡名称应与总表一致') "
            "assert(defs.bond_growth_demon_hunter_hunt.display_name == '射猎技巧', 'doc: 猎魔人第四张卡名称应与总表一致') "
            "assert(defs.bond_growth_bow_god_piercing.display_name == '百步穿杨', 'doc: 弓神第二张卡名称应与总表一致') "
            "assert(defs.bond_growth_bow_god_master.display_name == '弓箭大师', 'doc: 弓神第三张卡名称应与总表一致') "
            "assert(defs.bond_growth_core.display_name == '成长') "
            "assert(#defs.bond_growth_core.next_ids == 1, 'xmind: 成长首张后只应继续基础成长链') "
            "assert(string.find(defs.bond_growth_core.desc.single, '智力提升', 1, true) ~= nil and string.find(defs.bond_growth_core.desc.single, '敏捷提升', 1, true) == nil, 'doc: 成长根节点只应展示第一张基础成长卡') "
            "assert(defs.bond_growth_strength.next_ids[1] == 'bond_growth_strength_amp', 'doc: 力量分支应继续按文档拆基础卡') "
            "assert(defs.bond_growth_strength_amp.parent_id == 'bond_growth_strength', 'doc: 力量增幅应接在力量之源后') "
            "assert(defs.bond_growth_strength_growth.parent_id == 'bond_growth_strength_amp', 'doc: 力量成长应接在力量增幅后') "
            "assert(defs.bond_growth_strength_grant.parent_id == 'bond_growth_strength_growth', 'doc: 赋予力量应接在力量成长后') "
            "assert(defs.bond_growth_barbarian.parent_id == 'bond_growth_strength_grant', 'doc: 野蛮人应在基础力量四张卡后开启') "
            "assert(defs.bond_growth_barbarian.next_ids[1] == 'bond_growth_barbarian_steel', 'doc: 野蛮人应继续按文档拆卡') "
            "assert(defs.bond_growth_war_god.parent_id == 'bond_growth_barbarian_warcry', 'doc: 战神应在野蛮人四张卡后开启') "
            "assert(defs.bond_growth_war_god.next_ids[1] == 'bond_growth_war_god_guard', 'doc: 战神应继续按文档拆卡') "
            "assert(defs.bond_growth_strength_amp.display_name == '力量增幅', 'doc: 力量第二张卡名称应与总表一致') "
            "assert(defs.bond_growth_strength_growth.display_name == '力量成长', 'doc: 力量第三张卡名称应与总表一致') "
            "assert(defs.bond_growth_strength_grant.display_name == '赋予力量', 'doc: 力量第四张卡名称应与总表一致') "
            "assert(defs.bond_growth_barbarian_steel.display_name == '钢铁之肤', 'doc: 野蛮人第二张卡名称应与总表一致') "
            "assert(defs.bond_growth_barbarian_hammer.display_name == '先祖之锤', 'doc: 野蛮人第三张卡名称应与总表一致') "
            "assert(defs.bond_growth_barbarian_warcry.display_name == '集结呐喊', 'doc: 野蛮人第四张卡名称应与总表一致') "
            "assert(defs.bond_growth_war_god_guard.display_name == '战神之御', 'doc: 战神第二张卡名称应与总表一致') "
            "assert(defs.bond_growth_war_god_power.display_name == '战神之力', 'doc: 战神第三张卡名称应与总表一致') "
            "assert(defs.bond_growth_intelligence.next_ids[1] == 'bond_growth_intelligence_grant', 'doc: 智力分支应继续按文档拆基础卡') "
            "assert(defs.bond_growth_intelligence_grant.parent_id == 'bond_growth_intelligence', 'doc: 赋予智力应接在智力之源后') "
            "assert(defs.bond_growth_intelligence_growth.parent_id == 'bond_growth_intelligence_grant', 'doc: 智力成长应接在赋予智力后') "
            "assert(defs.bond_growth_intelligence_amp.parent_id == 'bond_growth_intelligence_growth', 'doc: 智力增幅应接在智力成长后') "
            "assert(defs.bond_growth_archmage.parent_id == 'bond_growth_intelligence_amp', 'doc: 秘法师应在基础智力四张卡后开启') "
            "assert(defs.bond_growth_archmage.next_ids[1] == 'bond_growth_archmage_sage', 'doc: 秘法师应继续按文档拆卡') "
            "assert(defs.bond_growth_spell_god.parent_id == 'bond_growth_archmage_burst', 'doc: 法神应在秘法师四张卡后开启') "
            "assert(defs.bond_growth_spell_god.next_ids[1] == 'bond_growth_spell_god_mana', 'doc: 法神应继续按文档拆卡') "
            "assert(defs.bond_growth_intelligence_grant.display_name == '赋予智力', 'doc: 智力第二张卡名称应与总表一致') "
            "assert(defs.bond_growth_intelligence_growth.display_name == '智力成长', 'doc: 智力第三张卡名称应与总表一致') "
            "assert(defs.bond_growth_intelligence_amp.display_name == '智力增幅', 'doc: 智力第四张卡名称应与总表一致') "
            "assert(defs.bond_growth_archmage_sage.display_name == '贤者', 'doc: 秘法师第二张卡名称应与总表一致') "
            "assert(defs.bond_growth_archmage_quick_cast.display_name == '快速施法', 'doc: 秘法师第三张卡名称应与总表一致') "
            "assert(defs.bond_growth_archmage_burst.display_name == '魔能爆发', 'doc: 秘法师第四张卡名称应与总表一致') "
            "assert(defs.bond_growth_spell_god_mana.display_name == '旷世法力', 'doc: 法神第二张卡名称应与总表一致') "
            "assert(defs.bond_growth_spell_god_element.display_name == '元素之力', 'doc: 法神第三张卡名称应与总表一致') "
            "assert(string.find(defs.bond_growth_demon_hunter.desc.advanced, '每进化1次', 1, true) ~= nil and string.find(defs.bond_growth_demon_hunter.desc.advanced, '敏捷增幅+2%', 1, true) ~= nil and string.find(defs.bond_growth_demon_hunter.desc.advanced, '继续补齐', 1, true) == nil, '猎魔人套装文案应同步总表正式效果') "
            "assert(string.find(defs.bond_growth_demon_hunter_heartseeker.desc.advanced, '每进化1次', 1, true) ~= nil and string.find(defs.bond_growth_demon_hunter_heartseeker.desc.advanced, '继续补齐', 1, true) == nil, '猎魔人中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_growth_bow_god.desc.advanced, '最终敏捷+5%', 1, true) ~= nil and string.find(defs.bond_growth_bow_god.desc.advanced, '每点敏捷额外提供0.1攻击力', 1, true) ~= nil and string.find(defs.bond_growth_bow_god.desc.advanced, '继续补齐', 1, true) == nil, '弓神套装文案应同步总表正式效果') "
            "assert(string.find(defs.bond_growth_bow_god_piercing.desc.advanced, '最终敏捷', 1, true) ~= nil and string.find(defs.bond_growth_bow_god_piercing.desc.advanced, '继续补齐', 1, true) == nil, '弓神中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_growth_barbarian.desc.advanced, '每进化1次', 1, true) ~= nil and string.find(defs.bond_growth_barbarian.desc.advanced, '力量增幅+2%', 1, true) ~= nil and string.find(defs.bond_growth_barbarian.desc.advanced, '继续补齐', 1, true) == nil, '野蛮人套装文案应同步总表正式效果') "
            "assert(string.find(defs.bond_growth_barbarian_steel.desc.advanced, '每进化1次', 1, true) ~= nil and string.find(defs.bond_growth_barbarian_steel.desc.advanced, '继续补齐', 1, true) == nil, '野蛮人中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_growth_war_god.desc.advanced, '最终力量+5%', 1, true) ~= nil and string.find(defs.bond_growth_war_god.desc.advanced, '每点力量额外提供0.1攻击力', 1, true) ~= nil and string.find(defs.bond_growth_war_god.desc.advanced, '继续补齐', 1, true) == nil, '战神套装文案应同步总表正式效果') "
            "assert(string.find(defs.bond_growth_war_god_guard.desc.advanced, '最终力量', 1, true) ~= nil and string.find(defs.bond_growth_war_god_guard.desc.advanced, '继续补齐', 1, true) == nil, '战神中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_growth_archmage.desc.advanced, '每进化1次', 1, true) ~= nil and string.find(defs.bond_growth_archmage.desc.advanced, '智力增幅+2%', 1, true) ~= nil and string.find(defs.bond_growth_archmage.desc.advanced, '继续补齐', 1, true) == nil, '秘法师套装文案应同步总表正式效果') "
            "assert(string.find(defs.bond_growth_archmage_sage.desc.advanced, '每进化1次', 1, true) ~= nil and string.find(defs.bond_growth_archmage_sage.desc.advanced, '继续补齐', 1, true) == nil, '秘法师中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_growth_spell_god.desc.advanced, '最终智力+5%', 1, true) ~= nil and string.find(defs.bond_growth_spell_god.desc.advanced, '每点智力额外提供0.1攻击力', 1, true) ~= nil and string.find(defs.bond_growth_spell_god.desc.advanced, '继续补齐', 1, true) == nil, '法神套装文案应同步总表正式效果') "
            "assert(string.find(defs.bond_growth_spell_god_mana.desc.advanced, '最终智力', 1, true) ~= nil and string.find(defs.bond_growth_spell_god_mana.desc.advanced, '继续补齐', 1, true) == nil, '法神中间节点也应展示正式套装效果') "
            "assert(defs.bond_magic_core.display_name == '法术') "
            "assert(defs.bond_archery_core.display_name == '箭术') "
            "assert(defs.bond_critical_core.display_name == '暴击') "
            "assert(string.find(defs.bond_magic_core.desc.single, '法术威力', 1, true) ~= nil and string.find(defs.bond_magic_core.desc.single, '法师奥义', 1, true) == nil, 'doc: 法术根节点只应展示第一张基础法术卡') "
            "assert(string.find(defs.bond_archery_core.desc.single, '箭矢弹射', 1, true) ~= nil and string.find(defs.bond_archery_core.desc.single, '射手姿态', 1, true) == nil, 'doc: 箭术根节点只应展示第一张基础箭术卡') "
            "assert(string.find(defs.bond_critical_core.desc.single, '暴击强化', 1, true) ~= nil and string.find(defs.bond_critical_core.desc.single, '暴伤强化', 1, true) == nil, 'doc: 暴击根节点只应展示第一张基础暴击卡') "
            "assert(string.find(defs.bond_growth_core_agility_up.desc.advanced, '每秒木材+0.3', 1, true) ~= nil and string.find(defs.bond_growth_core_agility_up.desc.advanced, '继续补齐', 1, true) == nil, '成长基础中间节点应展示正式套装效果') "
            "assert(string.find(defs.bond_body_core_momentum.desc.advanced, '斗气场域', 1, true) ~= nil and string.find(defs.bond_body_core_momentum.desc.advanced, '继续补齐', 1, true) == nil, '体术基础中间节点应展示正式套装效果') "
            "assert(string.find(defs.bond_economy_core_exp.desc.advanced, '每秒木材+0.5', 1, true) ~= nil and string.find(defs.bond_economy_core_exp.desc.advanced, '继续补齐', 1, true) == nil, '经济基础中间节点应展示正式套装效果') "
            "assert(string.find(defs.bond_magic_core_amp.desc.advanced, '魔爆术', 1, true) ~= nil and string.find(defs.bond_magic_core_amp.desc.advanced, '继续补齐', 1, true) == nil, '法术基础中间节点应展示正式套装效果') "
            "assert(string.find(defs.bond_archery_core_burst.desc.advanced, '穿云箭', 1, true) ~= nil and string.find(defs.bond_archery_core_burst.desc.advanced, '继续补齐', 1, true) == nil, '箭术基础中间节点应展示正式套装效果') "
            "assert(string.find(defs.bond_growth_agility.desc.advanced, '杀敌敏捷+0.1', 1, true) ~= nil and string.find(defs.bond_growth_agility.desc.advanced, '继续补齐', 1, true) == nil, '基础敏捷前段节点应展示正式套装效果') "
            "assert(string.find(defs.bond_growth_strength.desc.advanced, '杀敌力量+0.1', 1, true) ~= nil and string.find(defs.bond_growth_strength.desc.advanced, '继续补齐', 1, true) == nil, '基础力量前段节点应展示正式套装效果') "
            "assert(string.find(defs.bond_growth_intelligence.desc.advanced, '杀敌智力+0.1', 1, true) ~= nil and string.find(defs.bond_growth_intelligence.desc.advanced, '继续补齐', 1, true) == nil, '基础智力前段节点应展示正式套装效果') "
            "assert(defs.bond_economy_core.display_name == '经济') "
            "assert(defs.bond_body_core.display_name == '体术') "
            "assert(defs.bond_critical_deadly.display_name == '致命') "
            "assert(defs.bond_critical_core.next_ids[1] == 'bond_critical_core_damage', 'xmind: 暴击应先接暴伤强化') "
            "assert(defs.bond_critical_deadly.parent_id == 'bond_critical_core_damage', 'xmind: 致命应接在暴伤强化后面') "
            "assert(defs.bond_critical_deadly.next_ids[1] == 'bond_critical_deadly_magic', 'doc: 致命应拆成物/魔两张卡') "
            "assert(defs.bond_critical_cannon.parent_id == 'bond_critical_deadly_magic', 'doc: 大炮应在致命两张卡后开启') "
            "assert(defs.bond_critical_cannon.next_ids[1] == 'bond_critical_cannon_attack', 'doc: 大炮应拆成致命魔法和致命攻击两张卡') "
            "assert(defs.bond_critical_deadly_magic.display_name == '暴击转化-魔', 'doc: 致命第二张卡名称应与总表一致') "
            "assert(defs.bond_critical_cannon_attack.display_name == '致命攻击', 'doc: 大炮第二张卡名称应与总表一致') "
            "assert(defs.bond_archery_multishot.display_name == '多重箭') "
            "assert(defs.bond_archery_core.next_ids[1] == 'bond_archery_core_burst', 'xmind: 箭术应先接箭矢扩散') "
            "assert(defs.bond_archery_core_stance.parent_id == 'bond_archery_core_burst', 'xmind: 射手姿态应接在箭矢扩散后面') "
            "assert(defs.bond_archery_barrage.parent_id == 'bond_archery_core_stance', 'xmind: 广射应接在射手姿态后面') "
            "assert(defs.bond_archery_rapid.parent_id == 'bond_archery_core_stance', 'xmind: 速攻应接在射手姿态后面') "
            "assert(defs.bond_archery_shooting.parent_id == 'bond_archery_core_stance', 'xmind: 射术应接在射手姿态后面') "
            "assert(defs.bond_archery_rapid.next_ids[1] == 'bond_archery_rapid_swiftness', 'doc: 速攻应至少有第二张卡，不能单卡成套') "
            "assert(defs.bond_archery_barrage.next_ids[1] == 'bond_archery_barrage_moon_blade', 'doc: 广射后应先接弹射之刃，再到月刃套装') "
            "assert(defs.bond_archery_shooting.next_ids[1] == 'bond_archery_shooting_edge', 'doc: 射术应拆成穿云重弩和穿云箭锋两张卡') "
            "assert(defs.bond_archery_moon_blade.next_ids[1] == 'bond_archery_moon_blessing', 'doc: 月刃应拆成弹射之刃和月之祝福两张卡') "
            "assert(defs.bond_archery_multishot.next_ids[1] == 'bond_archery_multishot_volley', 'doc: 多重箭应拆成多重威力和多重齐发两张卡') "
            "assert(defs.bond_archery_barrage_moon_blade.display_name == '超远射击', 'doc: 第二张广射卡名称应与总表一致') "
            "assert(string.find(defs.bond_archery_barrage_moon_blade.desc.single, '攻击范围+150', 1, true) ~= nil, 'doc: 第二张广射卡文案应与总表一致') "
            "assert(defs.bond_archery_rapid_swiftness.display_name == '迅捷', 'doc: 速攻中间卡名称应与总表一致') "
            "assert(defs.bond_archery_rapid_agile.display_name == '灵敏', 'doc: 速攻终卡名称应与总表一致') "
            "assert(defs.bond_archery_shooting_edge.display_name == '穿云箭锋', 'doc: 射术第二张卡名称应与总表一致') "
            "assert(defs.bond_archery_moon_blessing.display_name == '月之祝福', 'doc: 月刃第二张卡名称应与总表一致') "
            "assert(defs.bond_archery_multishot_volley.display_name == '多重齐发', 'doc: 多重箭第二张卡名称应与总表一致') "
            "assert(string.find(defs.bond_archery_barrage.desc.single, '射击威力', 1, true) ~= nil and string.find(defs.bond_archery_barrage.desc.single, '超远射击', 1, true) == nil, 'doc: 广射起始节点只应展示第一张卡') "
            "assert(string.find(defs.bond_archery_rapid.desc.single, '疾风', 1, true) ~= nil and string.find(defs.bond_archery_rapid.desc.single, '迅捷', 1, true) == nil, 'doc: 速攻起始节点只应展示第一张卡') "
            "assert(defs.bond_magic_elementalist.display_name == '元素师') "
            "assert(defs.bond_magic_core.next_ids[1] == 'bond_magic_core_amp', 'xmind: 法术应先接法术增幅') "
            "assert(defs.bond_magic_core_essence.parent_id == 'bond_magic_core_amp', 'xmind: 法师奥义应接在法术增幅后面') "
            "assert(defs.bond_magic_arcane_power.parent_id == 'bond_magic_core_essence', 'xmind: 魔能应接在法师奥义后面') "
            "assert(defs.bond_magic_trick.parent_id == 'bond_magic_core_essence', 'xmind: 魔术应接在法师奥义后面') "
            "assert(defs.bond_magic_haste.parent_id == 'bond_magic_core_essence', 'xmind: 急速应接在法师奥义后面') "
            "assert(defs.bond_magic_elementalist.parent_id == 'bond_magic_haste_charge', 'xmind: 元素师应接在急速后面') "
            "assert(defs.bond_magic_mage.parent_id == 'bond_magic_haste_charge', 'xmind: 魔法师应接在急速后面') "
            "assert(defs.bond_magic_arcane_power.next_ids[1] == 'bond_magic_arcane_power_staff', 'doc: 魔能应至少拆成两张卡') "
            "assert(defs.bond_magic_trick.next_ids[1] == 'bond_magic_trick_mastery', 'doc: 魔术应至少拆成两张卡') "
            "assert(defs.bond_magic_elementalist.next_ids[1] == 'bond_magic_elementalist_storm', 'doc: 元素师应按文档拆成三张卡') "
            "assert(defs.bond_magic_mage.next_ids[1] == 'bond_magic_mage_flame', 'doc: 魔法师应按文档拆成三张卡') "
            "assert(defs.bond_magic_mage_flame.display_name == '火焰魔法', 'doc: 魔法师第二张卡名称应与总表一致') "
            "assert(defs.bond_magic_mage_frost.display_name == '寒冰魔法', 'doc: 魔法师第三张卡名称应与总表一致') "
            "assert(defs.bond_magic_arcane_power_staff.display_name == '魔法权杖', 'doc: 魔能分支补卡名称应与总表一致') "
            "assert(defs.bond_magic_trick_mastery.display_name == '魔爆掌握', 'doc: 魔术分支补卡名称应与总表一致') "
            "assert(defs.bond_magic_haste_cooldown.display_name == '冷缩', 'doc: 急速第二张卡名称应与总表一致') "
            "assert(defs.bond_magic_haste_charge.display_name == '充能', 'doc: 急速第三张卡名称应与总表一致') "
            "assert(defs.bond_magic_elementalist_storm.display_name == '风暴元素', 'doc: 元素师第二张卡名称应与总表一致') "
            "assert(defs.bond_magic_elementalist_lightning.display_name == '闪电元素', 'doc: 元素师第三张卡名称应与总表一致') "
            "assert(string.find(defs.bond_magic_mage.desc.single, '奥术魔法', 1, true) ~= nil and string.find(defs.bond_magic_mage.desc.single, '火焰魔法', 1, true) == nil, 'doc: 魔法师起始节点只应展示第一张卡') "
            "assert(string.find(defs.bond_magic_arcane_power.desc.single, '魔法外衣', 1, true) ~= nil and string.find(defs.bond_magic_arcane_power.desc.single, '魔法权杖', 1, true) == nil, 'doc: 魔能起始节点只应展示第一张卡') "
            "assert(string.find(defs.bond_magic_trick.desc.single, '魔爆能量', 1, true) ~= nil and string.find(defs.bond_magic_trick.desc.single, '魔爆掌握', 1, true) == nil, 'doc: 魔术起始节点只应展示第一张卡') "
            "assert(string.find(defs.bond_magic_haste.desc.single, '灵智', 1, true) ~= nil and string.find(defs.bond_magic_haste.desc.single, '冷缩', 1, true) == nil, 'doc: 急速起始节点只应展示第一张卡') "
            "assert(string.find(defs.bond_magic_elementalist.desc.single, '大地元素', 1, true) ~= nil and string.find(defs.bond_magic_elementalist.desc.single, '风暴元素', 1, true) == nil, 'doc: 元素师起始节点只应展示第一张卡') "
            "assert(string.find(defs.bond_magic_mage.desc.single, '奥术魔法', 1, true) ~= nil, '魔法师节点应同步总表中的卡牌描述') "
            "assert(string.find(defs.bond_magic_mage.desc.advanced, '魔法互通', 1, true) ~= nil, '魔法师节点应同步总表中的套装效果') "
            "assert(defs.bond_economy_greed.display_name == '贪婪') "
            "assert(defs.bond_economy_core.next_ids[1] == 'bond_economy_core_exp', 'xmind: 经济应先接杀敌经验') "
            "assert(defs.bond_economy_core_reward.parent_id == 'bond_economy_core_exp', 'xmind: 杀敌加成应接在杀敌经验后面') "
            "assert(defs.bond_economy_greed.parent_id == 'bond_economy_core_reward', 'xmind: 贪婪应接在基础经济链完成后') "
            "assert(defs.bond_economy_greed.next_ids[1] == 'bond_economy_greed_coin', 'doc: 贪婪应按文档拆成三张核心卡') "
            "assert(defs.bond_economy_challenge.next_ids[1] == 'bond_economy_challenge_exp_hunter', 'doc: 挑战应按文档拆成三张猎人卡') "
            "assert(defs.bond_economy_greed_coin.display_name == '贪欲金币', 'doc: 贪婪第二张卡名称应与总表一致') "
            "assert(defs.bond_economy_greed_key.display_name == '贪欲钥匙', 'doc: 贪婪第三张卡名称应与总表一致') "
            "assert(defs.bond_economy_challenge_exp_hunter.display_name == '经验猎人', 'doc: 挑战第二张卡名称应与总表一致') "
            "assert(defs.bond_economy_challenge_gold_hunter.display_name == '金币猎人', 'doc: 挑战第三张卡名称应与总表一致') "
            "assert(string.find(defs.bond_economy_greed.desc.single, '贪婪之刃', 1, true) ~= nil and string.find(defs.bond_economy_greed.desc.single, '贪欲金币', 1, true) == nil, 'doc: 贪婪起始节点只应展示第一张卡') "
            "assert(string.find(defs.bond_economy_challenge.desc.single, '木材猎人', 1, true) ~= nil and string.find(defs.bond_economy_challenge.desc.single, '经验猎人', 1, true) == nil, 'doc: 挑战起始节点只应展示第一张卡') "
            "assert(string.find(defs.bond_economy_greed_coin.desc.single, '6000', 1, true) ~= nil and string.find(defs.bond_economy_greed_key.desc.single, '150', 1, true) ~= nil, '贪婪后续节点应同步文档中的金币和木材文案') "
            "assert(string.find(defs.bond_economy_greed.desc.advanced, '吞噬4张', 1, true) ~= nil or string.find(defs.bond_economy_greed.desc.advanced, '随机吞噬4张', 1, true) ~= nil, '贪婪进阶文案应同步吞噬4张描述') "
            "assert(defs.bond_economy_challenge.display_name == '挑战') "
            "assert(defs.bond_economy_challenge.parent_id == 'bond_economy_core_reward', 'xmind: 挑战应接在基础经济链完成后') "
            "assert(string.find(defs.bond_economy_challenge.desc.single, '猎人', 1, true) ~= nil, '挑战节点应同步文档中的猎人卡牌文案') "
            "assert(string.find(defs.bond_economy_challenge.desc.advanced, '挑战伤害', 1, true) == nil, '挑战节点文案不应再宣称未实现的挑战伤害效果') "
            "assert(defs.bond_body_life_blessing.display_name == '生命祝福', 'doc: 生命第二张卡名称应与总表一致') "
            "assert(defs.bond_body_life_power.display_name == '生命之力', 'doc: 生命第三张卡名称应与总表一致') "
            "assert(string.find(defs.bond_body_life_power.desc.advanced, '生命增幅', 1, true) ~= nil, '生命终卡应同步总表中的生命套装效果') "
            "assert(defs.bond_body_core.next_ids[1] == 'bond_body_core_momentum', 'xmind: 体术应先接气势') "
            "assert(defs.bond_body_core_vitality.parent_id == 'bond_body_core_momentum', 'xmind: 生命值100应接在气势后面') "
            "assert(defs.bond_body_life.parent_id == 'bond_body_core_vitality', 'doc: 生命应是体术完成后的独立分支') "
            "assert(defs.bond_body_life.next_ids[1] == 'bond_body_life_blessing', 'doc: 生命分支应先接生命祝福') "
            "assert(defs.bond_body_life_blessing.parent_id == 'bond_body_life', 'doc: 生命祝福应接在生命后面') "
            "assert(defs.bond_body_life_power.parent_id == 'bond_body_life_blessing', 'doc: 生命之力应接在生命祝福后面') "
            "assert(defs.bond_body_blood_oath.parent_id == 'bond_body_core_vitality', 'doc: 血誓应是体术完成后的独立分支') "
            "assert(defs.bond_body_blood_oath.next_ids[1] == 'bond_body_blood_oath_blade', 'doc: 血誓分支应按血契/血刃/血矛拆开') "
            "assert(defs.bond_body_blood_oath_blade.parent_id == 'bond_body_blood_oath', 'doc: 血刃应接在血契后面') "
            "assert(defs.bond_body_blood_oath_spear.parent_id == 'bond_body_blood_oath_blade', 'doc: 血矛应接在血刃后面') "
            "assert(defs.bond_body_blood_demon.parent_id == 'bond_body_core_vitality', 'doc: 血魔应是体术完成后的独立分支') "
            "assert(defs.bond_body_blood_demon.next_ids[1] == 'bond_body_blood_demon_satan', 'doc: 血魔分支应按魔手/撒旦/臂章拆开') "
            "assert(defs.bond_body_blood_demon_satan.parent_id == 'bond_body_blood_demon', 'doc: 撒旦应接在魔手后面') "
            "assert(defs.bond_body_blood_demon_armlet.parent_id == 'bond_body_blood_demon_satan', 'doc: 臂章应接在撒旦后面') "
            "assert(defs.bond_body_tactics.display_name == '战术') "
            "assert(defs.bond_body_tactics.parent_id == 'bond_body_core_vitality', 'xmind: 战术应在基础体术链完成后开启') "
            "assert(defs.bond_body_tactics.next_ids[1] == 'bond_body_tactics_blunt_edge', 'doc: 战术应至少有两张卡') "
            "assert(defs.bond_body_fortress.next_ids[1] == 'bond_body_fortress_hard_armor', 'doc: 固守应按文档先接坚盾/硬甲卡') "
            "assert(defs.bond_body_tactics_blunt_edge.display_name == '挫锋', 'doc: 战术第二张卡名称应与总表一致') "
            "assert(defs.bond_body_fortress_hard_armor.display_name == '硬甲', 'doc: 固守第二张卡名称应与总表一致') "
            "assert(string.find(defs.bond_body_tactics.desc.single, '破甲', 1, true) ~= nil and string.find(defs.bond_body_tactics.desc.single, '挫锋', 1, true) == nil, 'doc: 战术起始节点只应展示第一张卡') "
            "assert(string.find(defs.bond_body_fortress.desc.single, '坚盾', 1, true) ~= nil and string.find(defs.bond_body_fortress.desc.single, '硬甲', 1, true) == nil, 'doc: 固守起始节点只应展示第一张卡') "
            "assert(defs.bond_body_charge_breaker.display_name == '陷阵') "
            "assert(defs.bond_body_charge_breaker.parent_id == 'bond_body_core_vitality', 'doc: 陷阵应是体术完成后的独立分支') "
            "assert(defs.bond_body_charge_breaker.next_ids[1] == 'bond_body_charge_breaker_bloody_battle', 'doc: 陷阵应按奋力抵抗/浴血拼杀拆开') "
            "assert(defs.bond_body_charge_breaker_bloody_battle.display_name == '浴血拼杀', 'doc: 陷阵第二张卡名称应与总表一致') "
            "assert(defs.bond_body_blood_oath_blade.display_name == '血刃', 'doc: 血誓第二张卡名称应与总表一致') "
            "assert(defs.bond_body_blood_oath_spear.display_name == '血矛', 'doc: 血誓第三张卡名称应与总表一致') "
            "assert(string.find(defs.bond_body_blood_oath.desc.single, '每100点生命上限', 1, true) ~= nil or string.find(defs.bond_body_blood_oath.desc.single, '每有100点生命上限', 1, true) ~= nil, '血誓首卡应体现生命上限转属性') "
            "assert(string.find(defs.bond_body_blood_oath_spear.desc.advanced, '生命值 +500', 1, true) ~= nil or string.find(defs.bond_body_blood_oath_spear.desc.advanced, '生命值+500', 1, true) ~= nil, '血誓终卡应体现生命值+500套装结果') "
            "assert(string.find(defs.bond_critical_deadly.desc.single, '物理暴击', 1, true) ~= nil, '致命首卡应体现物理暴击转化语义') "
            "assert(string.find(defs.bond_critical_deadly_magic.desc.single, '魔法暴击', 1, true) ~= nil, '致命第二张卡应体现魔法暴击转化语义') "
            "assert(string.find(defs.bond_critical_cannon.desc.single, '致命魔法', 1, true) ~= nil, '大炮首卡应体现致命魔法条目') "
            "assert(string.find(defs.bond_critical_cannon_attack.desc.single, '致命攻击', 1, true) ~= nil, '大炮第二张卡应体现致命攻击条目') "
            "assert(string.find(defs.bond_archery_barrage_moon_blade.desc.single, '攻击范围', 1, true) ~= nil, '广射后续节点应体现攻击范围成长') "
            "assert(string.find(defs.bond_archery_shooting.desc.single, '穿云箭', 1, true) ~= nil or string.find(defs.bond_archery_shooting.desc.advanced, '穿云箭', 1, true) ~= nil, '射术节点应体现穿云箭语义') "
            "assert(string.find(defs.bond_archery_multishot.desc.single, '多重', 1, true) ~= nil or string.find(defs.bond_archery_multishot.desc.advanced, '多重', 1, true) ~= nil, '多重箭节点应体现多重箭数量或伤害') "
            "assert(string.find(defs.bond_archery_shooting.desc.advanced, '穿云箭所需的攻击次数降低5次', 1, true) ~= nil and string.find(defs.bond_archery_shooting.desc.advanced, '继续补齐', 1, true) == nil, '射术套装文案应同步总表正式效果') "
            "assert(string.find(defs.bond_archery_barrage_moon_blade.desc.advanced, '每有100攻击范围', 1, true) ~= nil and string.find(defs.bond_archery_barrage_moon_blade.desc.advanced, '继续补齐', 1, true) == nil, '广射中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_archery_moon_blade.desc.advanced, '当前弹射次数*50的敏捷', 1, true) ~= nil and string.find(defs.bond_archery_moon_blade.desc.advanced, '继续补齐', 1, true) == nil, '月刃中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_archery_rapid_swiftness.desc.advanced, '攻击有20%的概率', 1, true) ~= nil and string.find(defs.bond_archery_rapid_swiftness.desc.advanced, '继续补齐', 1, true) == nil, '速攻中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_archery_multishot.desc.advanced, '当前多重数量*50的敏捷', 1, true) ~= nil and string.find(defs.bond_archery_multishot.desc.advanced, '继续补齐', 1, true) == nil, '多重箭中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_critical_deadly.desc.advanced, '所有非暴击伤害降低20%', 1, true) ~= nil and string.find(defs.bond_critical_deadly.desc.advanced, '继续补齐', 1, true) == nil, '致命套装文案应同步总表正式效果') "
            "assert(string.find(defs.bond_critical_cannon.desc.advanced, '每溢出2%的物理暴击', 1, true) ~= nil and string.find(defs.bond_critical_cannon.desc.advanced, '继续补齐', 1, true) == nil, '大炮套装文案应同步总表正式效果') "
            "assert(string.find(defs.bond_body_life.desc.advanced, '生命增幅+5%', 1, true) ~= nil and string.find(defs.bond_body_life.desc.advanced, '继续补齐', 1, true) == nil, '生命套装文案应同步总表正式效果') "
            "assert(string.find(defs.bond_body_charge_breaker.desc.advanced, '每击杀200名敌人触发', 1, true) ~= nil and string.find(defs.bond_body_charge_breaker.desc.advanced, '继续补齐', 1, true) == nil, '陷阵套装文案应同步总表正式效果') "
            "assert((string.find(defs.bond_body_blood_oath.desc.advanced, '生命值+500', 1, true) ~= nil or string.find(defs.bond_body_blood_oath.desc.advanced, '生命值 +500', 1, true) ~= nil) and string.find(defs.bond_body_blood_oath.desc.advanced, '继续补齐', 1, true) == nil, '血誓套装文案应同步总表正式效果') "
            "assert(string.find(defs.bond_body_blood_demon.desc.advanced, '每损失35%最大生命值', 1, true) ~= nil and string.find(defs.bond_body_blood_demon.desc.advanced, '继续补齐', 1, true) == nil, '血魔套装文案应同步总表正式效果') "
            "assert(string.find(defs.bond_magic_mage_flame.desc.advanced, '魔法互通', 1, true) ~= nil and string.find(defs.bond_magic_mage_flame.desc.advanced, '继续补齐', 1, true) == nil, '魔法师中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_magic_haste_cooldown.desc.advanced, '立即重置该技能冷却', 1, true) ~= nil and string.find(defs.bond_magic_haste_cooldown.desc.advanced, '继续补齐', 1, true) == nil, '急速中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_magic_elementalist_storm.desc.advanced, '另外2种15%的伤害增幅', 1, true) ~= nil and string.find(defs.bond_magic_elementalist_storm.desc.advanced, '继续补齐', 1, true) == nil, '元素师中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_economy_greed_coin.desc.advanced, '随机吞噬4张', 1, true) ~= nil and string.find(defs.bond_economy_greed_coin.desc.advanced, '继续补齐', 1, true) == nil, '贪婪中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_economy_challenge_exp_hunter.desc.advanced, '挑战伤害+15%', 1, true) == nil and string.find(defs.bond_economy_challenge_exp_hunter.desc.advanced, '继续补齐', 1, true) == nil, '挑战中间节点文案不应再宣称未实现的挑战伤害效果') "
            "assert(string.find(defs.bond_body_life_blessing.desc.advanced, '生命增幅+5%', 1, true) ~= nil and string.find(defs.bond_body_life_blessing.desc.advanced, '继续补齐', 1, true) == nil, '生命中间节点也应展示正式套装效果') "
            "assert((string.find(defs.bond_body_blood_oath_blade.desc.advanced, '生命值+500', 1, true) ~= nil or string.find(defs.bond_body_blood_oath_blade.desc.advanced, '生命值 +500', 1, true) ~= nil) and string.find(defs.bond_body_blood_oath_blade.desc.advanced, '继续补齐', 1, true) == nil, '血誓中间节点也应展示正式套装效果') "
            "assert(string.find(defs.bond_body_blood_demon_satan.desc.advanced, '每损失35%最大生命值', 1, true) ~= nil and string.find(defs.bond_body_blood_demon_satan.desc.advanced, '继续补齐', 1, true) == nil, '血魔中间节点也应展示正式套装效果') "
            "for _, def in ipairs(bond_nodes.list) do "
            "if def.parent_id ~= nil and #(def.next_ids or {}) > 0 then "
            "for _, next_id in ipairs(def.next_ids) do "
            "local next_def = defs[next_id] "
            "local next_name = next_def and next_def.display_name or '' "
            "if next_name ~= '' then "
            "assert(string.find(def.desc.single, next_name .. '：', 1, true) == nil, 'doc: 非根节点起始描述不应直接拼接后续卡牌名 -> ' .. def.id .. ' / ' .. next_id) "
            "end "
            "end "
            "end "
            "end "
            "for _, def in ipairs(bond_nodes.list) do "
            "assert(def.icon ~= nil, 'missing icon for ' .. def.id) "
            "assert(def.editor_skill_id ~= nil, 'missing editor_skill_id for ' .. def.id) "
            "assert(type(def.desc) == 'table', 'missing desc table for ' .. def.id) "
            "assert(type(def.desc.single) == 'string' and def.desc.single ~= '', 'missing single desc for ' .. def.id) "
            "if #(def.next_ids or {}) > 0 then "
            "assert(type(def.desc.advanced) == 'string' and def.desc.advanced ~= '', 'missing advanced desc for ' .. def.id) "
            "end "
            "local ability_file = io.open('maps/EntryMap/editor_table/abilityall/' .. tostring(def.editor_skill_id) .. '.json', 'r') "
            "assert(ability_file ~= nil, 'missing ability json for ' .. def.id) "
            "if ability_file then ability_file:close() end "
            "end "
            "local root_node = assert(bonds.unlock_node(state, 'bond_growth_core')) "
            "assert(root_node.id == 'bond_growth_core') "
            "assert(bonds.unlock_node(state, 'bond_growth_core_agility_up')) "
            "assert(bonds.unlock_node(state, 'bond_growth_core_strength_up')) "
            "assert(bonds.unlock_node(state, 'bond_growth_core_attack_up')) "
            "local node = assert(bonds.unlock_node(state, 'bond_growth_agility')) "
            "assert(node.id == 'bond_growth_agility') "
            "assert((state.resources.wood or 0) == 50, '敏捷节点应在解锁时发放木材 +50') "
            "local slot_text = bonds.build_slot_text(state, 1) "
            "assert(string.find(slot_text, '+100', 1, true) ~= nil, 'slot text should include current effect summary') "
            "local progress_lines = bonds.build_progress_lines(state, 6) "
            "assert(#progress_lines > 0, 'bond progress lines should not be empty') "
            "assert(string.find(progress_lines[1], '4/4', 1, true) ~= nil and string.find(progress_lines[1], '已吞噬完成', 1, true) ~= nil, 'bond progress lines should show completed base-chain progress after root set consumption') "
            "assert(bonds.can_unlock_node(state, 'bond_growth_demon_hunter') == false) "
            "assert(bonds.can_unlock_node(state, 'bond_growth_agility_grant') == true) "
            "local hero = { attrs = { ['最大生命'] = 1000 }, hp = 1000 } "
            "function hero:is_exist() return true end "
            "function hero:get_attr(key) return self.attrs[key] or 0 end "
            "function hero:add_attr(key, delta) self.attrs[key] = (self.attrs[key] or 0) + delta end "
            "function hero:get_hp() return self.hp end "
            "function hero:play_animation() end "
            "state.hero = hero "
            "assert(bonds.unlock_node(state, 'bond_magic_core')) "
            "assert(math.abs(bonds.get_runtime_bonus(state, 'skill_damage_bonus') - 0.05) < 0.0001, '法术根节点应先按文档提供单件基础效果') "
            "assert(bonds.has_route_tag(state, 'auto_spell_burst') == false, '法术根节点未凑齐前不应直接激活套装效果') "
            "assert(bonds.unlock_node(state, 'bond_magic_core_amp')) "
            "assert(bonds.unlock_node(state, 'bond_magic_core_essence')) "
            "assert(bonds.unlock_node(state, 'bond_magic_haste')) "
            "assert(bonds.unlock_node(state, 'bond_magic_haste_cooldown')) "
            "assert(bonds.unlock_node(state, 'bond_magic_haste_charge')) "
            "assert(bonds.unlock_node(state, 'bond_magic_mage')) "
            "assert(bonds.unlock_node(state, 'bond_magic_mage_flame')) "
            "assert(bonds.unlock_node(state, 'bond_magic_mage_frost')) "
            "assert(math.abs(bonds.get_runtime_bonus(state, 'skill_damage_bonus') - 0.20) < 0.0001, '法术基础链与分支应叠加显示为文档单件效果 + 分支效果') "
            "bonds.notify_attack_skill_cast({ STATE = state }, { id = 'arcane_arrow' }, nil) "
            "bonds.update_effects({ STATE = state, y3 = { helper = { tonumber = tonumber } } }, 1) "
            "assert(math.abs(bonds.get_runtime_bonus(state, 'all_damage_bonus') - 0.12) < 0.0001) "
            "assert(state.bond_runtime.arcane_empower_remaining == 2) "
            "bonds.update_effects({ STATE = state, y3 = { helper = { tonumber = tonumber } } }, 2) "
            "assert((bonds.get_runtime_bonus(state, 'all_damage_bonus') or 0) == 0) "
            "assert(state.bond_runtime.arcane_empower_remaining == 0) "
            "old_random = math.random "
            "math.random = function(a, b) if a and b then return a end return 0 end "
            "local root_draw_state = { bond_runtime = bonds.create_runtime(), resources = { wood = 999 }, bond_draw_count = 0 } "
            "assert(bonds.try_draw({ STATE = root_draw_state, message = function() end })) "
            "local root_choice = assert(root_draw_state.bond_runtime.current_choices[1]) "
            "assert(root_choice.node_id == nil and root_choice.group_id == 'body', 'first bond draw should start from group choices before root nodes') "
            "assert(root_choice.display_name == '体术', 'first group choice should use body group label') "
            "assert(root_choice.title_text == '体术 (未开启)', 'group choice title should show unopened status') "
            "assert(root_choice.progress_text == '未开启', 'group choice should expose unopened progress state') "
            "assert(root_choice.subtitle_text == '主链分组', 'group choice subtitle should explain the card type') "
            "assert(root_choice.title_color == 'bond_red', 'bond title should use the configured red title color') "
            "assert(string.find(root_choice.current_text, '解锁：', 1, true) ~= nil, 'group choice body should explain the unlocked routes') "
            "assert(string.find(root_choice.effect_text, '开放[体术]主链根节点', 1, true) ~= nil, 'group choice should describe unlocking the group root chain') "
            "assert(bonds.apply_choice({ STATE = root_draw_state, message = function() end }, 1)) "
            "assert(bonds.can_unlock_node(root_draw_state, 'bond_body_core') == true, 'unlocking body group should expose the body root node first') "
            "local body_root_state = { bond_runtime = bonds.create_runtime(), resources = { wood = 999 }, bond_draw_count = 0 } "
            "body_root_state.bond_runtime.unlocked_group_ids.body = true "
            "body_root_state.bond_runtime.unlocked_group_ids.economy = true "
            "body_root_state.bond_runtime.unlocked_group_ids.magic = true "
            "body_root_state.bond_runtime.unlocked_group_ids.archery = true "
            "body_root_state.bond_runtime.unlocked_group_ids.critical = true "
            "body_root_state.bond_runtime.unlocked_group_ids.growth = true "
            "assert(bonds.try_draw({ STATE = body_root_state, message = function() end })) "
            "local body_root_choice = assert(body_root_state.bond_runtime.current_choices[1]) "
            "assert(body_root_choice.node_id == 'bond_body_core', 'after unlocking body group the first root card should be body core') "
            "assert(body_root_choice.title_text == '体术 (0/3)', 'root choice title should include set progress in the screenshot format') "
            "assert(body_root_choice.progress_text == '', 'bond choice progress should move into the title instead of subtitle') "
            "assert(body_root_choice.subtitle_text == '体术', 'root choice subtitle should show the node name under the icon') "
            "assert(string.find(body_root_choice.current_text, '利刃', 1, true) ~= nil, 'root choice top block should keep the card name') "
            "assert(string.find(body_root_choice.current_text, '斗气场域', 1, true) == nil, 'root choice top block should no longer reuse set-effect text') "
            "assert(string.find(body_root_choice.body_blocks[1].text or '', '利刃：', 1, true) ~= nil, 'root choice body block should include the card name prefix') "
            "assert(string.find(body_root_choice.body_blocks[1].text or '', '攻击力+50', 1, true) ~= nil, 'root choice body block should include the card effect text') "
            "assert(body_root_choice.body_blocks[1].segments ~= nil and #body_root_choice.body_blocks[1].segments > 1, 'root choice value text should carry manual color segments') "
            "assert(body_root_choice.effect_title == '激活[体术]套装效果：', 'root choice should use set-effect title instead of branch preview title') "
            "assert(string.find(body_root_choice.effect_text, '斗气场域', 1, true) ~= nil, 'root choice should show set-effect text instead of follow-up branch names') "
            "assert(body_root_choice.body_blocks[3].segments ~= nil and #body_root_choice.body_blocks[3].segments > 1, 'root choice effect text should carry manual color segments') "
            "assert(bonds.apply_choice({ STATE = body_root_state, message = function() end }, 1)) "
            "assert(bonds.has_route_tag(body_root_state, 'auto_fighting_spirit') == false, 'unlocking only the root card should not immediately activate the body set effect') "
            "assert(bonds.can_unlock_node(body_root_state, 'bond_body_core_momentum') == true, 'unlocking body root should first expose remaining base body cards') "
            "local candidate_defs = bonds.get_candidate_nodes(body_root_state) "
            "local momentum_index = nil "
            "for i, def in ipairs(candidate_defs) do "
            "if def.id == 'bond_body_core_momentum' then momentum_index = i break end "
            "end "
            "assert(momentum_index ~= nil, 'body root unlock should expose momentum candidate') "
            "local old_random_for_tactics = math.random "
            "math.random = function(a, b) if a and b then return a end return 0.999 end "
            "assert(bonds.try_draw({ STATE = body_root_state, message = function() end })) "
            "math.random = old_random_for_tactics "
            "local momentum_choice = assert(body_root_state.bond_runtime.current_choices[1]) "
            "assert(momentum_choice.node_id == 'bond_body_core_momentum', 'forced body draw should pick bond_body_core_momentum first') "
            "assert(string.find(momentum_choice.title_text or '', '体术', 1, true) ~= nil, 'momentum choice title should show the set name above the icon') "
            "assert(string.find(momentum_choice.title_text or '', '1/3', 1, true) ~= nil, 'momentum choice title should show set progress above the icon') "
            "assert((momentum_choice.subtitle_text or '') == '气势', 'momentum choice subtitle should show the node name under the icon') "
            "assert(bonds.unlock_node(body_root_state, 'bond_body_core_momentum')) "
            "assert(bonds.has_route_tag(body_root_state, 'auto_fighting_spirit') == false, 'body set should still require enough cards after picking only one base card') "
            "assert(bonds.unlock_node(body_root_state, 'bond_body_core_vitality')) "
            "assert(bonds.has_route_tag(body_root_state, 'auto_fighting_spirit') == true, 'body set should activate after reaching the doc-based required count') "
            "assert(bonds.can_unlock_node(body_root_state, 'bond_body_life') == true and bonds.can_unlock_node(body_root_state, 'bond_body_tactics') == true and bonds.can_unlock_node(body_root_state, 'bond_body_fortress') == true, 'completing the base body set should expose follow-up body branches') "
            "math.random = old_random "
            "local growth_draw_state = { bond_runtime = bonds.create_runtime(), resources = { wood = 999 }, bond_draw_count = 0 } "
            "assert(bonds.unlock_node(growth_draw_state, 'bond_growth_core')) "
            "assert(bonds.can_unlock_node(growth_draw_state, 'bond_growth_agility') == false, 'growth root should not expose branch before base chain is complete') "
            "assert(bonds.can_unlock_node(growth_draw_state, 'bond_growth_core_agility_up') == true, 'growth root should first expose base growth card') "
            "assert(bonds.unlock_node(growth_draw_state, 'bond_growth_core_agility_up')) "
            "assert(bonds.unlock_node(growth_draw_state, 'bond_growth_core_strength_up')) "
            "assert(bonds.unlock_node(growth_draw_state, 'bond_growth_core_attack_up')) "
            "assert(growth_draw_state.bond_runtime.completed_root_sets['bond_growth_core'] == true, 'growth base chain should complete the root set') "
            "assert(bonds.can_unlock_node(growth_draw_state, 'bond_growth_agility') == true, 'completing the base growth set should expose agility branch') "
            "local archery_state = { bond_runtime = bonds.create_runtime(), resources = { wood = 999 }, bond_draw_count = 0 } "
            "assert(bonds.unlock_node(archery_state, 'bond_archery_core')) "
            "assert(bonds.unlock_node(archery_state, 'bond_archery_core_burst')) "
            "assert(bonds.unlock_node(archery_state, 'bond_archery_core_stance')) "
            "assert(archery_state.bond_runtime.completed_root_sets['bond_archery_core'] == true, 'archery base chain should complete the root set') "
            "assert(bonds.can_unlock_node(archery_state, 'bond_archery_barrage') == true, 'completing the base archery set should expose archery branches') "
            "local magic_draw_state = { bond_runtime = bonds.create_runtime(), resources = { wood = 999 }, bond_draw_count = 0 } "
            "assert(bonds.unlock_node(magic_draw_state, 'bond_magic_core')) "
            "assert(bonds.unlock_node(magic_draw_state, 'bond_magic_core_amp')) "
            "assert(bonds.unlock_node(magic_draw_state, 'bond_magic_core_essence')) "
            "assert(magic_draw_state.bond_runtime.completed_root_sets['bond_magic_core'] == true, 'magic base chain should complete the root set') "
            "assert(bonds.can_unlock_node(magic_draw_state, 'bond_magic_haste') == true, 'completing the base magic set should expose magic branches') "
            "local consume_state = { bond_runtime = bonds.create_runtime(), resources = { wood = 0 } } "
            "assert(bonds.unlock_node(consume_state, 'bond_body_core')) "
            "assert(bonds.unlock_node(consume_state, 'bond_body_core_momentum')) "
            "assert(bonds.unlock_node(consume_state, 'bond_body_core_vitality')) "
            "assert(consume_state.bond_runtime.completed_root_sets['bond_body_core'] == true, 'completed root set should be marked exactly once') "
            "assert(consume_state.bond_runtime.consumed_root_sets['bond_body_core'] == true, 'current root sets should default to consume_all') "
            "assert((consume_state.bond_runtime.completed_root_set_modes['bond_body_core'] or '') == 'consume_all', 'completed root set should record its completion mode') "
            "assert(bonds.has_route_tag(consume_state, 'auto_fighting_spirit') == true, 'consumed root set should keep its set route tag active') "
            "assert((bonds.get_total_attr_bonuses(consume_state)['生命'] or 0) >= 100, 'consumed root set should keep its persisted base attr bonuses') "
            "assert((bonds.get_total_attr_bonuses(consume_state)['力量'] or 0) >= 50, 'consumed root set should keep its persisted set attr bonuses') "
            "local consumed_slots = table.concat(consume_state.bond_runtime.owned_node_order, ',') "
            "assert(string.find(consumed_slots, 'bond_body_core', 1, true) == nil, 'consumed root nodes should leave the owned slot list') "
            "assert(string.find(consumed_slots, 'bond_body_core_momentum', 1, true) == nil, 'consumed root chain nodes should leave the owned slot list') "
            "assert(string.find(consumed_slots, 'bond_body_core_vitality', 1, true) == nil, 'consumed root chain nodes should leave the owned slot list') "
            "local economy_state = { bond_runtime = bonds.create_runtime(), resources = { wood = 0 } } "
            "assert(bonds.unlock_node(economy_state, 'bond_economy_core')) "
            "assert(math.abs(bonds.get_runtime_bonus(economy_state, 'kill_gold_ratio') - 0.10) < 0.0001, '经济根节点应先给单件金币收益') "
            "assert((bonds.get_runtime_bonus(economy_state, 'gold_per_sec_bonus') or 0) == 0, '经济根节点未凑齐前不应直接给套装每秒金币') "
            "assert(bonds.can_unlock_node(economy_state, 'bond_economy_greed') == false, '经济分支应在基础经济链完成后开启') "
            "local critical_state = { bond_runtime = bonds.create_runtime(), resources = { wood = 0 } } "
            "assert(bonds.unlock_node(critical_state, 'bond_critical_core')) "
            "local critical_bonus = bonds.get_total_attr_bonuses(critical_state) "
            "assert((critical_bonus['物理暴击'] or 0) == 3 and (critical_bonus['魔法暴击'] or 0) == 3, '暴击根节点应显示并提供文档中的单件暴击数值') "
            "assert(bonds.can_unlock_node(critical_state, 'bond_critical_deadly') == false, '致命应在暴伤强化完成后开启') "
            "local growth_state = { bond_runtime = bonds.create_runtime(), resources = { wood = 0 } } "
            "assert(bonds.unlock_node(growth_state, 'bond_growth_core')) "
            "assert(math.abs(bonds.get_runtime_bonus(growth_state, 'intelligence_per_second') - 0.5) < 0.0001, '成长根节点应先给文档单件成长属性') "
            "assert((bonds.get_runtime_bonus(growth_state, 'wood_per_sec_bonus') or 0) == 0, '成长根节点未凑齐前不应直接给套装资源收益') "
            "local group_entry_state = { bond_runtime = bonds.create_runtime(), resources = { wood = 0 } } "
            "local group_entries = bonds.get_available_group_choice_entries(group_entry_state) "
            "assert(#group_entries == 6, 'group choice entries should expose all unopened groups') "
            "local draw_state = { bond_runtime = bonds.create_runtime(), resources = { wood = 999 }, bond_draw_count = 0 } "
            "old_random = math.random "
            "math.random = function(_) return 1 end "
            "assert(bonds.try_draw({ STATE = draw_state, message = function() end })) "
            "local saw_group_choice = false "
            "for _, choice in ipairs(draw_state.bond_runtime.current_choices or {}) do "
            "  if choice.group_id and not choice.node_id then saw_group_choice = true end "
            "end "
            "assert(saw_group_choice == true, 'bond draw should include group choices when include_group_choices is enabled') "
            "assert(bonds.apply_choice({ STATE = draw_state, message = function() end }, 1)) "
            "assert(bonds.try_draw({ STATE = draw_state, message = function() end })) "
            "local draw_choice = assert(draw_state.bond_runtime.current_choices[1]) "
            "assert(type(draw_choice.current_text) == 'string' and draw_choice.current_text ~= '') "
            "assert(type(draw_choice.value_text) == 'string' and draw_choice.value_text ~= '') "
            "assert(type(draw_choice.effect_title) == 'string') "
            "assert(type(draw_choice.effect_text) == 'string' and draw_choice.effect_text ~= '') "
            "assert((draw_choice.next_text or '') == '', 'choice next text should stay hidden in UI/runtime previews') "
            "local preview_text = bonds.build_choice_preview_text(1, draw_choice) "
            "assert(string.find(preview_text, '1.', 1, true) ~= nil, 'choice preview should keep index prefix') "
            "assert(string.find(preview_text, ' | ', 1, true) ~= nil, 'choice preview should include compact summary') "
            "math.random = old_random "
            "local colorizer = require('ui.choice_panel_text_colorizer') "
            "local highlight_lines = colorizer.build_highlight_lines('每秒对周围1200范围\\n内的敌人造成60%力量自适应伤害', 'dim', 'auto') "
            "assert(#highlight_lines == 2, 'auto colorizer should preserve source line count') "
            "assert(highlight_lines[1][2].text == '1200' and highlight_lines[1][2].color == 'cyan', 'number highlights should use cyan') "
            "assert(highlight_lines[2][2].text == '60%' and highlight_lines[2][2].color == 'cyan', 'percentage highlights should use cyan') "
            "assert(highlight_lines[2][3].text == '力量' and highlight_lines[2][3].color == 'green', 'attribute keywords should use green') "
            "assert(highlight_lines[2][4].text == '自适应伤害' and highlight_lines[2][4].color == 'green', 'damage keywords should use green') "
            "local debug_tools = require('runtime.debug_tools') "
            "local debug_api = debug_tools.create({ "
            "STATE = { resources = { gold = 12.5, wood = 34.2 }, skill_points = 2.8, challenge_charges = 1.6, total_enemy_alive = 7.4, active_wave = nil }, "
            "CONFIG = { challenge_rules = { max_charges = 3.2 }, areas = {}, points = {} }, "
            "y3 = { fs = { save = function() end } }, "
            "message = function() end, "
            "round_number = function(v) return math.floor((tonumber(v) or 0) + 0.5) end, "
            "make_point = function() return nil end, "
            "develop_command = function() end, "
            "effect_debug_system = {}, "
            "get_hero_level = function() return 4.7 end, "
            "get_active_challenge_count = function() return 1.2 end, "
            "get_current_wave = function() return nil end "
            "}) "
            "local gm_text = debug_api.get_gm_panel_status_text() "
            "assert(type(gm_text) == 'string' and string.find(gm_text, '5', 1, true) ~= nil and string.find(gm_text, '7', 1, true) ~= nil, 'gm status text should round non-integer values safely') "
            "local attack_skills = require('runtime.attack_skills') "
            "local target = {} "
            "local attack_state = { hero = { is_exist = function() return true end, get_point = function() return {} end }, attack_skill_state = { slots = { [1] = nil, [2] = { id = 'test_spell', cast_range = 600, range_bonus = 0, repeat_count = 1, base_cooldown = 1, cooldown_reduction = 0, cooldown_remaining = 0 } } } } "
            "local notify_count = 0 "
            "local old_random = math.random "
            "math.random = function() return 0 end "
            "local selector = {} "
            "function selector:is_enemy(_) return self end "
            "function selector:in_range(_, _) return self end "
            "function selector:sort_type(_) return self end "
            "function selector:pick() return { target } end "
            "local sys = attack_skills.create({ "
            "STATE = attack_state, "
            "y3 = { selector = { create = function() return selector end }, helper = { tonumber = tonumber } }, "
            "round_number = function(v) return math.floor((v or 0) + 0.5) end, "
            "message = function() end, "
            "ATTACK_SKILL_DEFS = { basic_attack = { base_range = 250, damage_type = '物理' } }, "
            "ATTACK_SKILL_VFX = {}, "
            "get_player = function() return {} end, "
            "get_hero_point = function() return {} end, "
            "get_bond_runtime_bonus = function(key) if key == 'skill_echo_chance' then return 1 end return 0 end, "
            "is_bond_active = function() return false end, "
            "is_active_enemy = function(unit) return unit == target end, "
            "create_attack_skill_instance = function() return {} end, "
            "deal_skill_damage = function() end, "
            "get_damage_bonus_multiplier = function() return 1 end, "
            "get_enemies_in_range = function() return {} end, "
            "try_trigger_hunter_first_hit = function() end, "
            "notify_bond_attack_skill_cast = function() notify_count = notify_count + 1 end, "
            "notify_auto_active_basic_attack = function() end, "
            "notify_auto_active_skill_cast = function() end "
            "}) "
            "sys.update_attack_skills(0.1) "
            "math.random = old_random "
            "assert(notify_count == 2) "
            "local reward_state = { bond_runtime = bonds.create_runtime() } "
            "assert(bonds.unlock_node(reward_state, 'bond_body_core')) "
            "assert(bonds.unlock_node(reward_state, 'bond_body_core_momentum')) "
            "assert(bonds.unlock_node(reward_state, 'bond_body_core_vitality')) "
            "assert(bonds.unlock_node(reward_state, 'bond_body_fortress')) "
            "local route_tags = bonds.collect_route_tags(reward_state) "
            "assert(route_tags.fortress == true) "
            "assert(bonds.has_route_tag(reward_state, 'fortress') == true) "
            "local rewards = require('runtime.rewards') "
            "local reward_api = rewards.create({ "
            "STATE = reward_state, "
            "message = function() end, "
            "round_number = function(v) return math.floor((v or 0) + 0.5) end, "
            "add_attr_pack = function() end, "
            "sync_basic_attack_ability = function() end, "
            "heal_hero = function() end, "
            "collect_bond_route_tags = function() return bonds.collect_route_tags(reward_state) end "
            "}) "
            "local treasure_runtime = reward_api.get_treasure_runtime() "
            "for treasure_id in pairs(reward_api.TREASURE_DEFS) do "
            "if treasure_id ~= 'echo_codex' and treasure_id ~= 'heart_guard_mirror' then "
            "treasure_runtime.discarded_treasure_ids[treasure_id] = true "
            "end "
            "end "
            "old_random = math.random "
            "math.random = function(a, b) "
            "if a and b then return a end "
            "return 0.5 "
            "end "
            "local treasure_choices = reward_api.pick_treasure_choices(1) "
            "math.random = old_random "
            "assert(#treasure_choices == 1) "
            "assert(treasure_choices[1].id == 'heart_guard_mirror') "
            "local compatibility_state = { bond_runtime = bonds.create_runtime() } "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_core')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_core_amp')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_core_essence')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_haste')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_haste_cooldown')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_haste_charge')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_mage')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_mage_flame')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_mage_frost')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_trick')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_trick_mastery')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_elementalist')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_elementalist_storm')) "
            "assert(bonds.unlock_node(compatibility_state, 'bond_magic_elementalist_lightning')) "
            "assert(bonds.has_route_tag(compatibility_state, 'resonance') == true) "
            "assert(bonds.has_route_tag(compatibility_state, 'auto_spell_burst') == true) "
            "assert(bonds.has_route_tag(compatibility_state, 'auto_spell_burst_amp') == true) "
            "assert(bonds.has_route_tag(compatibility_state, 'auto_haste_reset') == true) "
            "assert(bonds.has_route_tag(compatibility_state, 'burn') == true) "
            "assert(bonds.has_route_tag(compatibility_state, 'cold_tide') == true) "
            "assert(bonds.has_route_tag(compatibility_state, 'shock') == true) "
            "local auto_active_effects = require('runtime.auto_active_effects') "
            "local auto_damage_count = 0 "
            "local stun_buff_count = 0 "
            "local enemy_debuff_count = 0 "
            "local debuff_target = { "
            "is_exist = function() return true end, "
            "get_attr = function(_, attr) if attr == '护甲' or attr == '物理攻击' then return 100 end return 100 end, "
            "get_hp = function() return 100 end, "
            "get_point = function() return {} end, "
            "add_attr = function() end, "
            "add_buff = function(_, data) if data and data.key == 117 then stun_buff_count = stun_buff_count + 1 end if data and data.key == 201365014 then enemy_debuff_count = enemy_debuff_count + 1 end return {} end "
            "} "
            "local auto_env = { "
            "STATE = { hero = hero, attack_skill_state = { slots = { [1] = nil, [2] = { id = 'test_spell', cooldown_remaining = 1 } }, by_id = { test_spell = { id = 'test_spell', cooldown_remaining = 1 } } } }, "
            "y3 = { "
            "helper = { tonumber = tonumber }, "
            "particle = { create = function() return { is_exist = function() return false end, remove = function() end } end }, "
            "projectile = { create = function() return { is_exist = function() return false end, remove = function() end, mover_target = function() end } end }, "
            "ltimer = { wait = function(_, fn) fn() end }, "
            "game = { str_to_modifier_key = function(name) if name == '晕眩' then return 9001 end if name == '斗气压制' then return 201365014 end return 0 end } "
            "}, "
            "ATTACK_SKILL_VFX = {}, "
            "get_player = function() return {} end, "
            "is_bond_active = function() return false end, "
            "has_bond_route_tag = function(tag) return tag == 'auto_spell_burst' or tag == 'auto_spell_burst_amp' or tag == 'auto_haste_reset' or tag == 'auto_fighting_spirit' or tag == 'auto_blood_demon_burst' end, "
            "is_active_enemy = function() return true end, "
            "get_enemies_in_range = function() return { debuff_target } end, "
            "deal_skill_damage = function() auto_damage_count = auto_damage_count + 1 end, "
            "heal_hero = function() end "
            "} "
            "function hero:add_attr() end "
            "function hero:get_hp() return 20 end "
            "local auto_sys = auto_active_effects.create(auto_env) "
            "auto_sys.update(0.25) "
            "assert(auto_damage_count > 0) "
            "assert(enemy_debuff_count > 0) "
            "old_random = math.random "
            "math.random = function() return 0 end "
            "auto_sys.handle_attack_skill_cast({ id = 'test_spell' }, nil) "
            "auto_sys.update(0.25) "
            "math.random = old_random "
            "assert(auto_env.STATE.attack_skill_state.by_id.test_spell.cooldown_remaining == 0) "
            "assert(stun_buff_count > 0) "
            "local attack_upgrades = require('runtime.attack_upgrades') "
            "local upgrade_state = { "
            "skill_points = 1, "
            "resources = { wood = 999 }, "
            "current_wave_index = 1, "
            "attack_skill_state = { unlock_offer_fail_streak = 0 } "
            "} "
            "local basic_attack = { "
            "damage_ratio = 1, split_count = 0, split_ratio = 0, boss_bonus_ratio = 0, "
            "range_bonus = 0, armor_break_ratio = 0, armor_break_duration = 0, armor_break_max_stacks = 0 "
            "} "
            "local random_values = { 0, 0.30, 0, 0 } "
            "local random_index = 0 "
            "old_random = math.random "
            "math.random = function(a, b) "
            "random_index = random_index + 1 "
            "local value = random_values[random_index] or 0 "
            "if a and b then return a end "
            "return value "
            "end "
            "local upgrade_sys = attack_upgrades.create({ "
            "STATE = upgrade_state, "
            "message = function() end, "
            "get_attack_skill = function(skill_id) if skill_id == 'basic_attack' then return basic_attack end return nil end, "
            "get_empty_attack_skill_slot = function() return 2 end, "
            "get_unlocked_attack_skill_count = function() return 1 end, "
            "get_upgrade_pick_count = function() return 0 end, "
            "record_upgrade_pick = function() end, "
            "unlock_attack_skill = function(skill_id) return { id = skill_id, name = skill_id }, 2, true end, "
            "sync_basic_attack_ability = function() end, "
            "build_attack_skill_slot_text = function() return '' end, "
            "is_bond_active = function() return false end, "
            "has_active_treasure = function() return false end, "
            "collect_bond_route_tags = function() return { arcane_arrow = true } end "
            "}) "
            "upgrade_sys.show_upgrade_choices() "
            "math.random = old_random "
            "assert(upgrade_state.current_upgrade_choices[1].key == 'unlock_arcane_arrow') "
            "local choice_panel_model = require('runtime.choice_panel_model') "
            "local choice_panel_api = choice_panel_model.create({ "
            "STATE = { bond_runtime = { current_offer_round = { free_refresh_left = 0, refresh_paid_count = 0 }, current_choices = { { "
            "quality = 'rare', "
            "title_text = '体术(0/3)', "
            "subtitle_text = '体魄', "
            "desc_text = '占位描述', "
            "current_text = '当前：敏捷 +100。', "
            "advanced_text = '进阶：杀敌敏捷 +0.1，每秒敏捷 +0.2。', "
            "next_text = '后继：猎魔人。', "
            "value_text = '生命值+100\\n力量+50', "
            "effect_title = '激活[体术]链式效果：', "
            "effect_text = '斗气场域：每秒对周围1200范围内的敌人造成(60%)力量自适应伤害' "
            "} } }, choice_panel_hidden = false }, "
            "message = function() end, "
            "BondSystem = { refresh_choice = function() return true end }, "
            "ATTACK_SKILL_DEFS = {}, "
            "TREASURE_DEFS = {}, "
            "get_pending_round_choice_kind = function() return 'bond' end, "
            "get_treasure_runtime = function() return {} end, "
            "get_treasure_quality_label = function() return '' end, "
            "get_treasure_active_count = function() return 0 end, "
            "pick_treasure_choices = function() return {} end, "
            "create_bond_env = function() return {} end, "
            "refresh_upgrade_choices = function() return false end "
            "}) "
            "local panel_model = assert(choice_panel_api.get_current_choice_panel_model()) "
            "assert(#panel_model.cards == 1) "
            "assert(panel_model.cards[1].title_text == '体魄') "
            "assert(panel_model.cards[1].set_title_text == '体术(0/3)') "
            "assert(panel_model.cards[1].subtitle_text == '') "
            "assert(#(panel_model.cards[1].body_blocks or {}) >= 2, 'bond choice body blocks should show current and follow-up info') "
            "assert(panel_model.cards[1].body_blocks[2].kind == 'effect_title', 'bond choice body blocks should preserve effect title block') "
            "assert(panel_model.cards[1].body_blocks[1].segments == nil or type(panel_model.cards[1].body_blocks[1].segments) == 'table') "
            "local text_layout = require('ui.choice_panel_text_layout').build_text_layout(panel_model.cards[1].body_blocks) "
            "assert(string.find(text_layout.value_text, '\\n', 1, true) ~= nil, 'value text layout should preserve explicit multi-line attribute formatting') "
            "local overview_model = require('runtime.overview_model') "
            "local overview_api = overview_model.create({ "
            "STATE = { "
            "session_phase = 'battle', "
            "runtime_overview_mode = 'build', "
            "bond_runtime = { awaiting_choice = true, current_choices = { { display_name = '敏捷', current_text = '当前：敏捷 +100。' } } }, "
            "resources = { gold = 0, wood = 0 }, "
            "skill_points = 0, "
            "active_challenges = {}, "
            "total_enemy_alive = 0 "
            "}, "
            "CONFIG = { challenge_rules = { max_charges = 3 } }, "
            "round_number = function(v) return math.floor((v or 0) + 0.5) end, "
            "get_current_wave = function() return { name = 'wave' } end, "
            "get_boss_name = function() return 'boss' end, "
            "get_pending_round_choice_kind = function() return 'bond' end, "
            "get_hero_progress_text = function() return 'Lv.1' end, "
            "get_reward_queue_count = function() return 0 end, "
            "get_reward_queue = function() return {} end, "
            "get_mark_runtime = function() return {} end, "
            "get_treasure_runtime = function() return {} end, "
            "get_treasure_quality_label = function() return '' end, "
            "get_treasure_active_count = function() return 0 end, "
            "get_mark_active_count = function() return 0 end, "
            "build_treasure_slot_text = function(slot) return '宝物位' .. tostring(slot) end, "
            "build_mark_slot_text = function(slot) return '烙印位' .. tostring(slot) end, "
            "get_bond_runtime_bonus = function() return 0 end, "
            "get_treasure_reward_ratio = function() return 0 end, "
            "get_treasure_passive_income = function() return 0 end, "
            "build_attack_skill_slot_text = function(slot) return '技能位' .. tostring(slot) end, "
            "build_bond_slot_text = function(slot) return '羁绊位' .. tostring(slot) end, "
            "build_bond_choice_preview_text = function(index, choice) return string.format('%d. %s | %s', index, choice.display_name, choice.current_text) end, "
            "build_bond_progress_lines = function() return { '成长 · 敏捷线 1/3 | 可选：猎魔人' } end "
            "}) "
            "local overview = overview_api.get_runtime_overview_model() "
            "assert(#(overview.sections.pending.lines or {}) >= 3) "
            "assert(string.find(overview.sections.pending.lines[2], '1.', 1, true) ~= nil, 'overview should show bond choice preview lines') "
            "assert(string.find(overview.sections.pending.lines[2], ' | ', 1, true) ~= nil, 'overview preview should keep compact summary structure') "
            "assert(string.find(overview.sections.progress.lines[1], '1/3', 1, true) ~= nil, 'overview should show bond progress lines') "
            "print('runtime bonds chain smoke ok')"
    )
    with tempfile.NamedTemporaryFile('w', encoding='utf-8', suffix='.lua', delete=False) as handle:
        handle.write(smoke_source)
        smoke_path = Path(handle.name)
    try:
        smoke = run([str(LUA), str(smoke_path)])
    finally:
        smoke_path.unlink(missing_ok=True)
    assert_ok(smoke, 'runtime bonds smoke failed')

    choice_panel_content = CHOICE_PANEL_MODEL.read_text(encoding='utf-8')
    overview_content = OVERVIEW_MODEL.read_text(encoding='utf-8')
    boot_content = BOOT.read_text(encoding='utf-8')
    bonds_chain_content = BONDS_CHAIN.read_text(encoding='utf-8')
    bond_nodes_content = NODE_DEFS.read_text(encoding='utf-8')
    bond_root_sets_csv_content = CSV_BOND_ROOT_SETS.read_text(encoding='utf-8')
    bond_nodes_csv_content = CSV_BOND_NODES.read_text(encoding='utf-8')
    input_events_content = INPUT_EVENTS.read_text(encoding='utf-8')
    attack_skills_content = ATTACK_SKILLS.read_text(encoding='utf-8')
    attack_upgrades_content = ATTACK_UPGRADES.read_text(encoding='utf-8')
    auto_active_effects_content = AUTO_ACTIVE_EFFECTS.read_text(encoding='utf-8')
    auto_active_effect_defs_content = AUTO_ACTIVE_EFFECT_DEFS.read_text(encoding='utf-8')
    rewards_content = REWARDS.read_text(encoding='utf-8')
    ability_config_content = BOND_ABILITY_CONFIG.read_text(encoding='utf-8')

    assert_contains(choice_panel_content, 'build_bond_body_blocks', 'choice_panel_model.lua should build structured bond body blocks')
    assert_contains(overview_content, 'build_bond_progress_lines', 'overview_model.lua should render bond progress bridge text')
    assert_contains(overview_content, 'progress = {', 'overview_model.lua should expose progress section key')
    assert_not_contains(overview_content, 'swallowed = {', 'overview_model.lua should not keep swallowed section key')
    assert_contains(overview_content, '链路进度', 'overview_model.lua should expose bond progress title')
    assert_contains(boot_content, '链式羁绊', 'boot.lua should expose chain-bond wording')
    assert_contains(boot_content, 'show_bond_progress', 'boot.lua should expose bond progress bridge')
    assert_not_contains(boot_content, 'show_swallowed_bonds', 'boot.lua should not keep swallowed progress bridge')
    assert_not_contains(boot_content, 'build_swallowed_bond_text', 'boot.lua should not keep swallowed bond text bridge')
    assert_contains(boot_content, 'collect_bond_route_tags', 'boot.lua should inject bond route tags into rewards')
    assert_contains(input_events_content, 'show_bond_progress', 'input_events.lua should use bond progress handler')
    assert_not_contains(input_events_content, 'show_swallowed_bonds', 'input_events.lua should not keep swallowed progress handler')
    assert_contains(bonds_chain_content, 'function M.show_bond_progress', 'bonds_chain.lua should expose bond progress output')
    assert_contains(bonds_chain_content, 'build_manual_color_segments', 'bonds_chain.lua should build manual colored text segments from doc text')
    assert_contains(BONDS_CHAIN.read_text(encoding='utf-8'), 'segments = build_manual_color_segments', 'bonds_chain.lua should attach manual color segments onto body blocks')
    assert_contains(bond_root_sets_csv_content, '斗气场域：每秒对周围1200范围内的敌人造成60%力量的自适应伤害', 'bond_root_sets.csv should align body root effect text with doc wording')
    assert_contains(bond_root_sets_csv_content, '魔爆术：每隔18秒，触发1次魔爆术，对300范围内的敌人造成200%智力的自适应伤害', 'bond_root_sets.csv should align magic root effect text with doc wording')
    assert_contains(bond_root_sets_csv_content, '穿云箭：每攻击15次，射出1支穿云箭，对直线敌人造成300%敏捷的自适应伤害', 'bond_root_sets.csv should align archery root effect text with doc wording')
    assert_not_contains(bond_nodes_csv_content, '挑战伤害+15%，所有挑战冷却时间减少。', 'bond challenge line text should not claim unimplemented challenge bonuses')
    assert_not_contains(bonds_chain_content, '每18 秒触发，对300 范围造成 200% 智力伤害', 'bonds_chain.lua should not keep abbreviated magic root effect text')
    assert_not_contains(bonds_chain_content, '每攻击 15 次射出 1 支，造成 300% 敏捷伤害', 'bonds_chain.lua should not keep abbreviated archery root effect text')
    assert_not_contains(bonds_chain_content, 'function M.show_swallowed_bonds', 'bonds_chain.lua should not keep swallowed progress output')
    assert_not_contains(bonds_chain_content, 'function M.build_swallowed_bond_text', 'bonds_chain.lua should remove swallowed bond text helper')
    assert_not_contains(bonds_chain_content, 'swallowed_bonds = {},', 'bonds_chain.lua should not keep swallowed bond runtime field')
    assert_contains(bond_nodes_csv_content, 'bond_growth_demon_hunter,猎魔人,', 'bond_nodes.csv should expose xmind growth chain naming')
    assert_contains(bond_nodes_csv_content, 'bond_archery_multishot,多重箭,', 'bond_nodes.csv should expose archery chain naming')
    assert_contains(bond_nodes_csv_content, 'bond_magic_elementalist,元素师,', 'bond_nodes.csv should expose magic chain naming')
    assert_contains(bond_nodes_csv_content, 'bond_body_charge_breaker,陷阵,', 'bond_nodes.csv should expose body chain naming')
    assert_contains(ability_config_content, '"name": "敏捷"', 'bond ability config should mirror new root node name')
    assert_contains(ability_config_content, '"name": "猎魔人"', 'bond ability config should mirror growth branch name')
    assert_contains(ability_config_content, '"name": "元素师"', 'bond ability config should mirror magic branch name')
    assert_contains(ability_config_content, '"name": "陷阵"', 'bond ability config should mirror body branch name')
    assert_contains(attack_skills_content, 'notify_bond_attack_skill_cast', 'attack_skills.lua should notify bond skill-cast hook')
    assert_not_contains(attack_skills_content, 'local is_bond_active = env.is_bond_active', 'attack_skills.lua should not depend on env.is_bond_active anymore')
    assert_contains(attack_upgrades_content, 'collect_bond_route_tags', 'attack_upgrades.lua should consume bond route tags')
    assert_not_contains(attack_upgrades_content, 'LEGACY_BOND_ROUTE_TAG_FALLBACKS', 'attack_upgrades.lua should not keep legacy bond route tag fallbacks')
    assert_contains(auto_active_effects_content, 'has_bond_route_tag', 'auto_active_effects.lua should consume bond route tags')
    assert_contains(auto_active_effects_content, 'add_buff', 'auto_active_effects.lua should apply buff-based control/debuff hooks')
    assert_not_contains(auto_active_effects_content, 'local is_bond_active = env.is_bond_active', 'auto_active_effects.lua should not depend on env.is_bond_active anymore')
    assert_contains(auto_active_effects_content, 'stun = 117', 'auto_active_effects.lua should use fixed stun modifier key to avoid load-time string conversion crashes')
    assert_not_contains(auto_active_effects_content, "str_to_modifier_key and str_to_modifier_key('", 'auto_active_effects.lua should not resolve modifier keys from localized names during module create')
    assert_not_contains(boot_content, '  is_bond_active = is_bond_active,', 'boot.lua should not inject env.is_bond_active into attack_skills anymore')
    assert_contains(boot_content, 'str_to_modifier_key', 'boot.lua should wire modifier key lookup for auto effects')
    assert_contains(auto_active_effect_defs_content, "modifier_key = 201365014", 'auto_active_effect defs should bind fighting spirit debuff resource id')
    assert FIGHTING_SPIRIT_MODIFIER.exists(), 'fighting spirit modifier resource should exist'
    assert_contains(rewards_content, 'best_with_tags', 'rewards.lua should read best_with_tags for treasure weighting')

    print('runtime bonds chain smoke ok')


if __name__ == '__main__':
    main()
