local list = {
  {
    id = 'spell_burst',
    source_type = 'bond',
    source_id = 'auto_spell_burst',
    trigger_type = 'periodic',
    cooldown = 18.0,
    range = 900,
    radius = 300,
    damage_ratio = 2.0,
    vfx = 'arcane_arrow',
  },
  {
    id = 'haste_reset',
    source_type = 'bond',
    source_id = 'auto_haste_reset',
    trigger_type = 'on_attack_skill_cast',
    chance = 0.07,
    vfx = 'arcane_arrow',
  },
  {
    id = 'fighting_spirit_field',
    source_type = 'bond',
    source_id = 'auto_fighting_spirit',
    trigger_type = 'periodic',
    cooldown = 1.0,
    radius = 1200,
    damage_ratio = 0.60,
    extra_hp_ratio = 0.30,
    armor_reduction_ratio = 0.10,
    attack_reduction_ratio = 0.30,
    modifier_key = 201365014,
    vfx = 'thunder',
  },
  {
    id = 'rapid_overdrive',
    source_type = 'bond',
    source_id = 'auto_rapid_overdrive',
    trigger_type = 'on_basic_attack_count',
    chance = 0.20,
    duration = 5.0,
    attack_speed_bonus = 100,
    vfx = 'thunder',
  },
  {
    id = 'blood_demon_burst',
    source_type = 'bond',
    source_id = 'auto_blood_demon_burst',
    trigger_type = 'periodic',
    threshold_step = 0.35,
    blast_radius = 320,
    damage_ratio = 0.50,
    heal_ratio = 0.20,
    vfx = 'thunder',
  },
  {
    id = 'charge_breaker_rally',
    source_type = 'bond',
    source_id = 'auto_charge_breaker_rally',
    trigger_type = 'on_kill',
    counter_required = 200,
    duration = 10.0,
    attr = {
      ['力量'] = 20,
      ['敏捷'] = 20,
      ['智力'] = 20,
      ['攻击速度'] = 50,
      ['技能急速'] = 30,
    },
    vfx = 'thunder',
  },
  {
    id = 'guardian_pulse',
    source_type = 'treasure',
    source_id = 'heart_guard_mirror',
    trigger_type = 'periodic',
    cooldown = 10.0,
    heal_ratio = 0.08,
    vfx = 'arcane_arrow',
  },
  {
    id = 'harvest_blade',
    source_type = 'treasure',
    source_id = 'harvest_flask',
    trigger_type = 'on_kill',
    cooldown = 1.2,
    range = 700,
    damage_ratio = 0.90,
    vfx = 'arcane_arrow',
  },
  {
    id = 'coin_burst',
    source_type = 'treasure',
    source_id = 'coin_casket',
    trigger_type = 'periodic',
    cooldown = 5.5,
    range = 900,
    hp_threshold = 0.55,
    radius = 220,
    damage_ratio = 0.80,
    vfx = 'flame_arrow',
  },
  {
    id = 'bloodrage_stomp',
    source_type = 'mark',
    source_id = 'war_god_mark',
    trigger_type = 'on_basic_attack_count',
    counter_required = 8,
    cooldown = 1.5,
    radius = 300,
    damage_ratio = 1.20,
    vfx = 'thunder',
  },
  {
    id = 'starfire_echo',
    source_type = 'mark',
    source_id = 'storm_mark',
    trigger_type = 'on_attack_skill_cast',
    cooldown = 1.2,
    range = 900,
    damage_ratio = 0.72,
    vfx = 'arcane_arrow',
  },
}

local by_id = {}
for _, def in ipairs(list) do
  by_id[def.id] = def
end

return {
  list = list,
  by_id = by_id,
}
