local list = {
  {
    id = 'chain_pulse',
    source_type = 'bond',
    source_id = 'chain',
    trigger_type = 'periodic',
    cooldown = 6.0,
    range = 900,
    primary_ratio = 1.00,
    chain_bounces = 2,
    chain_radius = 420,
    chain_ratio = 0.70,
    vfx = 'thunder',
  },
  {
    id = 'frost_ring',
    source_type = 'bond',
    source_id = 'cold_tide',
    trigger_type = 'periodic',
    cooldown = 7.5,
    radius = 280,
    damage_ratio = 0.95,
    vfx = 'frost_arrow',
  },
  {
    id = 'ember_volley',
    source_type = 'bond',
    source_id = 'burn',
    trigger_type = 'periodic',
    cooldown = 6.5,
    range = 900,
    volley_count = 3,
    damage_ratio = 0.85,
    splash_radius = 165,
    splash_ratio = 0.55,
    vfx = 'flame_arrow',
  },
  {
    id = 'guardian_pulse',
    source_type = 'treasure',
    source_id = 'heart_guard_mirror',
    trigger_type = 'periodic',
    cooldown = 10.0,
    heal_ratio = 0.08,
    vfx = 'arcane_arrow',
  },
  {
    id = 'harvest_blade',
    source_type = 'treasure',
    source_id = 'harvest_flask',
    trigger_type = 'on_kill',
    cooldown = 1.2,
    range = 700,
    damage_ratio = 0.90,
    vfx = 'arcane_arrow',
  },
  {
    id = 'coin_burst',
    source_type = 'treasure',
    source_id = 'coin_casket',
    trigger_type = 'periodic',
    cooldown = 5.5,
    range = 900,
    hp_threshold = 0.55,
    radius = 220,
    damage_ratio = 0.80,
    vfx = 'flame_arrow',
  },
  {
    id = 'bloodrage_stomp',
    source_type = 'mark',
    source_id = 'war_god_mark',
    trigger_type = 'on_basic_attack_count',
    counter_required = 8,
    cooldown = 1.5,
    radius = 300,
    damage_ratio = 1.20,
    vfx = 'thunder',
  },
  {
    id = 'starfire_echo',
    source_type = 'mark',
    source_id = 'storm_mark',
    trigger_type = 'on_attack_skill_cast',
    cooldown = 1.2,
    range = 900,
    damage_ratio = 0.72,
    vfx = 'arcane_arrow',
  },
}

local by_id = {}
for _, def in ipairs(list) do
  by_id[def.id] = def
end

return {
  list = list,
  by_id = by_id,
}
