return {
  id = 'elemental_throne',
  name = '元素王座',
  quality = 'legendary',
  required_count = 1,
  pool_weight = 0,
  tier = 't3',
  bond_role = 'mother',
  result_type = 'terminal_swallow',
  target_quality = 'legendary',
  route_tags = { 'element', 'late_game' },
  compose_inputs = { 'flame_thunder_overload', 'frost_arcane_prism' },
  compose_hint = '炎雷过载 + 霜奥棱镜 自动合成。',
  is_recipe_only = true,
  bond_effect_desc = '全伤害 +18%，技能伤害 +25%，四系关键词全部再上 1 档。',
  runtime = {
    all_damage_bonus = 0.18,
    skill_damage_bonus = 0.25,
    secondary_targets = 1,
    ignite_duration = 1,
    ignite_tick_ratio = 0.10,
    shard_count = 1,
    shard_ratio = 0.15,
    shock_duration = 1,
    shock_bonus = 0.10,
    field_radius = 120,
    field_ratio = 0.20,
  },
}
