return {
  id = 'flame_thunder_overload',
  name = '炎雷过载',
  quality = 'epic',
  required_count = 1,
  pool_weight = 0,
  tier = 't2',
  bond_role = 'mother',
  result_type = 'evolve_keep',
  target_quality = 'epic',
  route_tags = { 'element', 'burst' },
  compose_inputs = { 'burn', 'shock', 'resonance' },
  compose_hint = '灼烧 + 感电 + 共鸣 自动合成。',
  is_recipe_only = true,
  bond_effect_desc = '法术伤害 +22%；点燃每秒伤害提高并会向附近扩散；天雷感电延长并在落点形成电场。',
  runtime = {
    skill_damage_bonus = 0.22,
    ignite_tick_ratio = 0.14,
    ignite_spread_radius = 180,
    shock_duration = 2,
    shock_bonus = 0.15,
    field_radius = 120,
    field_ratio = 0.25,
  },
}
