return {
  id = 'frost_arcane_prism',
  name = '霜奥棱镜',
  quality = 'epic',
  required_count = 1,
  pool_weight = 0,
  tier = 't2',
  bond_role = 'mother',
  result_type = 'evolve_keep',
  target_quality = 'epic',
  route_tags = { 'element', 'control' },
  compose_inputs = { 'cold_tide', 'arcane', 'resonance' },
  compose_hint = '寒潮 + 奥术 + 共鸣 自动合成。',
  is_recipe_only = true,
  bond_effect_desc = '法术伤害 +20%；奥术箭次级目标 +2 并带小爆裂；寒冰箭碎裂伤害提高并额外裂出 2 枚冰片。',
  runtime = {
    skill_damage_bonus = 0.20,
    secondary_targets = 2,
    burst_radius = 150,
    burst_ratio = 0.30,
    shatter_bonus = 0.25,
    shard_count = 2,
    shard_ratio = 0.25,
  },
}
