return {
  id = 'hunter',
  name = '猎手',
  quality = 'rare',
  required_count = 2,
  pool_weight = 9,
  tier = 't1',
  bond_role = 'material',
  result_type = 'evolve_keep',
  target_quality = 'rare',
  route_tags = { 'basic_attack', 'boss' },
  compose_inputs = {},
  compose_hint = '连射猎杀路线的 Boss / 精英素材。',
  bond_effect_desc = '对精英与Boss伤害额外+25%，首次命中时追加50%攻击力伤害。',
  runtime = {
    boss_damage_bonus = 0.25,
    elite_damage_bonus = 0.25,
    hunter_first_hit_ratio = 0.50,
  },
}
