return {
  id = 'hunt_decree',
  name = '狩杀号令',
  quality = 'epic',
  required_count = 1,
  pool_weight = 0,
  tier = 't2',
  bond_role = 'mother',
  result_type = 'evolve_keep',
  target_quality = 'epic',
  route_tags = { 'basic_attack', 'boss' },
  compose_inputs = { 'barrage', 'hunter', 'armor_break' },
  compose_hint = '由 连射 + 猎手 + 穿甲 自动合成。',
  is_recipe_only = true,
  bond_effect_desc = '普攻伤害 +25%，额外分裂 1 个目标，并把破甲叠层上限提升到 3。对精英与 Boss 伤害额外 +30%。',
  runtime = {
    normal_attack_damage_bonus = 0.25,
    boss_damage_bonus = 0.30,
    elite_damage_bonus = 0.20,
    split_count = 1,
    split_ratio = 0.45,
    armor_break_ratio = 0.10,
    armor_break_duration = 5,
    armor_break_max_stacks = 3,
  },
}
