local helpers = require 'entry_objects.helpers'
local RecipeObjects = require 'entry_objects.bond_recipes'

local bond_module_paths = {
  'entry_objects.bonds.blessing',
  'entry_objects.bonds.berserk',
  'entry_objects.bonds.hunter',
  'entry_objects.bonds.greed',
  'entry_objects.bonds.barrage',
  'entry_objects.bonds.chain',
  'entry_objects.bonds.arcane',
  'entry_objects.bonds.execute',
  'entry_objects.bonds.growth',
  'entry_objects.bonds.fortress',
  'entry_objects.bonds.armor_break',
  'entry_objects.bonds.burn',
  'entry_objects.bonds.cold_tide',
  'entry_objects.bonds.shock',
  'entry_objects.bonds.resonance',
  'entry_objects.bonds.tailwind',
  'entry_objects.bonds.blood_pact',
  'entry_objects.bonds.guardian',
  'entry_objects.bonds.hunt_decree',
  'entry_objects.bonds.royal_hunt',
  'entry_objects.bonds.flame_thunder_overload',
  'entry_objects.bonds.frost_arcane_prism',
  'entry_objects.bonds.elemental_throne',
  'entry_objects.bonds.stormweb_echo',
  'entry_objects.bonds.unyielding_warpath',
  'entry_objects.bonds.holy_bastion',
}

local card_module_paths = {
  'entry_objects.bond_cards.blessing_holy_water',
  'entry_objects.bond_cards.blessing_prayer',
  'entry_objects.bond_cards.berserk_fury',
  'entry_objects.bond_cards.berserk_hot_blood',
  'entry_objects.bond_cards.hunter_pursuit',
  'entry_objects.bond_cards.hunter_purge',
  'entry_objects.bond_cards.greed_coin',
  'entry_objects.bond_cards.greed_hoard',
  'entry_objects.bond_cards.barrage_swiftstring',
  'entry_objects.bond_cards.barrage_draw',
  'entry_objects.bond_cards.barrage_spread',
  'entry_objects.bond_cards.chain_echo',
  'entry_objects.bond_cards.chain_return',
  'entry_objects.bond_cards.chain_pursue',
  'entry_objects.bond_cards.arcane_chant',
  'entry_objects.bond_cards.arcane_conduit',
  'entry_objects.bond_cards.arcane_focus',
  'entry_objects.bond_cards.execute_weakness',
  'entry_objects.bond_cards.execute_suppress',
  'entry_objects.bond_cards.execute_thrust',
  'entry_objects.bond_cards.growth_hone',
  'entry_objects.bond_cards.growth_accumulate',
  'entry_objects.bond_cards.growth_merit',
  'entry_objects.bond_cards.growth_charge',
  'entry_objects.bond_cards.fortress_iron',
  'entry_objects.bond_cards.fortress_wall',
  'entry_objects.bond_cards.fortress_heal',
  'entry_objects.bond_cards.fortress_stable',
  'entry_objects.bond_cards.armor_break_rend',
  'entry_objects.bond_cards.armor_break_breach',
  'entry_objects.bond_cards.burn_ember',
  'entry_objects.bond_cards.burn_kindling',
  'entry_objects.bond_cards.cold_tide_frost_mark',
  'entry_objects.bond_cards.cold_tide_splinter',
  'entry_objects.bond_cards.shock_static',
  'entry_objects.bond_cards.shock_conduct',
  'entry_objects.bond_cards.resonance_overtone',
  'entry_objects.bond_cards.resonance_tuning',
  'entry_objects.bond_cards.tailwind_gale',
  'entry_objects.bond_cards.tailwind_longshot',
  'entry_objects.bond_cards.blood_pact_thirst',
  'entry_objects.bond_cards.blood_pact_ferocity',
  'entry_objects.bond_cards.guardian_barrier',
  'entry_objects.bond_cards.guardian_watch',
}

local defs = helpers.load_list(bond_module_paths)
local cards = helpers.load_list(card_module_paths)

return {
  defs = defs,
  defs_by_id = helpers.list_to_map(defs),
  cards = cards,
  cards_by_id = helpers.list_to_map(cards),
  recipes = RecipeObjects.list,
  recipes_by_output_bond_id = RecipeObjects.by_output_bond_id,
}
