return {
  id = 'royal_hunt',
  name = '王庭围猎',
  quality = 'legendary',
  required_count = 1,
  pool_weight = 0,
  tier = 't3',
  bond_role = 'mother',
  result_type = 'terminal_swallow',
  target_quality = 'legendary',
  route_tags = { 'basic_attack', 'boss', 'execute' },
  compose_inputs = { 'hunt_decree', 'execute' },
  compose_hint = '狩杀号令 + 处决 自动合成。',
  is_recipe_only = true,
  bond_effect_desc = '普攻伤害 +30%；对精英与 Boss 伤害额外 +55%；首次命中追加 75% 攻击力伤害；对生命低于 12% 的敌人触发终结压制。',
  runtime = {
    normal_attack_damage_bonus = 0.30,
    boss_damage_bonus = 0.55,
    elite_damage_bonus = 0.30,
    hunter_first_hit_ratio = 0.75,
    execute_threshold = 0.12,
    execute_damage_bonus = 0.30,
  },
}
