return {
  id = 'stormweb_echo',
  name = '雷网回响',
  quality = 'epic',
  required_count = 1,
  pool_weight = 0,
  tier = 't2',
  bond_role = 'mother',
  result_type = 'terminal_swallow',
  target_quality = 'epic',
  route_tags = { 'chain', 'clear' },
  compose_inputs = { 'chain', 'shock', 'tailwind' },
  compose_hint = '连锁 + 感电 + 追风 自动合成。',
  is_recipe_only = true,
  bond_effect_desc = '弹射次数 +1，弹射伤害 +25%；天雷额外连锁 1 个目标，并在落点生成更大的电场。',
  runtime = {
    chain_bounces = 1,
    chain_ratio = 0.25,
    extra_targets = 1,
    shock_duration = 2,
    field_radius = 160,
    field_ratio = 0.30,
  },
}
